### ISSUE TITLE
From Drummer to Developer - career change experiences and some of my tips as a new Jnr. dev.

### ISSUE THREAD

**Issue by RocketRobC** [rails-oceania/roro#100]
I'd like to share some of the experiences and lessons I've learnt along the way to landing my first role as a dev.

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?
**Myself**
- Intended audience (beginners, intermediates, advanced)
Those embarking on a career in coding, beginners and all that are interested.

For proposals:
- Which month would you be ready for?
**September or later**

- Is this a 5m (lightning) talk, or a 15m talk?
**15m**

**Comment by tracymu** [comment]
Great title, looking forward to it Rob!

**Comment by tracymu** [comment]
You shouldn't have done such a great job Rob, now everyone is clamouring for more from you
