### ISSUE TITLE
Action Cable - Building A Chat App In Rails

### ISSUE THREAD

**Issue by DylanGriffith** [rails-oceania/roro#101]
I'd like to give a talk about the new Action Cable feature in Rails 5. It will probably be aimed at people with some rails experience. I'd like to go through some code as well as demo a working app. 

I'd be ready to talk in August.

This would need to be a 15 minute talk.

**Comment by holodigm** [comment]
Nice :+1:

**Comment by DylanGriffith** [comment]
I've just realised that I won't actually be around for the August or September meetups so I will have to close this and think about doing this when I'm sure about the next RORO event I'll be going to.

**Comment by tracymu** [comment]
Ok no worries, looking forward to it later on!
