### ISSUE TITLE
Exploring the rake gem

### ISSUE THREAD

**Issue by rudyyazdi** [rails-oceania/roro#102]
An overview about the [Rake](https://github.com/ruby/rake) gem, What it does and how it works.
If I have time at the end, everyone can share their tips and tricks about it too.

---

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)? **Myself**
- Intended audience: **beginners, intermediates**

For proposals:
- Which month would you be ready for? **Anytime after July would be good :)**
- Is this a 5m (lightning) talk, or a 15m talk? **A 15m talk**

**Comment by tracymu** [comment]
Hey @rudyyazdi  - how would you feel about talking in August?

**Comment by rudyyazdi** [comment]
@tracymu sounds good :)

**Comment by rudyyazdi** [comment]
Hey @tracymu just a quick note, I have not prepared anything yet, so it would be awesome if you could notify me when is going to be my presentation so that I can start preparing.

**Comment by tracymu** [comment]
Hi Rudy, above you have agreed August is ok for you? The August Roro is on Tuesday 9th August - let me know if there is any problem with you presenting at that one. 

thanks  so much!

**Comment by rudyyazdi** [comment]
No, all good, I just thought you'll notify me whether or not it is finalized, I also didn't see my presentation on the meetup page, so I thought I'd ask.

I'll see you then.

Thanks heaps :)

**Comment by tracymu** [comment]
Oops, sorry - well, you're on! :) Looking forward to hearing your talk.

**Comment by joshuapaling** [comment]
Thanks Rudy, really enjoyed this. Now I know the difference between a function and a task ;)

**Comment by rudyyazdi** [comment]
@joshuapaling my pleasure, thank you guys for making all this happen :)
