### ISSUE TITLE
Y U No use rails console ?!

### ISSUE THREAD

**Issue by sameera207** [rails-oceania/roro#103]
Using rails console more effectively for development, A.K.A rails console tips

------

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)? - **Proposal** I would like to give the talk by my self :)
- Intended audience: **beginners, intermediates**

For proposals:

- Which month would you be ready for? **September** (had a chat with @tracymu)
- Is this a 5m (lightning) talk, or a 15m talk? **A 15m talk**

**Comment by tracymu** [comment]
Thanks again for proposing it!

**Comment by tracymu** [comment]
@sameera207  I am putting you down for September, so let me know if anything changes :)

**Comment by sameera207** [comment]
@tracymu , thanks 👍 , September is good for me. Sure I'll let u know if anything changes

**Comment by tracymu** [comment]
Got great feedback from my Rails Girls on this! We should probably include a talk like this in the second level Rails Girls.

Thanks again Sam :)

**Comment by sameera207** [comment]
@tracymu, thanks and nice to hear good feedback.  Sure, If you want I should be able to do one  :) 

Here is the link to the slides https://speakerdeck.com/sameera207/working-with-rails-console
