### ISSUE TITLE
Security things I need to know about

### ISSUE THREAD

**Issue by jonathanyeong** [rails-oceania/roro#104]
- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)? **Proposal**
- Intended audience (beginners, intermediates, advanced). **Beginners, maybe intermediate, maybe advanced.**

For proposals:
- Which month would you be ready for? **August**
- Is this a 5m (lightning) talk, or a 15m talk? **5m lightning talk**

**Comment by joshuapaling** [comment]
I'd say if we're talking security stuff, it's definitely intermediate at least. Sounds like a good topic.

**Comment by joshuapaling** [comment]
Thanks Jono, nice talk!
