### ISSUE TITLE
A reading of a gem: Down a rabbit hole.

### ISSUE THREAD

**Issue by paradisaeidae** [rails-oceania/roro#105]
Proposal for 15m talk.
Deep details witheld for reveal in presentation

**Comment by mootpointer** [comment]
Could you give us some more details to help us fit this talk into an evening to create a good range of talks?

 - What level of experience is this talk targeted at?
 - Can you give us a brief précis (without giving away the punchline) of the talk?

**Comment by paradisaeidae** [comment]
Hi Andrew, please see your website contact form response.
I've left some dets there.

**Comment by mootpointer** [comment]
Seems like about.me is having some issues. I'm not sure why these details can't be posted here. Part of these issues is to have an open and transparent process.

If you must contact me privately, it might be worth sending me an email. My first name @ mootpointer.com

**Comment by paradisaeidae** [comment]
Hi Andrew,
So I did a test of the Pivitol hdmi with my laptop last night.
Drew a blank. (Great pun!! ;).
Is there a reset required at the command console when a non-Mac is hooked up?
I attach a photo of said lappy happy with hdmi.
I might be at another meetup there in the next weeks.
Though could liase with someone there to do a late afternoon test?
![asuslappynvidealinuxhdmidualscreen](https://cloud.githubusercontent.com/assets/440482/17541823/bba04fca-5f06-11e6-8fd3-7492c696db5c.jpg)

**Comment by mootpointer** [comment]
Perhaps more simply: can you render your presentation to a pdf and present it from a borrowed Mac?






On Wed, Aug 10, 2016 at 2:30 PM +1000, "MarkT" <notifications@github.com> wrote:












Hi Andrew,

So I did a test of the Pivitol hdmi with my laptop last night.

Drew a blank. (Great pun!! ;).

Is there a reset required at the command console when a non-Mac is hooked up?

I attach a photo of said lappy happy with hdmi.

I might be at another meetup there in the next weeks.

Though could liase with someone there to do a late afternoon test?

**Comment by paradisaeidae** [comment]
Hi Andrew,
I could, but would not.
It would over-simplify the preso.
And limit the demonstration options.

**Comment by paradisaeidae** [comment]
OK, so this is a side-rabbit-hole.
Apparently the projector manufacturers make sure they work on Apple boxen. The others being too many to test on.
And the subtleties of hdmi protocol differences do make a difference.
If I am in the area I will drop by Pivotal and enquire if there is appropriate testing window of opportunity.
Such issues are of interest to Tim's project: https://code.timvideos.us/home/

**Comment by paradisaeidae** [comment]
So this config was tested yesterday.
All OK.
Thanks Stewart!

**Comment by tracymu** [comment]
Hi @paradisaeidae 
Thanks for suggesting this talk. 
What month would you be available to present? Do you think it will be able to fit into our 15 minute time slot? (The last few Roro's we have been timing our speakers).

**Comment by paradisaeidae** [comment]
Hi Tracy,I will have the preso ready for next month. All non-conforming circumstances notwithstanding! Cya, MarkT                                                                                                                                                                                                    -- MarkTurner(+61 4) 0679 5734 :: https://plus.google.com/+MarkT :: 'Mutual Existencewins over Spooky Action At a Distance.'‎                                                                                                                                                                                                                  From: TracyMuSent: Wednesday, 14 September 2016 09:09To: rails-oceania/roroReply To: rails-oceania/roroCc: MarkT; MentionSubject: Re: [rails-oceania/roro] A reading of a gem: Down a rabbit hole. (#105)Hi @paradisaeidae 
Thanks for suggesting this talk. 
What month would you be available to present? Do you think it will be able to fit into our 15 minute time slot? (The last few Roro's we have been timing our speakers).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rails-oceania/roro","title":"rails-oceania/roro","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rails-oceania/roro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tracymu in #105: Hi @paradisaeidae \r\nThanks for suggesting this talk. \r\nWhat month would you be available to present? Do you think it will be able to fit into our 15 minute time slot? (The last few Roro's we have been timing our speakers).\r\n"}],"action":{"name":"View Issue","url":"https://github.com/rails-oceania/roro/issues/105#issuecomment-246854871"}}}

**Comment by tracymu** [comment]
Ok great, thanks Mark. We'll put you down for next month, October.

**Comment by tracymu** [comment]
Thanks for the talk Mark!

**Comment by paradisaeidae** [comment]
Hi Tracy,
And you were quite perceptive.
There was a chunk I omitted from this preso.
As I checked the clock I dynamically switched to the shortened version.
I have no scientific data on the perceived difference this made.
