### ISSUE TITLE
Writing functional code in ruby

### ISSUE THREAD

**Issue by brentonannan** [rails-oceania/roro#107]
We'd love to have you speak, or suggest a talk for Sydney Ruby. In addition to your talk topic, please mention the following:

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?

This is a talk I told Tracy I'd do after I'd had a few beers, and she's persistent, so here it is:

Writing functional code in ruby, or: How to get started thinking like an Elixir dev.

- Intended audience (beginners, intermediates, advanced)

Intermediates

For proposals:
- Which month would you be ready for?

October, or at least that's when I'm being told I'm doing it.

- Is this a 5m (lightning) talk, or a 15m talk?

Either. I haven't written anything yet, so I could go either way. I tend to be pretty verbose once I get rolling, so probably 15 min.

**Comment by tracymu** [comment]
Loving it.

**Comment by brentonannan** [comment]
Good, because I'm gonna make you help me write it.

**Comment by joshuapaling** [comment]
Hey Brenton, sounds like a good topic, but would be very tough to cover in 5 minutes. Let's put it down as a 15m talk, and you can let us know if you want to change that. 👍

**Comment by tracymu** [comment]
Thanks so much for doing this talk @brentonannan  it was great, and people were very interested, so feel free to do a follow up any time :)
