### ISSUE TITLE
Your Hackable Brain

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#108]
- Talk proposal
- Intended audience: all
- Which month would you be ready for? October
- 15m talk

**Comment by tracymu** [comment]
I keep getting comments from people saying they were going to submit talks, but then there were already so many listed that it discouraged them. So I'm being harsh and closing heaps of them.

Obviously I want you to do this talk - would love it as emergency backup

**Comment by joshuapaling** [comment]
Yep, cool, agreed.
