### ISSUE TITLE
Build a simple GraphQL API in Rails.

### ISSUE THREAD

**Issue by wayne5540** [rails-oceania/roro#109]
Github recently announced their [GraphQL API Alpha](http://githubengineering.com/the-github-graphql-api/) which is pretty cool, so I played around with [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) and want to share some experiences :)

This topic will cover some basic usage of [graphql-ruby](https://github.com/rmosolgo/graphql-ruby), showing how to build a simple GraphQL API in Rails, with some tests and demo and have fun with it 😄 
- Is this a proposal? Yes
- Intended audience: everyone, beginner friendly
- Which month would you be ready for? Nov
- Is this a 5m (lightning) talk, or a 15m talk? 10~15

**Comment by tracymu** [comment]
Thanks so much for volunteering @wayne5540 , what a great topic.

I'm putting you down for November!

**Comment by wayne5540** [comment]
Thanks @tracymu 👍

**Comment by tracymu** [comment]
Hey @wayne5540  just a reminder that you're scheduled to do this talk at the next Roro :)

Are you still available?

**Comment by wayne5540** [comment]
Yes, will be there at 8 Nov, thanks!

**Comment by joshuapaling** [comment]
Thanks @wayne5540!
