### ISSUE TITLE
The Power ⚡️ and Responsibility 😓 of Unicode Adoption ✨

### ISSUE THREAD

**Issue by glasnt** [rails-oceania/roro#110]
From the speaker that brought you https://github.com/rails-oceania/roro/issues/27; as seen at Web Directions: Code, and to be shown soon at a Ruby Conf AU near you...
- Is this a proposal?

Yup :)
- Intended audience

Beginner
- Which month would you be ready for?

January 2017 
- Is this a 5m (lightning) talk, or a 15m talk?

15 minute

✨

**Comment by tracymu** [comment]
Excited! But I think we often skip January, so I hope you're maybe available February?

**Comment by glasnt** [comment]
Sure, February also works :)

**Comment by tracymu** [comment]
I lied. I see there is a meetup scheduled for January :)

**Comment by glasnt** [comment]
@tracymu January works better for me. It gives me a chance to practice the ruby specific version of the talk, and chat about emoji and maybe include newly learnt things into my talk :)

**Comment by tracymu** [comment]
Hi @glasnt  

Sorry to be so annoying, but I was right the first time, we aren't having a January meet up.

We are having 13th December and 14th February (week after Ruby conf I believe).

If neither of these is suitable, hopefully you can talk another time in the future :)

**Comment by glasnt** [comment]
December is fine 😄

**Comment by tracymu** [comment]
fantastic. lock it in!

**Comment by joshuapaling** [comment]
Hi @glasnt, just confirming you're still good for next Tuesday's meetup?

**Comment by glasnt** [comment]
Yup! I even have slides!

**Comment by joshuapaling** [comment]
Great, see you then!

**Comment by joshuapaling** [comment]
Thanks a lot Katie, great talk! Looking forward to seeing you again at Ruby Conf.
