### ISSUE TITLE
Blinkin' leds using Ruby-serial.

### ISSUE THREAD

**Issue by paradisaeidae** [rails-oceania/roro#113]
I've recently had reason to explore options for driving multi-color leds.
High power Cree leds have very good brightness levels.
And have great multi color options.
A project board was soldered up to explore them.
Then using Ruby-serial on a RaspberrPi 'over-the-air' to control them.
This would be a 15 min show and tell.

**Comment by paulfioravanti** [comment]
@paradisaeidae I know this is very old, but is this still a presentation you would be interested in giving at a future RORO?

**Comment by paulfioravanti** [comment]
Closed due to inactivity. @paradisaeidae if you want to do this presentation, please feel free to re-open the issue :)
