### ISSUE TITLE
Effective Visual Tools for Ruby Development

### ISSUE THREAD

**Issue by rjattrill** [rails-oceania/roro#115]
- This talk will demonstrate some of the efficiencies that can be gained from using visual development tools as opposed to console / command line.   Will include:
   * refactoring
   * test management
   * git interaction

- 15 m talk for all levels

**Comment by tracymu** [comment]
Thanks so much for volunteering Ross!

This sounds like a great topic, and really different from other talks we've had. 

Let us know what month you're happy to present at too

**Comment by tracymu** [comment]
Hi @rjattrill, just confirming you're still good to present on 14th February :)

**Comment by rjattrill** [comment]
Guess so - it is coming up fast.   See you then!

**Comment by joshuapaling** [comment]
Thanks Ross, great talk!
