### ISSUE TITLE
Test Driven Bedtime Story

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#116]
This is a proposal for a 15 minute talk that I would like to give for RORO December.  Well, it's more of a "recital" than a talk: I'll be reciting a well known children's fairy tale, and we'll all be following along with the story through the (working) specs I've written for it in RSpec (they'll be up on the slides).  We spec user stories all the time, so why not a bedtime story? 😸 

I don't think there's anything too clever going on in the specs, so I would say it will be accessible for any level of Rubyist.

I'm aiming to do this at Rails Camp QLD as well, so it might end up being an encore performance for some Sydneysiders, if that's okay.

**Comment by tracymu** [comment]
Sounds so interesting - thanks @paulfioravanti  for volunteering (again!)

**Comment by joshuapaling** [comment]
Very entertaining talk @paulfioravanti, thanks a lot!
