### ISSUE TITLE
Nikolay's AI talk on keyboard layouts etc.

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#117]
https://www.youtube.com/watch?v=4O61sPaGI50

"Genetic Algorithms in Javascript"

25m Talk. Probably more advanced, but I think some interesting stuff for everyone. It's

**Comment by MadRabbit** [comment]
I can patch it to be in Ruby if you want. it's not really language specific

**Comment by joshuapaling** [comment]
OK cool, that'd be great. There's not heaps of code and the Ruby crowd mostly kinda know JS, so if you don't get time, no worries. But if you do - awesome.

**Comment by joshuapaling** [comment]
Awesome talk mate, thanks!
