### ISSUE TITLE
Proposal for talk on Prometheus for Rails.

### ISSUE THREAD

**Issue by htmldrum** [rails-oceania/roro#118]
Hey, I'd like to give a talk on using Prometheus for monitoring and analytics in a Rails app,  can do for December for intermediates, probs 15m. Outline as follows:

- Motivation / Use Case
  - Monitoring
  - Alerting
  - Querying
  - Alternative to vendors / SASS
- What it is
  - For
    - Monitoring system and TSDB
    - Focus: Operational systems monitoring for dynamic cloud environments
  - Not for
    - log collection
      - Aggregators
    - request tracing
    - durable storage
    - user/auth mgmt
- Where it’s used
  - Rack middleware
  - Counter: Sum or value that can only go up
  - Gauge: Counts that can go up and down
  - Histogram: samples observations (usually things like request durations
               or response sizes) and counts them in configurable buckets
  - Summary: Histogram + sum over all observed values
  - https://prometheus.io/docs/concepts/metric_types/
- What it’s good for
- grafana integration

- How to use it in Rails
  - High frequency data input
  - Request logging
- Live example
- Libraries / Reference / Extra reading
  - Google Analytics exporter: https://github.com/infinityworksltd/gar-exporter
  - Cloudwatch exporter: https://github.com/prometheus/cloudwatch_exporter
  - Prometheus Ruby client: https://github.com/prometheus/client_ruby
  - Postgres exporter: https://github.com/wrouesnel/postgres_exporter
  - Ceph exporter: https://github.com/digitalocean/ceph_exporter
  - Consul exporter: https://github.com/prometheus/consul_exporter
  - Webdriver exporter: https://github.com/mattbostock/webdriver_exporter

**Comment by tracymu** [comment]
Hi @htmldrum  thank you so much for volunteering!

I hope it doesn't discourage you to learn that the next speaking space we have available is March? Because we would love to hear this talk.

March or any month after would be great. Let us know what you think.

**Comment by htmldrum** [comment]
No worries - March is cool. Word of warning: it is my birthday **month**.

**Comment by tracymu** [comment]
Hello @htmldrum  Just confirming you're still cool to present on 14th March?
