### ISSUE TITLE
How to build highly scalable micro-services in Ruby using an actor model in a distributed environment

### ISSUE THREAD

**Issue by shirren** [rails-oceania/roro#119]
Hey, I'd like to give a talk on how to build highly scalable micro-services in ruby using an actor model is a distributed environment, I can do it for ~ April 2016, probably 25m. 

Motivation

* Monolithic Rails apps can be hard to maintain
* Micro-services can be more than just a buzzword
* No goto micro-service framework for Ruby

Presentation

* An actual example of how we use it, and how simple it has made our development efforts

**Comment by tracymu** [comment]
Thanks for volunteering! I'll put you down for April , and confirm closer to the date.

**Comment by shirren** [comment]
No worries @tracymu happy to be part of the community.

**Comment by mootpointer** [comment]
Hi @shirren, 25 minutes is a bit longer than we'd normally go for with a talk at rorosyd. We're trying hard to keep people engaged in the talks by keeping them snappy.

A good thing to remember with talks is that you're never going to be able to explain *everything* to everyone in 15 minutes. There are details and ephemera which can be glossed over. What you *can* do in 15 minutes is to inspire people to dig into your topic and get excited about it.

Are you okay with limiting your talk to 15 minutes?

**Comment by shirren** [comment]
@mootpointer you make a good point about engagement. 15 minutes is fine, is the expectation for me to speak at the next RORO, or the one after?

**Comment by mootpointer** [comment]
The next one – April 11th.

**Comment by shirren** [comment]
@mootpointer sounds good. Any tips?

**Comment by tracymu** [comment]
@shirren - sorry I see we never got back to you about this, are you prepared for tonight?

**Comment by shirren** [comment]
@tracymu I am prepared. I believe Hannah will relay the message on to you

**Comment by tracymu** [comment]
Thanks @shirren for your talk, you're such a smooth presenter!

I think there is definitely an interest in a part 2, when you have the inclination :)

**Comment by shirren** [comment]
Thanks @tracymu. Just let me know when it will appropriate for a follow up.
