### ISSUE TITLE
Connecting with others

### ISSUE THREAD

**Issue by lbain** [rails-oceania/roro#120]
Proposal
Audience: all
Month: April
Length: 30-35 min, but it can be shorter if needed

Blurb:
We interact with people every day, let's do it a bit better! First I'll cover a bit about improving how you connect with people day to day. Then we'll move into participating in your communities and how to make it a better experience. Finally, I'll discuss some ways to organise events that work for you, so you get the most out of the experience.

I gave this talk at KiwiPycon in September. You can watch it [here](https://www.youtube.com/watch?v=AI_TA6jgBYY&feature=youtu.be) but I thought it'd be nice to give it live, especially as I found RoRO to be such a welcoming community when I first moved to Sydney.

**Comment by tracymu** [comment]
Yay thanks @lbain 

I've heard great things about it.

**Comment by tracymu** [comment]
@joshuapaling  note the length of this talk when you're thinking about assigning other talks to April

**Comment by joshuapaling** [comment]
Yep have seen this talk online. I think we go for the full version - not often we get conference-level-preparation at RORO, so let's just have one other 15m talk for this month.

**Comment by tracymu** [comment]
Hey @lbain 

Just checking you're still cool to present on 11 April for us? :)

**Comment by lbain** [comment]
Yep, it's in my calendar and everything :)

**Comment by tracymu** [comment]
Thanks @lbain for the awesome talk! Seems like people really enjoyed and got a lot out of it.
