### ISSUE TITLE
Getting to know FactoryGirl 💃

### ISSUE THREAD

**Issue by sameera207** [rails-oceania/roro#121]
[FactoryGirl](https://github.com/thoughtbot/factory_girl) is the go to fixture replacement for ruby/rails nowadays. Even though `Factory Girl` is mostly used  specs/tests, its a great way to generate sample data in your development env too. 

`Factory Girl` gives you lots of options to build factories with more readable / simpler way, and also you can build complex associations via factories and keep your specs clean and readable. 

In this talk, I will be going through some points on how to create clean (DRY), extendable factories. And also I'll talk a bit about generating dynamic data for factories. 

💃💃💃💃💃💃💃💃💃💃💃💃  
 
- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?
_talk_

- Intended audience (beginners, intermediates, advanced)
   _I believe mostly beginners, intermediates_

For proposals:
- Which month would you be ready for?
   _March or May_

- Is this a 5m (lightning) talk, or a 15m talk?
  _15 mins talk_

**Comment by tracymu** [comment]
We should be giving you a repeat speaker bonus!

Thanks so much for volunteering, I've put you down for March!

**Comment by sameera207** [comment]
@tracymu , lol.... I'm 👍  for March, thx
