### ISSUE TITLE
"What the Functional? (What, Why, How)

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#122]
See more at https://twitter.com/damncabbage/status/846551921091522560

This is a 30m talk from Rob Howard, already given before at RC NZ. So, we could see if Rob's open to doing a shorter version, or, depending on how people like Lucy's longer talk this month, we could consider giving Rob a longer slot too.

**Comment by damncabbage** [comment]
If this happens I'll be definitely be going for a tightened-up version; the talk is getting a partial rewrite in an effort to achieve this. It'd still love 20-25 minutes, though.

A summary, to give you a better idea of the focus:

> We spend a lot of time building up libraries and applications. They can get complex, and feel like they can get out of control. Functional Programming is an approach that lets us zoom in and stay focused on small parts of a codebase at a time.
>
> We'll dig down into what Functional Programming is, what comes from it, and show you can do FP in pretty much any language.
>
> (This talk will be illustrated with Ruby and examples drawn from the Ruby ecosystem, but the concepts will intentionally be generally applicable.)

**Comment by joshuapaling** [comment]
OK cool, thanks Rob. @tracymu at 20 - 25 mins we could probably put this down as a normal "full length" talk, and have one other full length and one lightning on that night?

**Comment by damncabbage** [comment]
Hello again. I'm awfully sorry, but I actually can't do May (9th); I didn't realise I had a schedule clash until last night. 💦 

I can make June; in any case, please let me know what other month might suit.

**Comment by tracymu** [comment]
@damncabbage  It's no problem at all :)

June would be great. I'll put you down for then.

**Comment by damncabbage** [comment]
Just confirming I'm still good for June.

(I think the [meetup page](https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/239659910/) itself needs updating, with either this and other talks, or a TBA or something; it's currently wrong.)

**Comment by joshuapaling** [comment]
Thanks, Rob. I'll update meetup.

**Comment by joshuapaling** [comment]
Confirming you're still good for tomorrow night, @damncabbage ?

**Comment by damncabbage** [comment]
Yep. :)

**Comment by joshuapaling** [comment]
Thanks a lot for speaking tonight @damncabbage!

**Comment by damncabbage** [comment]
Thanks for having me. :)

**Comment by joshuapaling** [comment]
@damncabbage are your slides online anywhere? (Or could you put them online?)
