### ISSUE TITLE
Raspberry flavoured Ruby

### ISSUE THREAD

**Issue by RocketRobC** [rails-oceania/roro#123]
For christmas I was given a Raspberry Pi and since then I've been playing around with with what I can get it to do using Ruby. 

I'd like to do a 5 to 10 min talk in June or July on one of the little projects I've been working on using 433MHz transmitters and receivers that might inspire people to dig out their dusty Pi's and have some fun.

**Comment by joshuapaling** [comment]
Confirming you're still good for tomorrow night, @RocketRobC ?

**Comment by RocketRobC** [comment]
Yes, no worries. Hey, is there a power outlet near the lectern? I was thinking of doing a small demo with a pi but it will need power.

**Comment by mootpointer** [comment]
Yup. There's power. You may want an extension cable if you're dealing with a large wall wart.



________________________________

**Comment by joshuapaling** [comment]
Thanks a lot for speaking tonight @RocketRobC!

**Comment by joshuapaling** [comment]
@RocketRobC are your slides online anywhere? (Or could you put them online?)

**Comment by RocketRobC** [comment]
@joshuapaling Yeah you can see the slides at https://gitpitch.com/RocketRobC/raspberry_flavoured_ruby/master?grs=gitlab&t=black
