### ISSUE TITLE
Server-side split testing

### ISSUE THREAD

**Issue by nicholashibberd** [rails-oceania/roro#124]
Hi, I'd like to do a 15m talk about server-side split testing in a Rails app. 

I will cover an introduction to what split testing (A/B testing) is, the difference between server-side and client-side solutions, the things you have to be mindful of when implementing a server-side solution, a run-through of the implementation that we use in my company's rails app, and I will finish with some case studies of a few of the split tests that we have run and the surprising results that we have received.

From a technical perspective I will cover:

- How to identify sessions that are to be part of the experiment
- How to ensure an even, or controlled, split between different versions
- How to ensure that your implementation respects your caching infrastructure
- How to ensure a single customer sees the same page every time they visit
- How to vary your content based on the variant that has been chosen
- How to provide the data back to the reporting engine

I would hope that the content is fairly accessible to beginners, particularly the case studies, and I will try and keep the code samples light, but there should be a bit in there for more experienced devs too.

It should be ready for June, or May at a push.

Does that sound like something you'd like to see?

Nick

**Comment by tracymu** [comment]
Of course it is!

June would be great for us thanks Nicholas - looking forward to it :)

**Comment by joshuapaling** [comment]
Hi Nick, can you give us your twitter handle, and we'll add that to the meetup page along with your talk?

**Comment by nicholashibberd** [comment]
Sure, @nickhibberd

**Comment by joshuapaling** [comment]
Confirming you're still good for tomorrow night, @nicholashibberd ?

**Comment by nicholashibberd** [comment]
Yep, still good. See you later.

**Comment by joshuapaling** [comment]
Thanks a lot for speaking tonight @nicholashibberd!

**Comment by joshuapaling** [comment]
@nicholashibberd are your slides online anywhere? (Or could you put them online?)

**Comment by nicholashibberd** [comment]
Yep, here they are http://bit.ly/2s860dy
