### ISSUE TITLE
The repository pattern in Rails apps

### ISSUE THREAD

**Issue by rgravina** [rails-oceania/roro#126]
I was thinking of giving a short lightning talk (5-10mins?) at the next Roro (May 9th?) on applying the [Repository pattern](https://martinfowler.com/eaaCatalog/repository.html) in Rails apps. It's a pretty simple concept that used a lot in other "enterprise" frameworks but for some reason isn't commonly seen in Rails apps. I personally think it's saved my apps from having slow tests and hard to isolate domain logic.

The general idea is to wrap all database access for a model in a class responsible for making the query and returning results. It encapsulates this code and makes it easy to mock/stub out in your tests. That's pretty much it. That's why I think this is a 5-10 minute talk max.

It's also generally related to SOLID and generally accepted good unit testing practices. I could link to some talks which you might also like to watch at the end of the talk (like [this one](http://blog.thecodewhisperer.com/permalink/integrated-tests-are-a-scam) - it's awsome). This is a super interesting tangent you might like to go down and discuss.

**Comment by tracymu** [comment]
Hello @rgravina 

Thanks again for volunteering

Please note the venue change for next Tuesday - it is less convenient for you sorry :)

https://github.com/rails-oceania/roro/wiki/rorosyd-May-2017

**Comment by joshuapaling** [comment]
Thanks a lot for speaking last night @rgravina. Are your slides online anywhere? If you reply with a link, I'll post it in the #rorosyd slack channel.

**Comment by rgravina** [comment]
Here's a PDF export of the Keynote slides. I think you should be able to just link to the file here. Thanks for having me talk! I'll link to the code in this comment once I've added it to Github also :)
[rails-repositories-talk.pdf](https://github.com/rails-oceania/roro/files/989921/rails-repositories-talk.pdf)
