### ISSUE TITLE
Maintaining Shared Libraries in a Big Rails Project

### ISSUE THREAD

**Issue by adlerhsieh** [rails-oceania/roro#127]
When working in a huge project, it is common that multiple Rails applications share the same set of models, tasks, and other sets of code. One good practice is to extract these classes into separate gems and install them as dependencies. However, there are many problems we have to deal with. For example, which applications the migrations should go into? How to decide if a model belongs to a specific application or a shared library?

This talk is going to share my experience on the difficulties I ran into when maintaining shared libraries, and how did I overcome them. It will cover:

- At which point should we consider extracting code to shared libraries.
- Some common issues.
- Some bad practices that will make us regret.

These are other details:

- Intended audience is beginners and intermediates.
- This is a 10-15m talk.
- It's good to have this on July or August.

Feedback is welcome :)

**Comment by tracymu** [comment]
Hello @adlerhsieh  sorry for not getting back to you sooner. This sounds great. So you have availability for July?

**Comment by adlerhsieh** [comment]
Thanks for your reply. Yes July would be great :)

**Comment by jamsi** [comment]
This is a very interesting topic - +1 for this talk :)

**Comment by adlerhsieh** [comment]
Thanks for your support 😄

**Comment by adlerhsieh** [comment]
Just wanna to add that my twitter account is [@adler_hsieh](https://twitter.com/adler_hsieh)
