### ISSUE TITLE
MiniTest and Fixtures

### ISSUE THREAD

**Issue by knockycode** [rails-oceania/roro#128]
I want to give this talk about MiniTest and Fixtures myself.

Intended audience is beginner and upwards.

I think the talk will be ready for July or August at the latest.

It will go for 15 minutes.

**Comment by tracymu** [comment]
Thanks for volunteering @knockycode ! Can I put you down for July?

**Comment by knockycode** [comment]
Hey @tracymu, yup I can make July.

**Comment by knockycode** [comment]
BTW, my twitter is https://twitter.com/knockycode

And I'd like to alter my talk to "15 minutes Minitest recipe with Fixtures"
