### ISSUE TITLE
How not to give advice about Markdown

### ISSUE THREAD

**Issue by keithpitty** [rails-oceania/roro#129]
Proposal:  This lightning talk relates to an experience where I gave some imperfect advice about Markdown but learned some valuable lessons in the process.

Intended audience:  All, but especially beginners

**Comment by tracymu** [comment]
Thanks so much @keithpitty  I have added you to September :)

**Comment by keithpitty** [comment]
You're welcome.

**Comment by paulfioravanti** [comment]
@keithpitty thanks so much for your talk!  Are you planning on making the slide deck public somewhere like Slideshare or Speakerdeck?  If so, when you do it, would you please be able to any of the following:

- send out a tweet with a link to the slides adding the `#rorosyd` hashtag and/or mentioning the `@rorosyd` account
- post a link to the slides in the Meetup comments at: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/242048097/

Cheers!

**Comment by keithpitty** [comment]
Will do this evening.

**Comment by keithpitty** [comment]
Done.
