### ISSUE TITLE
Let's Chat - Ruby and Elixir. An exploration of cross language communication

### ISSUE THREAD

**Issue by tracymu** [rails-oceania/roro#130]
I'm submitting this on behalf of @gogogarrett
It will be 15 mins

**Comment by paulfioravanti** [comment]
@gogogarret thanks for the talk!  I see you've made your slidedecks public and put them up in the meetup comments, which is awesome.  If you wanted to do something a bit further, please send out a tweet with a link to the slides adding the `#rorosyd` hashtag and/or mentioning the `@rorosyd` account and that would be great!  Thanks!
