### ISSUE TITLE
Rebalancing your Extreme Programming Wheels

### ISSUE THREAD

**Issue by MarkRatjens** [rails-oceania/roro#133]
A 15-minute health check of The Coding Circle from Xtreme Programming (Testing, Refactoring, Pairing-Programming). In the Rails community we focus much on testing, we might do pair programming but how much refactoring happens? What are the consequences?

**Comment by paulfioravanti** [comment]
@MarkRatjens thanks so much for your talk last night!

Are you planning on making the slide deck public somewhere like Slideshare or Speakerdeck?  If so, when you do it, would you please be able to any of the following:

- send out a tweet with a link to the slides adding the `#rorosyd` hashtag and/or mentioning the `@rorosyd` account
- post a link to the slides in the Meetup comments at: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/242048097/

Cheers!
