### ISSUE TITLE
A Pull Request Has Been Submitted

### ISSUE THREAD

**Issue by pauloancheta** [rails-oceania/roro#134]
Hey 👋,

Wanting to give a talk on a few housekeeping before actually submitting a pull request to either open source or even private repositories for your companies. The intention of this is to make a reviewer's job a bit easier.

This is beginner friendly but intermediates can benefit from it too.

The talk will be coming from one of my blog posts with a twist to a bit more rails (or at least planning to put more rails-ey things) so it should be ready by the end of the month.

**Comment by tracymu** [comment]
Hey Paulo - thanks so much for volunteering! 

This sounds like an interesting topic - and something that will be relevant for everyone.

How long were you thinking? Our full talks usually go around 15 minutes, and we also have shorter talks. The shortest would be around 5 minutes.

**Comment by pauloancheta** [comment]
I'll go for 15 min. The last talk I did, I ran out of time 😅

**Comment by tracymu** [comment]
Hey Paulo, ok, can I put you down for October?

**Comment by paulfioravanti** [comment]
Hey @pauloancheta, thanks for volunteering to do a talk!  If you need anyone to do a dry run with (either on Skype or in person), please let me know and I'll be happy to!

**Comment by RocketRobC** [comment]
Hi @pauloancheta. We're going to start videoing the presentations and posting them on our youtube channel. Is it OK that we film your presentation?

**Comment by pauloancheta** [comment]
hey @RocketRobC 👋. Yeah, that should be fine.

**Comment by tracymu** [comment]
Thanks again for the talk @pauloancheta 

Really appreciate you volunteering when you've just moved here!

Looking forward to seeing you at the next meetup

**Comment by pauloancheta** [comment]
@tracymu no worries! I had so much fun giving a talk. 😄
