### ISSUE TITLE
Ruby Newbie

### ISSUE THREAD

**Issue by biancapower** [rails-oceania/roro#135]
Hello,

I'm currently learning Ruby as a student at Coder Academy, and I attended the September RoRo meetup after a talk from Paul Fioravanti at Coder Academy.

I'd love to give a talk on my experience learning Ruby as my first programming language, including some of the challenges faced as well as some resources and ways of thinking that I found useful. I also have a background as an educator so would talk a bit from the perspective of someone who knows a lot about learning.

The intended audience would be all levels as I think beginners could relate to the challenges and benefit from the tips I suggest, while the intermediate and advance audience - who are often in a position to help newbies - might also benefit from hearing a beginner's perspective.

I would be ready for the October meetup, and would like to do a 15 min talk but happy to do a 5 min version if preferred.

**Comment by tracymu** [comment]
Hello Bianca! Thank you so much for volunteering!

We would love for you to do a 15 minute talk at the October meetup if you're able :)

**Comment by biancapower** [comment]
Brilliant, thanks @tracymu! Looking forward to it :)

**Comment by paulfioravanti** [comment]
@biancapower thanks so much for volunteering to do a talk!  Really sad that I'll be missing it unfortunately due to being in Melbourne during the next RORO, but if you want someone to do a dry run with (either on Skype or in person), please reach out and I'd be happy to!

**Comment by biancapower** [comment]
Thanks @paulfioravanti, I'd really appreciate that! I'll get in touch when I've got something together - what's the best way to contact you?

**Comment by paulfioravanti** [comment]
@biancapower Shoot me an email at paul.fioravanti@gmail.com at any time during the process of creating your presentation (or afterwards) and I'll be happy to help.  Preferably, though before October 5 :)

**Comment by tracymu** [comment]
@biancapower  do you have a twitter handle you'd like me to include in our event?

**Comment by biancapower** [comment]
Yes please, @20by31 :)

**Comment by RocketRobC** [comment]
Hi @biancapower, looking forward to your talk on Tuesday, I'm also a latecomer to this career but it's been the best change I've made. 

A couple of questions. We're going to start videoing the presentations to be added to the RoRoSyd youtube channel, are you OK with us filming and posting your talk?

Second, I was checking out your site and saw that you speed cube. That has always amazed me, would you mind solving a cube as part of your intro?

**Comment by biancapower** [comment]
Hey @RocketRobC, no problem re filming and posting my talk. And sure, I'd be happy to do a speedsolve as part of my intro.

Look forward to meeting you on Tuesday :)

**Comment by tracymu** [comment]
Thank you so much for your talk @biancapower ! It was great and I loved the speed cube...
