### ISSUE TITLE
Trying other perspectives as a developer && as a human

### ISSUE THREAD

**Issue by knockycode** [rails-oceania/roro#137]
I'd like to give a 15 minute talk about trying other perspectives as a developer and as a human. 

Intended audience is for everyone. Technicalities in Rails isn't mentioned much, or at all. I'll be talking about my life experience with various development technologies, including Rails, and another discipline (martial arts) that both helped my understanding in both disciplines.

It may help the Rubyist audience give that extra nudge to try a different language which can further improve their Ruby development and way of life, or assure them that they don't need to try too many if they're already overloaded.

Talk will be ready by November.

Thanks @paulfioravanti for asking me to clarify my talk! It could be easily misconstrued before.

**Comment by tracymu** [comment]
Hey @knockycode  - I've officially added you to the November lineup. Please let us know if any problems :)

**Comment by paulfioravanti** [comment]
@knockycode thanks for the great talk yesterday, and also for posting your slide deck in the meetup comments! If you plan on posting the deck on Twitter, feel free to tag `@rorosyd` and `#rorosyd` :)
