### ISSUE TITLE
How to be a resilient developer

### ISSUE THREAD

**Issue by lucabusin** [rails-oceania/roro#139]
I propose a talk about personal resilience and being a developer. The talk would give an overview of what it means to be resilient and how to be resilient, especially from the point of view of a developer and the specific challenges we face.

It's not a tech talk so it's for everyone.

This would be a 15 minutes talk.

**Comment by tracymu** [comment]
@lucabusin  - okey dokey you are confirmed for November :)

**Comment by lucabusin** [comment]
Shall I go with the 5 minutes version?

**Comment by RocketRobC** [comment]
Yes, the 5 min version. Thanks.

**Comment by paulfioravanti** [comment]
@lucabusin nice work yesterday, Luca! Assuming you plan to share your slide deck, when you have a few minutes, please export your slide deck to PDF and put them on your slide-sharing service of choice (Speakerdeck, Slideshare, Slides etc...), and link to them in the meetup comments (https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/242665185/). If you plan on sharing them on Twitter, please tag `@rorosyd` and/or `#rorosyd`.
