### ISSUE TITLE
Rails and Feature Flags

### ISSUE THREAD

**Issue by lengarvey** [rails-oceania/roro#14]
Happy to do a presentation based on my blog posts at: https://reinteractive.net/posts/220-better-development-with-feature-flags and https://reinteractive.net/posts/221-feature-flags-on-rails

Would prefer a 15 minute session, will make it a good introduction to the topic with some discussion more suited towards intermediate and advanced developers.

**Comment by holodigm** [comment]
Great talk @lengarvey Shipped.
