### ISSUE TITLE
Creating an Alexa app with Rails

### ISSUE THREAD

**Issue by tarun-pacifica** [rails-oceania/roro#140]
Exact title still TBC.
Step by step on how I created an Alexa app using Rails.
Presentation will include a live demo of the Alexa App using an Amazon Echo.
We'd love to have you speak, or suggest a talk for Sydney Ruby. In addition to your talk topic, please mention the following:

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?
Proposal
- Intended audience (beginners, intermediates, advanced)
Intermediate Rails devs and Beginners using AWS

For proposals:
- Which month would you be ready for?
November
- Is this a 5m (lightning) talk, or a 15m talk?
15min talk

**Comment by tracymu** [comment]
Hello @tarun-pacifica  

I've just officially added you to the November lineup - please let us know if there is any problem with that :)

**Comment by paulfioravanti** [comment]
@tarun-pacifica awesome talk yesterday, mate :) 

Assuming you plan to share your slide deck, when you have a few minutes, please export your slide deck to PDF and put them on your slide-sharing service of choice (Speakerdeck, Slideshare, Slides etc...), and link to them in the meetup comments (https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/242665185/). If you plan on sharing them on Twitter, please tag `@rorosyd` and/or `#rorosyd`.
