### ISSUE TITLE
How I used scraped PokemonGo data to detect "nests"

### ISSUE THREAD

**Issue by matenia** [rails-oceania/roro#142]
I've prepared this talk and would like to present on the 12th December.

The talk is primarily about the capabilities of geokit-rails related to my use case of detecting potential "nest" locations in PokemonGo.

Please let me know if you need further info.

Intended Audience: Intermediates
Month: December
Duration: ~15 mins.

**Comment by tracymu** [comment]
Thank you so much @matenia !

looking forward to it.

**Comment by paulfioravanti** [comment]
Thanks @matenia, now get all your talk materials up on all the social medias and all will be sparkles ✨
