### ISSUE TITLE
Don't be so hard on yourself, Dummy!

### ISSUE THREAD

**Issue by tracymu** [rails-oceania/roro#144]
If you get told "Don't be so hard on yourself" - maybe you think "Why not?"

I used to. I used to think that being hard on myself was important to help myself improve and not repeat mistakes. 

But, now I'm in my 30s, and people still say it to me, and I still don't feel better. So, I did a lot of thinking and reading about *why* you shouldn't be so hard on yourself.

And that's what this talk is about.

This is a lightning talk for developers, and people(!), of any level. Even if you don't feel like you're hard on yourself, this is a good thing to think about, because I'm sure you have colleagues, friends or family who do this too.

I am able to do this in February.

**Comment by RocketRobC** [comment]
Sounds awesome. I'm very keen to hear your insights.

*Rob Cornish*
----------------------------------------
+61 415 183 555
@: rob@robcornish.net
Twitter: robcornish <http://www.twitter.com/robcornish>
=======================

**Comment by paulfioravanti** [comment]
Cleared milestone on this talk for now, so let's see how we go for March onwards :)

**Comment by paulfioravanti** [comment]
This talk on hold for now. Re-visit potentially for May.

**Comment by paulfioravanti** [comment]
@tracymu Do you still want to keep this talk on ice, or aim for the May meetup?

**Comment by tracymu** [comment]
Yes, I will do it in May! 
If it fits in with the lineup :)

**Comment by paulfioravanti** [comment]
@tracymu just a check-in since the meetup is next week, but are you still good with doing this lightning talk?

**Comment by paulfioravanti** [comment]
Hey @tracymu, I just had a look through the issue list, and I couldn't find your name having submitted a talk before. Is this going to be your first time doing a talk? I have a feeling that's not the case, but just want to confirm.

**Comment by tracymu** [comment]
I've done one before - a lightning one, about naming. Don't know why it isn't there :)

**Comment by paulfioravanti** [comment]
Thanks for last night, @tracymu ! Nice to finally get this talk out the door and into everyone's heads! 😄 

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/nnvkcpyxhblb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
