### ISSUE TITLE
Hard questions from beginners - Donna Zhou

### ISSUE THREAD

**Issue by RocketRobC** [rails-oceania/roro#145]
Feb 13th.
Lightning Talk, maybe more. 
Donna Zhou

I would like to give a lightning talk about the hardest questions I've been asked while coaching beginners to code. These questions were technically 'easy' but incredibly difficult to explain to someone coding for the very first time! My favourite question was 'What is the difference between print and return?'.

Before a Rails Girls event in Berlin, the coaches shared responses to these tough questions, and there were some really inspired ones (which I've since borrowed). I thought the RORO audience would also like to have a go at these 'hard' questions. I hope it would be a fun way to finish the presentation part of the evening.

**Comment by paulfioravanti** [comment]
@dondonz Hi there!  This is the issue opened on your behalf for your RORO talk.  If you have anything you'd like to add or change, please let us know here :)

**Comment by dondonz** [comment]
@paulfioravanti @RocketRobC Hello, thanks for posting this! I'm happy to leave the description as Rob posted it.

**Comment by paulfioravanti** [comment]
Thanks for presenting, @dondonz! Hope to see you at the next one! 

If possible, would you be able to make your slides available publicly by exporting it to PDF, putting it on your slide-sharing service of choice (Speakerdeck, Slideshare, Slides etc...), and linking to it in the meetup comments (https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/nnvkcpyxdbrb/). If you plan on sharing them on Twitter, please tag `@rorosyd` so we can give you a retweet.

**Comment by dondonz** [comment]
@paulfioravanti Thanks for having me!

I've popped a comment on the meetup with this link: https://speakerdeck.com/dondonz/what-is-a-variable-hard-questions-from-beginners

See you next time!
