### ISSUE TITLE
Understanding complex linux commands.

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#147]
Topic: understanding complex linux commands. We'd go through concepts like pipes, STDIN, STDOUT, STDERR, xargs, etc - then use them to break down and understand a big, long command.

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)? Proposal

- Intended audience (beginners, intermediates, advanced) Intermediates.

For proposals:
- Which month would you be ready for? March
- Is this a 5m (lightning) talk, or a 15m talk? 15m (actually, 23min)

**Comment by paulfioravanti** [comment]
@joshuapaling still good to go for March with this talk?

**Comment by joshuapaling** [comment]
Yep, I'm still good.

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @joshuapaling! When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/244339661/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
