### ISSUE TITLE
Learning From Other Languages - Immutability

### ISSUE THREAD

**Issue by JonRowe** [rails-oceania/roro#148]
Topic: Experimenting with other languages is a way of learning different ideas and concepts, one such concept that Elixir adds when coming from Ruby is immutability. What is it, why is it a good idea and can we do it with ruby.

> Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?

Proposal

> Intended audience (beginners, intermediates, advanced)

Intermediates, advanced.

For proposals:
> Which month would you be ready for?

March

> Is this a 5m (lightning) talk, or a 15m talk?

15minute

**Comment by paulfioravanti** [comment]
Thanks, @JonRowe ! Let's lock you in for March.

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @JonRowe! When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/244339661/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
