### ISSUE TITLE
Exercism talk for March Meetup

### ISSUE THREAD

**Issue by ezramizrahi** [rails-oceania/roro#149]
We'd love to have you speak, or suggest a talk for Sydney Ruby. In addition to your talk topic, please mention the following:

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)? 
This is a proposal to give a talk about one or two of my completed exercisms.
- Intended audience (beginners, intermediates, advanced)
Beginners, intermediates, advanced

For proposals:
- Which month would you be ready for?
March
- Is this a 5m (lightning) talk, or a 15m talk?
lightning talk about exercism code

**Comment by paulfioravanti** [comment]
Awesome @ezramizrahi! :tada: Looking forward to seeing your solution to the [Beer Song](http://exercism.io/exercises/ruby/beer-song/readme), and thanks very much for stepping up! If you need any assistance with anything regarding your presentation/solution, don't hesitate to reach out!

**Comment by paulfioravanti** [comment]
Well done tonight, @ezramizrahi ! You did awesome! If you ever want to do another talk, let us know!
