### ISSUE TITLE
Words of Advice for Young People

### ISSUE THREAD

**Issue by suranyami** [rails-oceania/roro#15]
As an old fart in the Rails world, we often try to one-up each other with mind-bendingly complicated presentations about how amazing our 733t coding skillz are.

I want to do the opposite of that.

I'd like to show some simple, elegant solutions to problems encountered by newcomers to the Ruby world, informed by battle-tested deployments in the real world.

I'll collect some scenarios from junior devs I work with, but would really appreciate some feedback on this before the next ROROSyd.

So, if you're a junior, or work with some, send me your most vexing questions, problems, and things that drive you nuts. I promise I'll get you sorted, or triple your money back.

**Comment by holodigm** [comment]
Great talk @suranyami with a lot of info. Looking forward to the next ;)  Shipped.
