### ISSUE TITLE
Memory Hack a TODO

### ISSUE THREAD

**Issue by knockycode** [rails-oceania/roro#150]
This is a request to speak about memory hacking a TODO without having to write it down or save a reminder about it in order to tick it off. The 'memory hack a TODO' example relates to coding.

The intended audience is for everyone.

It'll be ready for March and is a lightning/5min talk.

**Comment by RocketRobC** [comment]
Hi @knockycode. This sounds like a really great topic. I'll add you to the list for next week. 

Thanks!

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @knockycode ! When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/244339661/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

**Comment by knockycode** [comment]
Thanks, @paulfioravanti. Is it alright I'll put a link to a dev.to article, which will go into a bit more detail on the topic of tonight's talk, instead? Some of my slides will be appearing in the article and I'm planning to have the article published this weekend.

**Comment by paulfioravanti** [comment]
For sure, @knockycode ! Anything that will enable your audience to follow up on what you talked about is perfect.
