### ISSUE TITLE
Wallaby - yet another Rails admin interface

### ISSUE THREAD

**Issue by tian-im** [rails-oceania/roro#151]
Topic: Introducing wallaby gem - yet another Rails admin interface.

> - Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)? 

Proposal

> - Intended audience (beginners, intermediates, advanced)

All levels

> For proposals:
> - Which month would you be ready for?

March

> - Is this a 5m (lightning) talk, or a 15m talk?

15m

**Comment by paulfioravanti** [comment]
Hey @tian-im, thanks for submitting a talk!  We're full up with speakers for the March meetup next week, but would you be interested to do the talk at the April meetup?

**Comment by tian-im** [comment]
@paulfioravanti sounds good to me :)

**Comment by paulfioravanti** [comment]
Hey @tian-im do you have a Twitter account? If so, what is it?

**Comment by tian-im** [comment]
yep, i do, it's `@tian_im`

**Comment by paulfioravanti** [comment]
So it is.  I even follow you.  I have no idea why I couldn't find it.

**Comment by tian-im** [comment]
i guess it's because i'm too lazy twitting XD

**Comment by paulfioravanti** [comment]
Hey @tian-im, thanks for speaking last night! When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/244339662/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
