### ISSUE TITLE
File Uploading with ActiveStorage in Rails 5.2

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#152]
File uploading has been traditionally done in Rails using gems like Carrierwave or Paperclip, but Rails 5.2 provides its own out-of-the-box solution: [ActiveStorage](https://github.com/rails/rails/tree/master/activestorage). This is a talk *request* for an introduction to ActiveStorage.

**Comment by hhemanth** [comment]
Hi Paul, I would be interested to give this talk in December. I will submit an outline in a few days.

**Comment by hhemanth** [comment]
@paulfioravanti 
Below is the talk submission, please let me know any feedback, I will incorporate any suggestions you may have. 

### File Uploading with ActiveStorage in Rails 5.2 

### Agenda 
- Introduction to Active Storage, as an alternative to paperclip, inbuilt into rails 5.2
- How to build a simple rails app to upload image. 
- Uploading with S3 (External Service).
- How to test ?
- Demo (Building a simple Image Upload app).
- Performance & Security Considerations
- Any tips and tricks

### Summary
- Intended audience -, Beginner & Intermediate
- Month: Dec 2018
- Length of talk: full-length talk
- Your Twitter username: hhemanth
- avatar: https://www.hhemanth.com/images/avatar.jpg

### About me
- Hemanth Haridas
- Senior Engineer @ Maestrano
- Ruby on Rails Dev for 5+ years

**Comment by paulfioravanti** [comment]
@hhemanth that outline sounds great, and I'm looking forward to it! You're locked in for December!

**Comment by paulfioravanti** [comment]
Thanks for the great talk tonight, @hhemanth!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
