### ISSUE TITLE
Proposal: Smaller is always better

### ISSUE THREAD

**Issue by philnash** [rails-oceania/roro#159]
I gave this talk at [RoRo Melbourne](https://github.com/rails-oceania/melbourne-ruby/issues/92) and it seemed to go well. Wondered if you'd fancy it if I gave it in Sydney too?

For proposals:
- Which month would you be ready for? Don't think I'm around for the April event, but could do May
- Is this a 5m (lightning) talk, or a 15m talk? It was around 20 minutes, but I could cut it back a little?

Here's the abstract:

---

Gzipping content has long been a best practice when serving text based files over the web. Turn on gzip compression in your web server, your users download smaller files quicker and everyone is happy, right?

That's what I thought as I went to tune my personal site over the holiday and I ended up writing 3 new gems and learning a whole bunch about the compression options available to us today. So join me on a journey to smaller and smaller files, discover how to tune your applications and find out how I ended up fighting a CDN over 1kB.

**Comment by paulfioravanti** [comment]
@philnash Thanks for the submission! We'd be happy for you to get more milage out of your talk in Sydney!  I'll put you in aiming for the May meetup, and we can update this issue closer to the date.  If possible, cutting it back to as close to 15 minutes as possible would be fantastic 😁

**Comment by philnash** [comment]
Fantastic, thanks. I'll see what I can cut 😄 

The May meetup is the 8th, right?

**Comment by paulfioravanti** [comment]
Yep, the meetup will be on May 8th 👍

**Comment by paulfioravanti** [comment]
@philnash just a check-in since the meetup is next week, but are you still good with doing this talk?

**Comment by philnash** [comment]
Yup, I'm still good! 👍

**Comment by paulfioravanti** [comment]
Hey @philnash, just wanted to confirm: have you done a talk at RORO Sydney before, or will this be your first time?

**Comment by philnash** [comment]
@paulfioravanti this is my first time at RORO Sydney :)

**Comment by paulfioravanti** [comment]
Thanks so much for the talk last night, @philnash! You're most welcome back to ROROSyd if you're in the area again, either for another talk, or just to attend!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/nnvkcpyxhblb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

**Comment by philnash** [comment]
Cheers @paulfioravanti, done and done. Thanks again for having me! 🙂
