### ISSUE TITLE
Proposal: Integrating elm into a rails app

### ISSUE THREAD

**Issue by nicholashibberd** [rails-oceania/roro#160]
Hi, we have been using Elm for our frontend apps at Spabreaks.com (rails site) for the past year and I'd like to do a talk on it.

I'll cover:

- A basic introduction to the Elm programming language
- A summary of the Elm architecture and how it compares to the approaches of other JS frameworks such as React
- Example of how to integrate Elm into an existing rails app
- Other stuff

It'll be a 15 min talk and I'll try and keep it as light as possible but it will probably have to assume some knowledge of JavaScript and JS frameworks

May at the earliest :)

**Comment by paulfioravanti** [comment]
@nicholashibberd Personally, I am _very_ interested in this since I'm tinkering a lot with Elm 😀 I'll tentatively set this talk for the May meetup!

**Comment by paulfioravanti** [comment]
@nicholashibberd Still okay to do this talk in May or do you want to push it out?

**Comment by nicholashibberd** [comment]
If you have a few lined up for May, then I could probably use the extra time, but if not I can get it done

**Comment by paulfioravanti** [comment]
No worries.  In that case, extra time granted! I'll re-schedule you for June.

**Comment by RocketRobC** [comment]
Hi @nicholashibberd. Still good to do this next meetup?

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @nicholashibberd!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:
	•	Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxjbqb/
	•	Tweet the slides link out to @rorosyd, and we'll give it a retweet.

**Comment by paulfioravanti** [comment]
Also, @nicholashibberd do you have a Twitter account...?

**Comment by nicholashibberd** [comment]
No probs, enjoyed it! Yeah sure I'll share the slides now

My twitter is @nickhibberd, but I don't tweet often

**Comment by nicholashibberd** [comment]
I don't seem to have access to the Meetup event anymore, perhaps I forgot to sign up. Here at the slides if someone else can post them for me goo.gl/ASY2oM

**Comment by paulfioravanti** [comment]
Strange that you can't access the meetup page... Anyway, I posted a link to the slides in the comments section: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/249732801
