### ISSUE TITLE
Exercism talk for April Meetup

### ISSUE THREAD

**Issue by dondonz** [rails-oceania/roro#161]
I'd love to present my exercism solution at the April meetup!

**Comment by paulfioravanti** [comment]
Yay! Thanks @dondonz! You're locked in for April!

**Comment by paulfioravanti** [comment]
@dondonz did you shut down your Twitter account? https://twitter.com/dancingTeeth doesn't seem to exist anymore...

**Comment by dondonz** [comment]
Hello! Ah well spotted! I changed the name of the account to https://twitter.com/failscasts 😄

**Comment by paulfioravanti** [comment]
Thanks! LOL at the handle 😆

**Comment by paulfioravanti** [comment]
Thanks for sharing your Exercism solution last night @dondonz ! I know you had a few slides (or was it just one?), but regardless if you want to share the deck, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/244339662/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
