### ISSUE TITLE
Proposal: Remote Work - lessons learned.

### ISSUE THREAD

**Issue by brushbox** [rails-oceania/roro#162]
# Remote Work : lessons learned.

I've been working remotely for over 13 years. I've experienced the highs and lows. I've survived and seen (some) others crash and burn. It's not for everyone and not every company will do it well. 

At Rubyconf AU I found that many people were interested in hearing more about working remotely. So I think I could share something of my experiences with a goal for the listeners to consider:

* whether remote work is something that they would consider trying
* whether _they_ are suited to remote work.
* whether their company is suited to remote work.
  * what their company might need to do in order to support remote work.
* tools that make things work better.
* things to be vigilant about when working remotely.

There's too much to cover in 5min, so this will need to be a full length (15min) talk. I suspect it will still be an overview at that.

I am planning to have this ready for April's meetup.

Pete.

**Comment by paulfioravanti** [comment]
Thanks Pete! Look forward to hearing how your experience differs from mine with regards to this. We'll lock you in for April!

**Comment by paulfioravanti** [comment]
Hey @brushbox, thanks for speaking last night! Great catalyst for all that group discussion! When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/244339662/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
