### ISSUE TITLE
When Sorry seems to the hardest Word

### ISSUE THREAD

**Issue by catherine-jones** [rails-oceania/roro#163]
What happens when you make a mistake? You say something ill-informed or insensitive in the heat of the moment without thinking it through. What do you do next? Do you just try to ignore it or do you get defensive? In this lightning talk, I will talk about advocacy and making mistakes and what comes next.

This is a proposal I am submitting
This talk is intended for everyone

For proposals:
My Talk will be ready to present in April
It is a 5-minute lightning talk

**Comment by paulfioravanti** [comment]
Thanks @catherine-jones! Submitted just in the nick of time! Confirmed for April!

**Comment by paulfioravanti** [comment]
@catherine-jones How do you feel about re-aiming for the June meetup for this?

**Comment by knockycode** [comment]
I saw it was marked for April and I missed April due to be double-booked and felt really sad. But if it's re-aimed for June, I'm definitely making that meetup! This talk sounds great!

**Comment by paulfioravanti** [comment]
@catherine-jones Still good for the June meetup?

**Comment by catherine-jones** [comment]
yep all good to go thanks @paulfioravanti

**Comment by paulfioravanti** [comment]
Nice work tonight, @catherine-jones! Definitely see if you can shop the presentation around to some other meetups!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:
	•	Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxjbqb/
	•	Tweet the slides link out to @rorosyd, and we'll give it a retweet.
