### ISSUE TITLE
Production-ready web service checklist

### ISSUE THREAD

**Issue by sarneaud** [rails-oceania/roro#164]
Hi, I can give a 15min talk (practically any month) about making sure a web service is ready for the scary world of production.  Hopefully everyone from beginners to experienced developers would be able to learn something from it.

**Comment by paulfioravanti** [comment]
Hey Simon! Thanks for the submission! Would you be up for doing this at the June meetup?

**Comment by sarneaud** [comment]
Sure.

**Comment by sarneaud** [comment]
Sorry, do you mind pushing it back to a later meetup?  I'm not sure if I can be at the June event any more.

**Comment by paulfioravanti** [comment]
Sure! I'll push it back to July.

**Comment by paulfioravanti** [comment]
Hey @sarneaud, just curious about how much of the content of this talk, if any, is around Docker? Asking since we have another talk proposal about it; this isn't a request for you to change anything about what you're planning to talk about :)

**Comment by sarneaud** [comment]
No, it's okay.  I might mention some tools, but my talk won't be tool-specific.  I definitely won't go into depth about Docker.

**Comment by paulfioravanti** [comment]
@sarneaud do you have a twitter handle?

**Comment by sarneaud** [comment]
No, I don't.

**Comment by paulfioravanti** [comment]
Okay, no worries! Thanks.

**Comment by paulfioravanti** [comment]
Thanks for the great talk tonight, @sarneaud!  When you have a moment, can you post a link to your slides to the Meetup page? https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/249433971/

If you decide to join Twitter again, feel free to tweet the deck at `@rorosyd` and we'll re-tweet it there ;)
