### ISSUE TITLE
Learn to Teach a Junior Developer

### ISSUE THREAD

**Issue by knockycode** [rails-oceania/roro#165]
A proposal for me to give a lightning talk on learning to teach a junior developer. It's intended for all levels.

It can be ready for May.

**Comment by knockycode** [comment]
Sure I can either be a backup lightning talk for May and June and if they're both covered, can speak in July instead. 😄

**Comment by paulfioravanti** [comment]
Okay, great!  Let's mark you in initially for July, and move you forward if we get any lightning talk rescheduling/cancellations 😄

**Comment by catherine-jones** [comment]
👍

**Comment by paulfioravanti** [comment]
Thanks again for yet another great talk, @knockycode! As you're no doubt used to by now, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/249433971/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
