### ISSUE TITLE
My Ruby Story - from political cartooning and animation to ruby developer

### ISSUE THREAD

**Issue by leesheppard** [rails-oceania/roro#166]
Intended for a 15 minute presentation. My career and background in cartoons and transitioning to developer. Of interest to a wide audience, I will cover issues around why and how I ended up where I am today.

**Comment by paulfioravanti** [comment]
@leesheppard just a check-in since the meetup is next week, but are you still good with doing this talk?

**Comment by leesheppard** [comment]
all systems are go :100:

**Comment by paulfioravanti** [comment]
@leesheppard Just want to confirm: is this your first talk at RORO?

**Comment by leesheppard** [comment]
@paulfioravanti Yes it will be

**Comment by paulfioravanti** [comment]
Thanks for the talk last night, @leesheppard!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/nnvkcpyxhblb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
