### ISSUE TITLE
Exercism - Roman Numerals 

### ISSUE THREAD

**Issue by mathewdbutton** [rails-oceania/roro#167]
I'd like to give this a shot, if it's still open. I've not had as much time to work on it as I'd like as it's not currently finished..... I'm hoping to have it done by the time the meetup rolls around (yes I left this to the last minute).

**Comment by paulfioravanti** [comment]
@mathewdbutton Champion!  You're locked in for Tuesday!

**Comment by paulfioravanti** [comment]
@mathewdbutton do you have a Twitter account? If so, what is it, so we can put it in the meetup details.

**Comment by mathewdbutton** [comment]
I do not have a twitter account, I've just never managed to get into it.

**Comment by paulfioravanti** [comment]
@mathewdbutton Just confirming another thing: this is your first talk at RORO, right?

**Comment by paulfioravanti** [comment]
Nice work last night, @mathewdbutton! Thanks for being able to get a solution done so quickly!
