### ISSUE TITLE
Blocks, Procs and Lambdas

### ISSUE THREAD

**Issue by damncabbage** [rails-oceania/roro#169]
_15min talk, for beginners with some tidbits for intermediates._

This talk digs into what Blocks, Procs and Lambdas are, how they're used, how they respectively cause trouble, and some tricks that can be done with them.

**Comment by paulfioravanti** [comment]
Thanks for being able to do a talk so last minute, @damncabbage ! Much appreciated!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:
	•	Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxjbqb/
	•	Tweet the slides link out to @rorosyd, and we'll give it a retweet.

**Comment by damncabbage** [comment]
Done; thanks. :)

(The link is http://robhoward.id.au/talks/2018/06/blocks-procs-and-lambdas/ for later reference.)
