### ISSUE TITLE
How to learn VIM?

### ISSUE THREAD

**Issue by catherine-jones** [rails-oceania/roro#17]
Where do you start with VIM? What are the best ways to maintain productivity whilst learning? What are the best resources?

**Comment by snoblenet** [comment]
Also 'why VIM'? (Written as a TextMate user who constantly wants to go faster.)
And, 'is it really worth it?' (Given the amount of upfront learning required.)

**Comment by subshad** [comment]
Is there still interest in this talk? I'd be happy to do it.

**Comment by joshuapaling** [comment]
Hi subshad, I'm sure there'll be people interested if you'd like to do it. Let us know which meetup (month) you'd like to present.
