### ISSUE TITLE
Upgrading to Rails 5

### ISSUE THREAD

**Issue by dondonz** [rails-oceania/roro#171]
I would like to give a 15m talk about upgrading to Rails 5.

I would like to speak about the experience of upgrading from Rails 4 to Rails 5. I will discuss the challenges and how we overcame them. I will provide actionable tips to save time, and hopefully make the process a bit more pleasant for the next person.

This talk would be appropriate for all audiences.

I would be happy to present this for the August or September meetup.

**Comment by paulfioravanti** [comment]
@dondonz Sounds like a great talk idea! We've currently got no speakers for August, so if you want a spot then, it's yours! How about aim for August, then we'll check in after the July meetup and see how you're tracking, and if needed, push out to September?

**Comment by paulfioravanti** [comment]
@dondonz assuming that it's still okay to change this from a full-length to lightning talk :)

**Comment by dondonz** [comment]
@paulfioravanti Yes, as discussed, happy to make this a lightning talk. Thanks!

**Comment by paulfioravanti** [comment]
Hey Donna, I heard your talk was awesome as per usual :D Thanks for sharing the slides on Twitter. It's probably too late, but if you also wanted to share them on the meetup page, the link is: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxmbpb/
