### ISSUE TITLE
Pivoting your career

### ISSUE THREAD

**Issue by G-face** [rails-oceania/roro#172]
This is a talk I gave at the Girl Geeks meetup in June 2018.

Pivot is a framework former Googler Jenny Blake developed to help people use the skills they have built through experience to seek new challenges and change their careers. After spending 7 years working behind the scenes in the recruitment industry, it was time for a pivot of my own! In this talk I'll give an overview of the Pivot framework and how it can help you decide when, how and where to pivot, as well as sharing a little of my personal experience along the way.

- Intended audience - all levels

I'm ready whenever you are - July, or August

15 minute talk

**Comment by paulfioravanti** [comment]
Hey @G-face, thanks for this! We've got a full length spot available for July, so let's lock you in for that!

**Comment by paulfioravanti** [comment]
Thanks for the talk tonight, @G-face! I see you've posted your Slideshare to the meetup page already, but would you also be able to tweet the deck out to `@rorosyd` as well and we'll give it a re-tweet!
