### ISSUE TITLE
Developing with Docker

### ISSUE THREAD

**Issue by cyclotron3k** [rails-oceania/roro#174]
I've been using Docker recently so I can work with different versions of Ruby, across different operating systems.

I'm not an expert on Docker, but perhaps other people may be interested to learn a bit about docker, its benefits and its drawbacks.

**Proposal or request:** I don't mind, I could do it - someone else could do it.
**Lightening or 15m:** 5 minutes would be enough for a overview. 15 mins would be good for some worked examples
**Intended audience:** all

**Comment by paulfioravanti** [comment]
Similar to #173 and #175, please let us know which of your talk proposals you would like to initially proceed with, in what format, and what meetup month you would like to target.

**Comment by paulfioravanti** [comment]
@cyclotron3k, do you still want to do a presentation at all on this at a future meetup?

**Comment by cyclotron3k** [comment]
Hmm. On second thoughts, I don't think 5 minutes would be enough time to convey anything useful about docker, and I don't think I feel qualified to talk about docker for a longer period of time

**Comment by paulfioravanti** [comment]
So, should we convert this into a presentation request, or do you plan to get into Docker enough to be able to work yourself up to a 15 minute presentation? It's okay to just close this issue as well if you've moved on to other things :)

**Comment by paulfioravanti** [comment]
As per separate conversation, we'll close this issue. If anyone wants to do their own Docker presentation, they can open up a new one.
