### ISSUE TITLE
Fun with Enumerator

### ISSUE THREAD

**Issue by cyclotron3k** [rails-oceania/roro#175]
The Enumerable mixin must be one of the most used parts of Ruby, but the heavy lifting is mostly done by Enumerator class, which gets very little attention*.

Let's shed some light on this mysterious beast, and investigate what makes it so powerful, introducing the concept of infinite arrays in the process.

\* I have no idea if that's true, but it _feels_ right.

Disclaimer: I haven't done a technical talk before, so I don't know if this is an appropriate topic or even if it's worth talking about. Happy to discuss.

**Proposal or request:** I guess I'd have to do it
**Lightening or 15m:** 5 minutes should be plenty
**Intended audience:** all

**Comment by paulfioravanti** [comment]
Any Ruby topic is fair game for a presentation proposal, @cyclotron3k, so don't worry about that, and I'm sure your take on it will make it worth talking about :)

If you wanted to do this as a lightning talk, then there is currently a slot for any meetup from August onwards, so let us know which talk you'd like to do and we can lock something in.

**Comment by paulfioravanti** [comment]
Hey @cyclotron3k , thanks for the talk last night! When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxlbsb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
