### ISSUE TITLE
Exercism exercise

### ISSUE THREAD

**Issue by yilmazgunalp** [rails-oceania/roro#176]
Hi there
I am happy to present my solution to 'accumulate' problem from exercism.io 

Since it is a simple problem 5 min would be more than enough.

My solution is here: http://exercism.io/submissions/cd1e08597f9740c0a748ecd46cebf48c 

cheers
Yilmaz

**Comment by paulfioravanti** [comment]
Brilliant, thanks, @yilmazgunalp! I'll lock you in for the July meetup!

**Comment by yilmazgunalp** [comment]
thanks @paulfioravanti

**Comment by paulfioravanti** [comment]
@yilmazgunalp do you have a Twitter handle?

**Comment by yilmazgunalp** [comment]
@paulfioravanti  I don't have a twitter account  but feel free to use my meetup profile picture.or  I can send you one. thanks

**Comment by paulfioravanti** [comment]
Great work tonight, @yilmazgunalp! Doing live coding, and C-code reading for your first lightning talk with us is an impressive feat! If you end up putting your different implementations in, say, a Github Gist somewhere, tweet it out to `@rorosyd` and we'll give it a re-tweet.
