### ISSUE TITLE
Successfully Outsourcing an Offshore ROR Team

### ISSUE THREAD

**Issue by costakoulis** [rails-oceania/roro#179]
This is a 15 min talk.

There are many obstacles to outsourcing the coding of a ROR platform, to an offshore team. When not done correctly, the outcomes can be disastrous.

However, Designerex™ overcame all these offshoring obstacles and launched a very successful and rapidly-growing platform in Australia, using a ROR programming team in Nepal.

Designerex™ ( https://designerex.com.au ) is the world's first secure designer clothes sharing platform and it is built on ROR ( https://rails-apps.com/ruby-on-rails-ecommerce )

It is a purpose-built ROR platform, created from scratch, which has now grown to be Australia's largest designer dress hire destination, with over 8,500 listings ( https://designerex.com.au/search ).

Given the success of Designerex in Australia, it is soon expanding to the USA.

This talk covers important strategies employed by Designerex, to ensure successful offshore management from Sydney, using outsourced programming team in Nepal. These strategies include:

- Ensuring all product research, development and design done locally, prior to offshore coding.
- Learning to communicate effectively between Sydney and Kathmandu.
- Timing the launch marketing, in line with the product build.
- Creating innovative techniques, to solve the chicken/egg problem of a 2 sided sharing economy marketplace. 

- Intended audience (beginners, intermediate)

**Comment by paulfioravanti** [comment]
Thanks for making a new Github account just to submit this talk @costakoulis! :) We'll lock you in for the August meetup.

**Comment by paulfioravanti** [comment]
Hey @costakoulis, thanks so much for coming along to speak last night! If possible, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxlbsb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
