### ISSUE TITLE
Exercism exercise — anagram

### ISSUE THREAD

**Issue by filterfish** [rails-oceania/roro#180]
I will be showing how I solved the [anagram exercism](https://exercism.io/my/solutions/96051bfad743408e9d25c8b2e2da0000). Possibly in the most obtuse way I can ;)

**Comment by RocketRobC** [comment]
Nice! Looking forward to it.

*Rob Cornish*
----------------------------------------
+61 415 183 555
@: rob@robcornish.net
Twitter: robcornish <http://www.twitter.com/robcornish>
=======================

**Comment by paulfioravanti** [comment]
Thanks for the presentation last night, @filterfish!

Not sure if there are any shareable materials for your talk (maybe a gist of the code or Exercism page with the code...?), but if there are any:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxlbsb/
- Tweet the link out to `@rorosyd`, and we'll give it a retweet.
