### ISSUE TITLE
Breadth First Analysis - Presentation Proposal

### ISSUE THREAD

**Issue by johnofsydney** [rails-oceania/roro#181]
Hi Paul and Rob

in response to your shout out for a talk for the next meet up, I'd like to do a talk on Breadth First Analysis / Shortest path between two nodes.

I currently work at General Assembly as a Teacher's Assistant. It's my first job in tech. One of the first homeworks here is to create a function that will navigate you from a starting station to a destination on a very simple 3 line train network. While I was studying at GA I kept hacking away at a BFS solution that would work for a network with any number of interconnections. I demoed this solution to the following class, while I was working as a TA there. I'd love to present to RORO and this would be a good topic for me.

Here is a link to the repo, I'd need to make a presentation to go with it. I'll get a chance to practice on the current class of GA students.
https://github.com/johnofsydney/BFS

- Is this a proposal (you want to give this talk yourself)
** This is a proposal - I'll do the talk

- Intended audience (beginners, intermediates, advanced)
** beginners I guess. This was hard for me, but I am a beginner.

For proposals:
- Which month would you be ready for?
** I'm ready for the August meetup

- Is this a 5m (lightning) talk, or a 15m talk?
** closer to 15 than 5 I feel.

**Comment by paulfioravanti** [comment]
Hey @johnofsydney, sounds like a great talk idea, and we'd love to have you as the second full length talk for August! We'll lock you in for two weeks time!

**Comment by paulfioravanti** [comment]
Hey @johnofsydney, awesome job on the talk last night! Let us know if you ever have any other ones you want to present!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxlbsb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

**Comment by johnofsydney** [comment]
Thanks Paul. I really enjoyed the experience. Slides are uploaded in the comments and tweet has been tweeted.

BR
John
