### ISSUE TITLE
Combining the Powers of SEM and BIO for Improving CSS 

### ISSUE THREAD

**Issue by iamryanyu** [rails-oceania/roro#183]
Hi Paul,

As discussed in SydCSS, I would like to submit the talk proposal for the 10 min (if not possible, 15 min) talk. 

The talk will be about how to write better CSS with SEM and BIO; especially around how to manage CSS specificity better.

The intended audience would be all levels of developers/engineers who write **CSS**.

As I am going overseas for few weeks in mid November, it would be great if I could give the talk in the early November or Jan next year :)

Thanks a lot Paul,

Warm regards,
Ryan

**Comment by paulfioravanti** [comment]
Hi @iamryanyu, thanks for submitting the talk! We're more than happy to accommodate your timeframe request! Since the November RORO meetup is on the 13th, I'm assuming that qualifies as mid-November, and since January is the month that RORO takes off, would you be interested in aiming all the way out for February 2019, if not September or October this year?

**Comment by iamryanyu** [comment]
Hi @paulfioravanti,

I am happy to do October if that's ok with you :)

**Comment by paulfioravanti** [comment]
@iamryanyu perfect! We'll add a milestone for that and confirm again later towards the date.

**Comment by paulfioravanti** [comment]
@iamryanyu Still good for the October meetup, I presume?

**Comment by iamryanyu** [comment]
Hi @paulfioravanti, yep! Just confirming the meetup is on 9th Oct?

**Comment by paulfioravanti** [comment]
Yep, sure is!

**Comment by paulfioravanti** [comment]
Hey @iamryanyu , thanks so much for speaking last night!

If you decide to make your slides public in some format (I vote that you do 😉 ), please tweet a link out to `@rorosyd`, and we'll give it a retweet 😃

**Comment by iamryanyu** [comment]
Thanks @paulfioravanti , yep definitely will do it!
