### ISSUE TITLE
ROROSyd leap year exercisim solution

### ISSUE THREAD

**Issue by zailleh** [rails-oceania/roro#184]
I would like to present a [Solution] to the Leap Year exercism problem in the next ROROSyd Meetup.

[Solution]:https://exercism.io/my/solutions/b40758ad37274f068809be14058b178c

**Comment by paulfioravanti** [comment]
Nice one, @zailleh ! We'll lock you in for the September meetup!

**Comment by paulfioravanti** [comment]
Hey Tim, thanks for your talk (even though I didn't get to see it)! When you have a few moments, if you had any slides, could you please do the following:

Export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxmbpb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
