### ISSUE TITLE
Managing concurrent workloads: forks, threads and events

### ISSUE THREAD

**Issue by cyclotron3k** [rails-oceania/roro#186]
This would be a talk about the different strategies for dealing with concurrent workloads.

I would probably begin by quickly covering a bit about CPUs (cores & hyperthreading), then talk about the difference between forking and multi-threading. Then I'd dive into the Ruby and discuss the ways of working with forks & threads, and I'd also want to cover single-threaded event-based strategies.

I don't mind if someone else wants to give the talk but I assume I'll do it.

It would be for intermediates, but I'd hope beginners and advanced could gain something from it. Especially if I don't talk so fast and take a bit more time explaining things!

I'd need at least a few weeks notice to prepare the talk, and I think it would probably have to be a 15m talk.

**Comment by paulfioravanti** [comment]
Thanks for the submission, @cyclotron3k. Would you like to perhaps aim at doing this talk at the November meetup, with a back-up plan for doing it in October? Since you've only recently given a talk, we try and keep spaces open as long as possible for people that either haven't given a talk before, or who haven't in the last 3 or so months, and that's why I'm suggesting November. What do you think?

**Comment by cyclotron3k** [comment]
That's no problem at all.

I just added the idea before I forgot it, and wasn't expecting to be doing it any time soon. Happy to do it whenever works best.

**Comment by paulfioravanti** [comment]
Okay, great! For now, I'll schedule you in for the November meetup, and if there ends up being a gap for October, I'll ping you again.

**Comment by paulfioravanti** [comment]
@cyclotron3k, are you still good to do this talk in November?

**Comment by cyclotron3k** [comment]
@paulfioravanti yep, no problem!

**Comment by paulfioravanti** [comment]
Hey Aidan, thanks for speaking last night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
