### ISSUE TITLE
Fail to Succeed - TDD with RSPEC

### ISSUE THREAD

**Issue by sonicakes** [rails-oceania/roro#187]
Proposal
15 minute talk
Beginners
September 11th

My name is Sonia, and I’d like to propose a talk on TDD in RoR with RSPEC, which I’d call ‘Fail to succeed’.

I graduated from General Assembly’s Web Development Immersive course this Friday, and I devoted a big part of my final project to Testing my Models and Controllers with RSPEC. You can view my presentation recorded on Facebook, I’m starting from 00:25 [WDi28 Final Presentations! 🖥 - General Assembly](https://www.facebook.com/GeneralAssemblySydney/videos/710556632633979/)

This is a talk aimed at Junior Developers and beginners, who would like to start with testing in Ruby.

Since it’s 15-minute talk, I’d like to explain how I got started with TDD, what I found most challenging, do a quick demo of tests failing/passing and viewing the test coverage, and why it’s important to fail to succeed (literally!).

This would be my first talk on a meetup,  and I thought it would be good to introduce something from “junior dev” track. The idea came to me after attending “DDD Sydney” conference a few weeks ago, where they had the whole section dedicated to Junior Developers.

Please let me know if you’d like this talk at 11th September RoRo meet up!

Thank you!

**Comment by paulfioravanti** [comment]
Thanks for the submission, @sonicakes! We'd love to get you to do this presentation at the September meetup, so consider your position locked in!

**Comment by paulfioravanti** [comment]
Hey Sonia, thanks so for your talk (even though I didn't get to see it, I heard it went great)! When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and:

- Put a link to them in the Meetup comments: https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/rxmjspyxmbpb/
- Tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
