### ISSUE TITLE
Mind mapping for clarity

### ISSUE THREAD

**Issue by erinbelot** [rails-oceania/roro#188]
Mind mapping has really helped me clarify and see different concepts. You can see area's that need improving on and fleshed out. Hopefully the talk would benefit other juniors too.

Proposal or request: Propsal
Lightening or 15m: 5 minutes lightning
Intended audience: juniors/all

<img width="592" alt="screen shot 2018-09-04 at 1 29 23 pm" src="https://user-images.githubusercontent.com/36493925/45009039-44501400-b049-11e8-9dcd-46914fc7f295.png">

**Comment by paulfioravanti** [comment]
Hi @erinbelot, thanks so much for your submission! Would doing your lightning talk at the November meetup (13th November) work for you?

**Comment by erinbelot** [comment]
Heya! Sorry, I meant to apply for the Melbourne meetup. Will close the issue.

**Comment by RocketRobC** [comment]
Hi Erin,

What a shame! Was keen on hearing your talk.

I hope it goes well in Melbourne.

*Rob Cornish*

**Comment by paulfioravanti** [comment]
No problem, Erin. If you're ever in Sydney when the meetup is on and you want to do it then, let us know, and good luck in Melbourne!
