### ISSUE TITLE
Fantastic passwords and where to find them

### ISSUE THREAD

**Issue by philnash** [rails-oceania/roro#190]
We'd love to have you speak, or suggest a talk for Sydney Ruby. In addition to your talk topic, please mention the following:

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?
*Proposal*

- Intended audience (beginners, intermediates, advanced)
*Everyone*

For proposals:
- Which month would you be ready for?
October
- Is this a 5m (lightning) talk, or a 15m talk?
15m

Description:

The humble password is broken. The internet is littered with poor security practices and password breaches, but the world is not ready to go password free yet. So what can we do to protect our users?

Let's take a look at how we currently protect passwords, at what we can throw away from those processes and what we can bring in to strengthen our users' passwords. Together we can move the world from "password1" to "correct horse battery staple" and beyond!

**Comment by paulfioravanti** [comment]
Thanks, @philnash, and a pleasure to have you back in town! Locked in!

**Comment by paulfioravanti** [comment]
Hey @philnash , thanks for coming out and speaking last night, and sorry I wasn't able to attend!

If your slide deck is for public consumption, please tweet the slides link out to `@rorosyd`, and we'll give it a retweet, and let us know when you'll be back in town again!
