### ISSUE TITLE
Exercism Exercise - Flatten Array

### ISSUE THREAD

**Issue by IvanRahn** [rails-oceania/roro#192]
Hi! 
I would like to present my [solution](https://exercism.io/tracks/ruby/exercises/flatten-array/solutions/27d290e1430943ea905505221f15d771) to November challenge - Flatten Array.

Intended audience: beginners
Meetup time: November
Length: lightning talk (5 minute)
Twitter: @ivan_rahn

**Comment by paulfioravanti** [comment]
Awesome, thanks, Ivan!  You are locked in for the November meetup!

**Comment by paulfioravanti** [comment]
Hey Ivan, well done with the talk and demo last night!

Assuming you have something to share (maybe your slide deck title page and screenshots of your code...?), please consider exporting them to PDF and putting them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and then tweeting the slides link out to `@rorosyd`, and we'll give it a retweet.

If you just want to do a Gist of the code, or give a link to where it is on your Github account, then we can retweet that out as well 👍
