### ISSUE TITLE
Introduction to Sonic Pi 🎶

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#193]
I would love to see a presentation about one of the coolest Ruby projects: [Sonic Pi](https://sonic-pi.net/)!

I am completely musically illiterate, so if there is anyone with a musical background
who would be able to give an overview of Sonic Pi, how it works, and maybe show off some of their [musical creations created with Sonic Pi](https://www.youtube.com/watch?v=cydH_JAgSfg) and/or do a [live coding performance](https://www.youtube.com/watch?v=KJPdbp1An2s), I think you'd bring down the house!

**Comment by RocketRobC** [comment]
I'll do it. Maybe not for December but in the new year.

**Comment by andypalmer** [comment]
Sam Aaron is in the area, maybe you could encourage him to drop over for a special RoRo event: https://www.linkedin.com/feed/update/urn:li:activity:6465010860678008832

**Comment by paulfioravanti** [comment]
I've already made contact, but unfortunately he'll be in India when the meetup is on, so if you want to see him do some live-coding in Sydney, your best bet is going to the YOW! Conference.

**Comment by andypalmer** [comment]
If he's up for it, you could run a _special edition_ meetup, but I guess he's probably got a hectic schedule

**Comment by paulfioravanti** [comment]
If anyone is reading this thread and they have connections to musical venues in Sydney, Sam has indicated he would be down to play at one if they can host him while he's in Sydney for the conference.

**Comment by andypalmer** [comment]
I reached out to Amanda Palmer, to find out where she uses for her ninja gigs, and her team suggested contacting the [The Oxford Art Factory](http://oxfordartfactory.com/)
I'd reach out, but I don't know what dates you've discussed with Sam

**Comment by paulfioravanti** [comment]
I reached out to Sam with that info, and if he gives a response that leads to something happening with regards to a Sonic Pi performance outside of the YOW conference (I still don't know what dates he'd be available before, during or after the conference), then we'll announce it through the ROROSyd Twitter account.

Oh, and if anyone else aside from Rob is thinking of doing their own Sonic Pi-related presentation for rorosyd, then by all means let us know. For something this cool, there can be more than one 😄

**Comment by rowena-s** [comment]
Just saw this linked on twitter. No joke, I considered doing a talk on it last year when I first learnt SonicPi but dismissed it because its Ruby only and not Rails. 
@RocketRobC did you have something in mind to present? Happy for you to DM me on the Ruby AU Slack :)

**Comment by paulfioravanti** [comment]
@rowena-s please continue to consider doing a talk on Sonic Pi! If you can get a talk ready for the September meetup, we'll definitely secure your spot!

**Comment by rowena-s** [comment]
This can be made to happen. No guarantees of any samaaron-style live music sets though 😄 
How long is the timeslot I have to present and would I be able to get someone to sanity check my talk plan? (most of it will be doing things in Sonic Pi anyway)

**Comment by paulfioravanti** [comment]
Full length talks are typically capped at 15 minutes, but if you're planning on rocking out with what you create with Sonic Pi, as well as providing a bit of an intro to Sonic Pi itself, we can be flexible!

Don't worry, we don't have any expectations of a full-blown live coding gig 😉 You'd be the first person to do a Sonic Pi presentation, though, so by default, that would make you our community expert!

Either @RocketRobC or myself would be very happy to sanity check your talk plan and/or do dry runs with you, and since it looks like Sam Aaron is following this thread, this may be presumptuous, but he might be willing to give you some feedback as well if you ask... 😄

**Comment by rowena-s** [comment]
Thanks Paul, 
This is my high-level plan for the talk that I would want to give, with no concept of timings.
If there are things that might be a too advanced for an intro talk, please flag them and I'll cut them out.

**Background:**  I was introduced to Sonic Pi via my volunteering work with Code Club Australia and have a long-term master plan to get Sonic Pi into more Australian schools. I also went through the AMEB music examination system so there is going to be a small amount of music theory in this talk :)

**Plan:**
- What is Sonic Pi: open sourced ruby based gui to super collider, TLDR what is super collider. 
- Go through main parts of the gui (docs, oscilloscope, settings) and emphasise the relevant menu more as I'm talking about the appropriate bit.

- Demo of basic functions: play_note, play chord, can use midi values or musical notation
- ADSR envelope (what is it and how does it affect sounds)
- playing samples and changing bpm
- using local files as sample (give it a direct path, might work with urls too?)
- play_scale, play_pattern_timed - use this as a basis for a liveloop then demonstrate fx
- short demo of OSC (playing notes with a slider from my phone app)

- communities:  in-thread.sonicpi.net is main forum, also has subreddit and google group, currently v3 is not supported on Rasbian buster but may be kickstarter for it soon, can also support Sam via Patreon

**Comment by paulfioravanti** [comment]
That sounds like a pretty awesome plan to me!

Perhaps it might be good to just create what you want to, see how long the presentation/demo you want to give is, and then if it ends up being hours long, then perhaps adapt a portion of it for a RORO talk, and then have the entirety of it to develop as a workshop for Code Club Australia (or maybe we could organise a special RORO event...?).

If what you want to do ends up spanning more than one talk's worth of content, we'd be happy to potentially spread out the content over multiple months as well. There are options :)

**Comment by rowena-s** [comment]
@paulfioravanti Am I confirmed for September? I have talk that I'm expecting to take 15-20 mins with questions (I'm expecting lots of those).

**Comment by paulfioravanti** [comment]
@rowena-s That's great to hear! I wasn't sure if you would be ready by September, so I didn't lock you in, but since you're ready, the spot is yours!

**Comment by rowena-s** [comment]
YAY 🎉thanks :)

**Comment by rowena-s** [comment]
If you can't find a second speaker for Sep, I _may_ be able to fill in that slot with more Sonic Pi depending on audience engagement 😛I'm thinking something along the lines of attendee sourcing a "roro syd" composition that can then be shared on the socials.

**Comment by paulfioravanti** [comment]
That sounds like an _excellent_ idea! I would wager that given the subject matter, you're going to have a lot of audience engagement. Would it be okay to confirm a potential double slot just before the weekend, or does that not give you enough time to prepare?

**Comment by rowena-s** [comment]
That's fine with me, not much prep needed when you get the audience to do most of the work :)

**Comment by RocketRobC** [comment]
Hi @rowena-s . Sorry I didn't get back to you in the first place, I only just caught up with this thread. 

I initially thought I'd be able to spend some time learning the interface and then writing some tracks but it never ended up happening so I'm really happy to see someone else pick it up and I'm looking forward to your presentation. 

Do you have your own amp or PA? I'm not sure what the AV is like at the venue this month so I'll need to see what they have that you can play back through. 

Also, is there a photo I can grab for the slides?

**Comment by rowena-s** [comment]
Hi Rob, 

Don't have my own PA but I've been to a few of the Women Who Code workshops hosted at the venue (one of them was even in Sonic Pi !) If it's going to be the same setup, I think their AV system should be fine.
I was going to ask if I could go there earlier anyway because I'm planning to run everything off an RPi (don't worry, I'll take a laptop as backup :) ) so some setup will be involved.

Do you mean a photo of the Sonic Pi UI or a profile pic of me?

**Comment by paulfioravanti** [comment]
A profile pic of you, personally, and your Twitter handle if you have one. Also, please feel free to take a double spot!

**Comment by rowena-s** [comment]
Twitter: @goldenfennec
 Profile pic: [GDrive Link](https://drive.google.com/file/d/10PKHO4FFr8zSGF6jxSJCU3yaTrNrs9lC/view?usp=sharing)

I'm also working on a [gist](https://gist.github.com/rowena-s/f32cc837db205f8e8b270f90b1dba402) with a collation of resources I've found and code snippets for people to copy-paste if they want to follow along. Please feel free to preview it and thank you for the double spot 😄

**Comment by paulfioravanti** [comment]
Thanks so much for doing your talk tonight, @rowena-s! When you're ready, please tweet out any resources you would like to share at `@rorosyd` and we'll make sure to give them a retweet.
