### ISSUE TITLE
Know Thy App

### ISSUE THREAD

**Issue by lachie** [rails-oceania/roro#195]
Hey

I'd like to give a talk about getting to know your app via functional & load testing.
The main thrust is to encourage thinking of apps in global terms to promote an in-depth knowledge and intuition of all the parts of apps (code and stack) by using different tools to explore it.

- What is the goal of your app?
- Which is the most important part of your app?
- Especially as a newly minted junior, how do you get to know the app in depth? Empirical methods like load testing can help explore this.
- Load & functional testing helps develop a realistic, intuitive-but-evidence-based feel for how an app runs, and thus the relative importance of its components and their interconnection.
- it also helps in thinking clearly about the trade-offs your app can make - e.g. is it more important to be fast or correct? Why?

Although load testing is an empirical or forensic approach that applies to all sorts of apps, I think its a particularly good fit for Rails apps given the performance vs productivity trade-off that Rails offers.

Full disclosure: I work for flood.io & will incidentally mention flood.io as a good tool for easily getting in to load testing :)

Intended audience: load testing beginners, developers of all ages

I'd like to present at the November meetup
I can't seem to add labels so: this'd be a full length talk

it me:
@lachiecox
https://github.com/flood-io/site/blob/602b4ec00da224bfa5fc3c24bbfcc16d558002a3/app/assets/images/landing/about/mugshot-lachie-alt%402x.jpg

**Comment by paulfioravanti** [comment]
Hey Lachie! Thanks for the submission, and consider yourself on for November!

About your photo, though, I'm assuming that the flood.io site repo is private, so have you got a photo that's more publicly accessible? ;)

**Comment by lachie** [comment]
Cool!
Ok, did this work?
![mugshot-lachie](https://user-images.githubusercontent.com/265/48107787-06fc4280-e295-11e8-9a79-54cad16d1d3e.jpg)

**Comment by paulfioravanti** [comment]
Certainly did! Nice portrait! 😄

**Comment by paulfioravanti** [comment]
Hey Lachie, thanks for the talk!

Assuming your slides are okay to make public right now, given you'll be doing the talk again in Melbs, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
