### ISSUE TITLE
How not to have future developers curse you

### ISSUE THREAD

**Issue by keithpitty** [rails-oceania/roro#196]
# How not to have future developers curse you
You're staring at some code, trying to figure out what it is intended to do. Maybe you're reviewing a PR. Worse still, maybe you're under pressure trying to solve a production problem. The code makes no sense at all to you.

How can you learn from this situation and ensure that you will not be the person being cursed for leaving a trail of unintelligible code behind you?

## Intended Audience
Beginners, intermediates

## Intended Meetup
November, 2018

## Length
Lightning talk

## Personal details
Twitter: @keithpitty 
Photo: https://secure.gravatar.com/avatar/a871f5bf1b1a48262a04ec49bc60fa77

**Comment by keithpitty** [comment]
@paulfioravanti @RocketRobC if you need another lightning talk for Tuesday, here's my proposal.

**Comment by paulfioravanti** [comment]
Thanks, @keithpitty! We'll lock you in for November!

**Comment by paulfioravanti** [comment]
Hey Keith, thanks for for the talk last night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

**Comment by keithpitty** [comment]
@paulfioravanti slides shared!
