### ISSUE TITLE
Introduction to Infrastructure as Code

### ISSUE THREAD

**Issue by sarneaud** [rails-oceania/roro#197]
> Thanks for proposing or suggesting a talk for RORO Sydney!
> 
> For talk proposals, please provide the following information:
> 
> - Name of talk (in the title field)
> - Brief summary of the talk content

A web applications needs a lot more than Ruby code to run --- databases, DNS records, etc.

I'll talk about why it's a good idea to make all this infrastructure into code, too, and give an introduction to how it can be done.

>  - Intended audience - beginners, intermediates, advanced, all levels
>   (feel free to use Github Labels, located on the right of the screen, to specify this)

Intermediates and above will get the most, but hopefully interesting for all levels.

> - Which month's meetup you would like to present at

Any.

> - Length of talk: full-length talk (15 minute) or lightning talk (5 minute)
>   (feel free to use Github Labels, located on the right of the screen, to specify this)

Full.

> - Your Twitter username (if you have one)
> - Link to, or upload of, a photo of yourself that will appear in the meetup slide deck
>   (if you don't specify one, we'll see if we can find one from your social media accounts)
> 
> For talk suggestions, please provide the following information:
> 
> - What you would like to see a talk about
> - What kinds of things you would like to see covered in such a talk

**Comment by paulfioravanti** [comment]
Thanks for the submission, Simon! How open are you to being on reserve for December? If possible, I'd like to leave as much time as possible to give people who haven't spoken this year a chance to submit a proposal. If we end up with an empty spot in December, you can take it; if not, then definitely February.

**Comment by paulfioravanti** [comment]
Okay, Simon, you're on for February 2019 😄

**Comment by paulfioravanti** [comment]
Sorry I wasn't able to make the talk tonight, but thanks for doing it @sarneaud! If you make your slide deck public, please put the link here and we'll tweet it out!
