### ISSUE TITLE
Exercism Exercise - Pangram

### ISSUE THREAD

**Issue by dav-armour** [rails-oceania/roro#199]
Hi,
I would like to present my [solution](https://exercism.io/my/solutions/f51e1aa7a36f436e8de5614d1a5ff201) for December's exercism challenge

Intended audience: beginners
Meetup: December
Length of talk: lightning talk (5 minute)
Twitter: @DavArmour

**Comment by paulfioravanti** [comment]
Nice work tonight, @dav-armour!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
