### ISSUE TITLE
Lotus Framework - a perfect choice for backend API

### ISSUE THREAD

**Issue by joneslee85** [rails-oceania/roro#20]
Well, the last submission was Lotus in 15' but since it is kinda useless, I'd like to change the topic to how to build a backend API with Lotus Framework.

**Comment by holodigm** [comment]
Sounds great Trung. When would you like to do this one?

**Comment by joneslee85** [comment]
@holodigm sorry for late reply, I would love to do it in March, any chance?

**Comment by holodigm** [comment]
Definitely, locked and loaded. Thanks @joneslee85

**Comment by mootpointer** [comment]
Shipped!
