### ISSUE TITLE
Introduction to Crystal 💎

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#200]
[Crystal](https://crystal-lang.org/) is a language that claims to be as "fast as C, slick as Ruby", which is potentially good news for any Rubyist wanting to get native speeds from their programming language, without giving up the niceties of Ruby.

So, this is a presentation request to do one or more of the following (or anything else you can think of!):

- tell us all about the language
- show some demos
- show some comparisons between Ruby and Crystal code syntactically
- do some benchmark speed comparisons between the same code written in Ruby and Crystal

**Comment by websymphony** [comment]
I am interested in doing a lightening talk for this.

**Comment by mathewdbutton** [comment]
Great @websymphony sorry I completely missed this! Looking forward to hearing about this.

Which meetup would you like to present at? October?

I just need a few details around your talk:
- How long (just a rough estimate)
- Your preferred twitter photo
- A brief description of your talk

Thanks for volunteering @websymphony!

**Comment by websymphony** [comment]
Hey @mathewdbutton,

If october meetup is after middle of month then that works, otherwise can do November.

I have same handle on twitter as github, so that photo should work.

I think it should be around 10 15 minutes.

Will probably talk about similarities and differences between the languages. With some code samples, live demo etc.

**Comment by mathewdbutton** [comment]
Hey @websymphony I'm just catching up after being away for the long weekend.

The meetup for October is the 13th (next Tuesday) so not sure if that timing will work. So shall I put you down for speaking October 13th or for November's Meetup on Nov 10th?

**Comment by websymphony** [comment]
Hi @mathewdbutton,

November 10th should be fine.

**Comment by mathewdbutton** [comment]
@websymphony great! thanks for offering to speak, You're locked in for November! Looking forward to hearing your talk

**Comment by mathewdbutton** [comment]
hey @websymphony 

I just wanted to check in to see if you're still available to speak the November 10th Meetup?

**Comment by websymphony** [comment]
Yup still on.

**Comment by mathewdbutton** [comment]
Sweet thanks for the confirmation

**Comment by mathewdbutton** [comment]
Thanks @websymphony for showing us the Crystal programming language, that was a great way to show the differences and similarities.

Would it be okay if I uploaded the recording of your talk to YouTube?

**Comment by websymphony** [comment]
Yup, go for it.

**Comment by mathewdbutton** [comment]
Thanks Mate
