### ISSUE TITLE
Deep dive into Serverless Ruby on AWS Lambda

### ISSUE THREAD

**Issue by stevenringo** [rails-oceania/roro#202]
AWS Lambda recently released support for Ruby as a first-class citizen. This talk will be a quick deep-dive into how to run your Ruby apps in AWS Lambda.

- Probably intermediate to advanced.
- Feb 2019
- Full-length talk
- @stevenringo on twitter

**Comment by stevenringo** [comment]
Please add labels intermediate sydney-presentations—I don't seem to be able to do this.

**Comment by paulfioravanti** [comment]
No worries, Steven. These things happen. We'll bump you over to the March meetup 👍

**Comment by paulfioravanti** [comment]
@stevenringo apologies for not pinging you with a reminder for this month's meetup. Would you like to be re-scheduled for a future meetup. Including the April meetup onwards is fine.

**Comment by SoxFace** [comment]
Hi @stevenringo - can we lock you in for April 9th 2019?

**Comment by stevenringo** [comment]
> Hi @stevenringo - can we lock you in for April 9th 2019?

Yes! And again my apologies for the March confusion. Its locked in for April 9!

**Comment by paulfioravanti** [comment]
@stevenringo great, thanks!

**Comment by paulfioravanti** [comment]
@stevenringo this is your one week speaker alarm clock/check in 😄 Still okay for next Tuesday?

**Comment by paulfioravanti** [comment]
Hey @stevenringo , thanks for speaking last night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
