### ISSUE TITLE
Inspecting the Accessibility Inspector by @lol-russo

### ISSUE THREAD

**Issue by SoxFace** [rails-oceania/roro#204]
Thanks for proposing or suggesting a talk for RORO Sydney!
I'm nominating Jack 
- Name of talk (in the title field) 
Inspecting the Accessibility Inspector by Jack Lo Russo
- Brief summary of the talk content
A lightening version of the talk delivered at A11y Bytes Sydney on Global Accessibility Awareness Day in 2018
- Intended audience - beginners, intermediates, advanced, all levels
  all levels
- Which month's meetup you would like to present at
February
- Length of talk: full-length talk (15 minute) or lightning talk (5 minute)
5 mins
- Your Twitter username (if you have one)
lol_russo
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck

For talk suggestions, please provide the following information:

- What you would like to see a talk about
Accessibility, design systems
- What kinds of things you would like to see covered in such a talk
Theory and application

**Comment by SoxFace** [comment]
@lol-russo I took the liberty of submitting on your behalf :D

**Comment by paulfioravanti** [comment]
Hi @lol-russo, if you can confirm that you'd like to do the presentation for Feb, we're more than happy to lock your position in!

**Comment by lol-russo** [comment]
Hi @paulfioravanti — definitely interested! Thanks for nominating me @SoxFace.

Thought I'd quickly provide a bit more information. This would be a lightning talk about the Accessibility inspector tools provided in the DevTools of both Chrome and Firefox. I'll touch on how browsers take what is in the DOM tree and modify it into a form that is useful to assistive technology, and use a quick demo example to show how the accessibility inspector tools can help debug accessibility issues.

Not strictly RoR related, but relevant to anyone building things for the web I guess!

**Comment by paulfioravanti** [comment]
Sounds great, @lol-russo, and I'm sure it will be of great interest to our audience! Consider your position locked in for February!

**Comment by paulfioravanti** [comment]
Hey @lol-russo, thanks so much for speaking tonight, and sorry I couldn't be there to see it!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and then tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
