### ISSUE TITLE
Automation in your workflow to ease mundane tasks (A demo of Automator & Jira Assistant)

### ISSUE THREAD

**Issue by Steven-Chang** [rails-oceania/roro#205]
Thanks for proposing or suggesting a talk for RORO Sydney!

For talk proposals, please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
Hi, I've found that there's a lot of mundane things you need to repeat daily which uses up a lot of your mental energy. I have been using Automator on Mac and Jira assistant to make these tasks a lot easier. I think a lot of developers would find these tools extremely helpful and I'd like to give a demo. 

- Intended audience - beginners, intermediates, advanced, all levels
  (feel free to use Github Labels, located on the right of the screen, to specify this)
All levels

- Which month's meetup you would like to present at
Any

- Length of talk: full-length talk (15 minute) or lightning talk (5 minute)
I think I could do either, if it was the lightning, I'd just rush through it and give people a link to code or something like that. 

  (feel free to use Github Labels, located on the right of the screen, to specify this)
- Your Twitter username (if you have one)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck
  (if you don't specify one, we'll see if we can find one from your social media accounts)
![14280689](https://user-images.githubusercontent.com/14280689/52162317-2c7ada00-2726-11e9-81db-9bab821b3ce1.jpeg)

For talk suggestions, please provide the following information:

- What you would like to see a talk about
I'm really big into automation, so anything related to that would be great. 

- What kinds of things you would like to see covered in such a talk
Any tips that can reduce regular mundane tasks!

**Comment by paulfioravanti** [comment]
Hi @Steven-Chang thanks for submitting a talk! Would you be okay doing the full-length version of your presentation for the February meetup?

**Comment by Steven-Chang** [comment]
Hey Paul,

does it matter that what I'm talking about isn't Rails specific?
I was just thinking on the train today...

Steve

________________________________

**Comment by paulfioravanti** [comment]
Hey Steven,

No need to submit anything beforehand; as long as you have a presentation to give on the night, and it's around 15 mins, all good!

As for not being Ruby/Rails-specific, that's totally fine. We like to have Ruby-related talks, but we also like to have non-Ruby talks that would also be of interest to Rubyists, and I think your talk falls into that bucket :)

**Comment by paulfioravanti** [comment]
Oh, and I'll also lock you in for the February meetup!

**Comment by paulfioravanti** [comment]
Sorry I couldn't make it to see your talk tonight, @Steven-Chang, but thanks so much for giving it!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and put the link in this issue and we'll tweet the slides link out from the `@rorosyd` account.

**Comment by steven-chang-maestrano** [comment]
@paulfioravanti - No problems, thanks for organising the event!

**Comment by paulfioravanti** [comment]
Thanks, Steven! We've given the slides a tweet out: https://twitter.com/rorosyd/status/1095499713405566976
