### ISSUE TITLE
A Programmer's Guide to Public Speaking

### ISSUE THREAD

**Issue by dondonz** [rails-oceania/roro#208]
**Name of talk (in the title field)**
_A Programmer's Guide to Public Speaking_. Or if you prefer puns, _From Stand-up to Standups_.

**Brief summary of the talk content**
Public speaking is a learnable skill and can be substantially improved with a few tweaks.

I used to be terrified of public speaking. After more than a decade of performing comedy, I have learned to feel confident on stage, and you can too. (Unfortunately I still don't know how to be funny.)

I will discuss immediately actionable tips you can apply to tomorrow's morning standup, the weekly all-company meeting, or your next meetup talk.

**Intended audience - beginners, intermediates, advanced, all levels**
Anyone who wants to be a confident public speaker.

**Which month's meetup you would like to present at**
April 2019 or later.

**Length of talk: full-length talk (15 minute) or lightning talk (5 minute)**
Full-length talk (15 minutes).

**Your Twitter username (if you have one)**
@failscasts

**Comment by paulfioravanti** [comment]
Thanks, @dondonz! We'll lock you in for the April meetup. I also put my preference in for using the punny title 😆

**Comment by SoxFace** [comment]
I am LIVING for this!!! Can't wait to see you in action @dondonz

**Comment by paulfioravanti** [comment]
@dondonz this is your one week check-in :) Still good for next Tuesday?

**Comment by dondonz** [comment]
@paulfioravanti @SoxFace I am super keen to present at the April edition of RORO! The more I work on the talk, the more excited I get!

FYI I've decided to slightly change the title, but the content and theme is the same.

**Comment by paulfioravanti** [comment]
Thanks, @dondonz, your presentation is all retweeted and memo-ed in the RORO repo!
