### ISSUE TITLE
Building a geo-aware travel blog in Rails

### ISSUE THREAD

**Issue by slead** [rails-oceania/roro#209]
During 2018 I took a year off to go travelling with my family. Like a good geek I knew I needed to set up a blog to showcase my travel photos, but I couldn't find anything just right so I built my blog from scratch.

The key difference is that the blog is geo-aware, meaning that the posts can be viewed and searched for on a map interface, which is a far more intuitive way to view a travel blog (compared to the standard alphabetical listing of place-names).

This talk covers the key gems used, which include `geocoder`, `leaflet` and `flickraw`, and explains how this approach could be used for other more serious projects.

- Intended audience - all levels
- Which month's meetup you would like to present at - April 2019
- Length of talk:  lightning talk (5 minute)
- Your Twitter username - @stephenlead
- [Link to](https://avatars2.githubusercontent.com/u/133596?s=400&v=4) a photo of yourself that will appear in the meetup slide deck

**Comment by slead** [comment]
(for some reason I can't add labels so please feel free to add them)

**Comment by paulfioravanti** [comment]
Sounds awesome, @slead! We'll lock your spot in for April (though if you have your talk ready, then you're more than welcome to do it for the March meetup next week if you're able!)

**Comment by slead** [comment]
@paulfioravanti thanks, I don't think I can make the March meetup but I'll let you know if my plans change

**Comment by paulfioravanti** [comment]
Hi @slead, it's one week left until RORO, so I'm just checking in to make sure you're still okay for next Tuesday. All good?

**Comment by slead** [comment]
Hi @paulfioravanti yep, I'll be there

**Comment by paulfioravanti** [comment]
Hey @slead , thanks for speaking last night!

We've retweeted out your [last tweet to us](https://twitter.com/stephenlead/status/1115575578181033984), but if you used any slideware (sorry I wasn't there in person so I could actually know!), could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give that a retweet as well.
