### ISSUE TITLE
Better APIs With GraphQL Ruby

### ISSUE THREAD

**Issue by joshprice** [rails-oceania/roro#212]
Quick introduction to GraphQL concepts, how to get started in Ruby and a glimpse of why it's the future of APIs.

- Intended audience - all levels
- Which month's meetup you would like to present at - March 2019
- Length of talk: 15 minute+
- Your Twitter username @joshprice

**Comment by paulfioravanti** [comment]
Thanks, @joshprice! Locked in!

**Comment by paulfioravanti** [comment]
Hey @joshprice, thanks again for the last minute talk preparations!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
