### ISSUE TITLE
Problems that Occur when Multiple Things Use a Database at the Same Time

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#213]
Opened on behalf of @damncabbage for his update of a talk from 2014 (#7). Thanks, Rob!

**Comment by damncabbage** [comment]
My pleasure! Here's my [hack-edited](https://twitter.com/damncabbage/status/1105397479166472192) redux version of that 2014 talk:
https://robhoward.id.au/talks/2019/03/databases-and-race-conditions.pdf

**Comment by paulfioravanti** [comment]
Slide deck tweeted out. Thanks, Rob!
