### ISSUE TITLE
Submit April session Phone Exercisim

### ISSUE THREAD

**Issue by julcharton** [rails-oceania/roro#214]
Hi guys,

please find attached my solution for the next RORO meetup exercise. 

I took two different approaches here: 

- A back end approach (see attached) using a combination of regexp and .gsub.
- the second one if a Front End approach (input masks). I used Vue JS for this exercise because I think it is a great tool for front 

end dev and you can easily use Vue JS as part of your rails project.  (to start it, npm install and npm run serve will do)

Hope you'll like it. 

Waiting for you feebacks.
[phone_number_ex_back_and.rb.zip](https://github.com/rails-oceania/roro/files/3001122/phone_number_ex_back_and.rb.zip)
<img width="647" alt="Screen Shot 2019-03-21 at 20 36 18" src="https://user-images.githubusercontent.com/31607462/54889124-02a88d00-4ef7-11e9-9e16-d6365e35278e.png">

**Comment by paulfioravanti** [comment]
Hi @julcharton, thanks for your submission!

The front end version looks pretty cool, and I think it's definitely worth demoing along with your solution at the next RORO! Did you mean to include that code as well, or perhaps a gist? If not, then it would be awesome if you did as I'm sure that many people will be curious as to how you implemented this solution.

As for your back end solution, when you downloaded the problem using `exercism download --exercise=phone-number --track=ruby`, you may have seen some tests that go along with the problem to make sure you solved it correctly. Have another look at your solution and run the tests against it to make sure all is well. Once you've got all the tests passing, I'd encourage you to submit your solution up to Exercism and see if you get any further feedback from its community. Good luck!

**Comment by julcharton** [comment]
Hi @paulfioravanti , 
here is my repo for the Front end https://github.com/julcharton/Vue.js_phone_mask

The issue with the tests on Exercism is they are all design for US format phone number. 
Shall I rewrite some for Australian cellphone format ?

**Comment by paulfioravanti** [comment]
I would say that since Exercism exercises are pretty much standardised, try creating a solution that passes all their tests (running the tests during your lightning talk to show that your implementation passes is a great proof point showing the validity of your solution). Then, make it public somewhere (either on Exercism or your own Github repo) so that other RORO community members who attempt this month's problem can compare their solution to yours. 

If you want to then create another implementation complementing the Exercism version that deals with Australian mobile phone formats, then by all means, please do! It might be an interesting compare-and-contrast point to hear about the differences in complexity between parsing US and Australian phone numbers.

**Comment by paulfioravanti** [comment]
Nevertheless, @julcharton, and I probably should have done this before, but we'll lock you in for the April meetup! Thanks!

**Comment by julcharton** [comment]
here is my repo with the Exercism tests all passed. 
https://github.com/julcharton/Exercism_phone_ruby_vuJS

**Comment by paulfioravanti** [comment]
@julcharton do you have a Twitter username?

**Comment by julcharton** [comment]
@paulfioravanti  @Spike_BDG

**Comment by julcharton** [comment]
Hi @paulfioravanti ! 
I will have to go to Melbourne for a big work opportunity from the 8 until the 11th of April. So I won't able to attend this Meetup.. 
I am so sorry for letting you down like this. 
My github repo is public so feel free to use my code for this session.

**Comment by paulfioravanti** [comment]
Hey @julcharton, congratulations on your big work opportunity! Totally understand that you will not be around for the meetup, so please don't think you are letting anyone down! 😄Enjoy the Melbourne ☕️ !

What I might do then is just close this issue, but please feel free to take on an Exercism talk in the future, or maybe submit another talk! If your experiences in Melbourne end up being something you think the community could benefit from, by all means please open an issue about it!
