### ISSUE TITLE
Making software maintainable

### ISSUE THREAD

**Issue by brushbox** [rails-oceania/roro#215]
A brief overview of taking software from a difficult to maintain state and evolving it to be more maintainable. The main focus will be on technical aspects and going over a case study of some software that I took through this process.

Along the way we'll look at:

* Separation of concerns
* Using types to improve reliability
* Finding ways to discover errors sooner
* A very brief diversion into Rx.rb/Observable (there's a whole other talk lurking in there)
* Streaming for scalability
* Specs as documentation
* Code generation

...well, there's a lot there - so we'll cover what we can in the time available.

I spoke to Rob at the last meetup and said I would have this ready for April.

Talk length: 15min

Twitter: @brushbox

**Comment by paulfioravanti** [comment]
Thanks, @brushbox! It looks like we're full up for the April meetup, so would you be okay with, say, being a backup for the April meetup in case of any cancellations, and a definite for May?

**Comment by paulfioravanti** [comment]
@brushbox, I talked with @RocketRobC and he said you were good with May, so I'll lock you in. Please let me know if that changes!

**Comment by brushbox** [comment]
Hey Paul,

That's fine. I won't be able to make it tonight but I'll lock in May 14th
for my talk.

Cheers,
Pete.

**Comment by paulfioravanti** [comment]
Hey @brushbox, thanks for speaking on Tuesday!

If you wanted to share your presentation materials, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

**Comment by brushbox** [comment]
It was a pleasure, thanks.

I've published the slides at
https://www.slideshare.net/PeterSumskas/making-software-maintainable

Cheers,
Pete.
