### ISSUE TITLE
Machine Learning (e.g. TensorFlow) in Ruby

### ISSUE THREAD

**Issue by cyclotron3k** [rails-oceania/roro#218]
This is a talk request.

If anyone has used one of the TensorFlow gems in Ruby, or otherwise achieved some level of machine learning in Ruby, I'd love to hear about it.

Failing that, I'd love to hear a general intro to Machine Learning talk.

Ruby Gems:
* tensorflow.py
* tensor_stream
* tensorflow.rb

**Comment by hhemanth** [comment]
I would like to present this talk. August or September? I will share the agenda soon as well.

**Comment by hhemanth** [comment]
**Talk Title**: Introduction to Machine Learning in Ruby

**Talk Outline**:

- Introduction to Machine Learning & AI 
- Machine Learning Libraries and Gems available for Ruby
   - Classifier Reborn, Decision Tree, knn, similarity, KMeansClusterer, KMeans, RubyFann
- Tensorflow.rb
- small demo
**Talk Duration** : 15 to 20 mins
The talk will be a small introduction to Machine Learning and Artificial Intelligence. The talk will be useful for Beginners as well as experienced Ruby developers. I will try to introduce the state of the art in Machine Learning libraries in Ruby. 

I will also touch upon limitations where you will be forced to Jump ship to continue your machining learning journey. 

I outline of the talk may change slightly.

**Comment by paulfioravanti** [comment]
Thanks for the submission @hhemanth! You're on for November!

**Comment by mathewdbutton** [comment]
@hhemanth do you have a Twitter account? If so, what is it, so we can put it in the meetup details.

**Comment by hhemanth** [comment]
My twitter account is hhemanth

**Comment by mathewdbutton** [comment]
@hhemanth We've had a wee change of plans with Novembers RORO, it clashes with an event we'd like to go and figure a bunch of the Sydney Ruby community would like to go to it as well. As a result we've postponed November's RORO meetup by a week, [here is the tweet for reference](https://twitter.com/rorosyd/status/1189380669006204928?s=20). So your talk will now be on the 19th of November, I hope that still works for you, but please reach out if it does not.

**Comment by mathewdbutton** [comment]
Hey @hhemanth 
Thanks so much for doing your talk yesterday, it was a tricky topic to cover in a short amount of time. Could you share a link to your slides? and we'll share them on twitter and link to them in our repo.
