### ISSUE TITLE
Attempt at Exercism challenge (beginner level)

### ISSUE THREAD

**Issue by josephine-c** [rails-oceania/roro#219]
Hi there RORO team,

I was thinking about doing the Exercism challenge, but not sure if it would be for the phone numbers formatting or the high score challenge? Please kindly advise. Happy to present if I can get the code working by next week RORO!

Cheers,
Josephine

**Comment by paulfioravanti** [comment]
Hi @josephine-c! Thanks for submitting this issue, and sorry for the confusion! I accidentally put _next_ month's challenge (High Scores) in the Meetup description (which is now fixed). The challenge for this month is definitely Phone Number (https://exercism.io/tracks/ruby/exercises/phone-number). 

If there is anything that myself, @RocketRobC , or @SoxFace can do to assist, please let us know! We'll lock you in for next Tuesday, and if something unforeseen happens, please update the issue 😄 

Also, would you be able to provide a few more details for our slide deck and meetup info if you have them?

- Your Twitter username (if you have one)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck
(if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by josephine-c** [comment]
Hi @paulfioravanti,
Thanks for replying so quick! I might need to ask you about how I can test my code using the minitest gem, so thank you in advance for your support!

I don't have a Twitter (should I get one?

Here is a link to a pic you can use for my photo (https://drive.google.com/file/d/1LujBOnBqTjbQ4Kh3XVLQselb_NgbBgtP/view?usp=sharing)

**Comment by paulfioravanti** [comment]
Hey @josephine-c,

First, if you haven't already, create an account on [Exercism](https://exercism.io) and download the [Exercism command line interface](https://exercism.io/cli) program (that page will tell you what to do for the operating system you're using).

Once you're all installed, you should be able to download the Phone Number exercise with the following command: `exercism download --exercise=phone-number --track=ruby`. There, you'll see that the exercise contents will be in a `exercism/ruby/phone-number` folder with a Ruby file to fill in with your solution, a set of tests, and a README file.

The README should include the following instructions on how to run the tests:

- Install Minitest (`gem install minitest`)
- Run the tests (`ruby phone_number_test.rb`)

Give that a shot and let us know if you have any issues!

Thanks for the photo link, and as for Twitter, that's entire optional. If you have one already, then we'll just mention it on the slides and from the RORO Twitter account for the meetup promo stuff etc. If not, and you don't want one/aren't interested, then that's totally fine! 😃

**Comment by josephine-c** [comment]
![image](https://user-images.githubusercontent.com/48109810/55448855-22d1fd80-5615-11e9-912c-06ccc536bf72.png)

@paulfioravanti I made an account on Exercism and have downloaded the interface on my UBUNTU/BASH command line program (using windows). I tried that line of code [exercism download --exercise=phone-number --track=ruby] but I got an error, see my screen print I pasted above. Any advice? Thanks in advance!

Josephine

**Comment by josephine-c** [comment]
@paulfioravanti Just switched to independent mode and was able to download the exercise, so ignore my previous comment!

**Comment by josephine-c** [comment]
@paulfioravanti FYI, I just made my twitter account @jytc_

**Comment by paulfioravanti** [comment]
@josephine-c great! We'll add it to our slide deck and you should see a mention from us soon 😄

**Comment by paulfioravanti** [comment]
@josephine-c Just one extra bit of info: what is your surname?

**Comment by paulfioravanti** [comment]
Nevermind. I found you at https://josephine-c.github.io/ :smile:

**Comment by josephine-c** [comment]
@paulfioravanti do you guys use google cast? I only have usb-c connection my laptop.

**Comment by paulfioravanti** [comment]
We don't have Google cast at Airtasker, but I _think_ they have a USB->HDMI cable you should be able to use (we've had speakers with USB-C laptops present before), but just to make extra sure, @SoxFace will bring along a cable.

**Comment by josephine-c** [comment]
okay awesome! Thanks @paulfioravanti and @SoxFace!

**Comment by paulfioravanti** [comment]
Hey @josephine-c , thanks for speaking last night! I heard it went great!

Since I don't know whether you used any slides or not, assuming you did, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

Otherwise, if you have a [gist](https://gist.github.com/) of your solution, or if you've put it up in your Github repo (recommended!), then let us know and we'll retweet that out :smile:

**Comment by josephine-c** [comment]
Hey @paulfioravanti - I hope it went better than I felt *nerves* hehe, but here's the link to my code on github (https://github.com/josephine-c/Phone_number). Will you be at the next meetup? Thanks for being a ball of support regardless!!
