### ISSUE TITLE
The Good, the Bad and the Absent

### ISSUE THREAD

**Issue by damncabbage** [rails-oceania/roro#22]
A talk about how we model and represent things like "nothing" or "it worked / it didn't work", and what fancy things we can do with them when do.

(The next part of the ongoing *"how do we try to make sure our stuff doesn't break"* series, wherein Rob looks more and more haggard with every talk.)

PS: This is the first submission I've made without saying hi beforehand. Is this the queue for consideration?
PPS: `Intermediate` tag, please.

**Comment by holodigm** [comment]
Indeed it is Rob :+1: Nice one :)

**Comment by holodigm** [comment]
Great talk @damncabbage! Thanks. Have you put this up anywhere yet?

**Comment by damncabbage** [comment]
Sorry, I missed this; I just posted it in the meetup.com group.

It's up at robhoward.id.au/talks/2015/02/the-good-the-bad-and-the-absent/

**Comment by holodigm** [comment]
Thanks Rob :+1:

**Comment by mootpointer** [comment]
Shipped!
