### ISSUE TITLE
Military-grade security in Ruby

### ISSUE THREAD

**Issue by nathantesler** [rails-oceania/roro#220]
_or: How I Learned to Stop Worrying and Love Cryptography_

Strong encryption and digital signatures are surprisingly easy tools to use in Ruby, and they can be hugely valuable to all types of applications - even if you’re not handling financial transactions, medical data or nuclear launch codes. 

This talk would cover:

- A quick primer/refresher on cryptography (all levels)
- A fun diversion to a practical example of how I’ve used cryptography to let people “hack” into their own bank accounts.
- A practical example showing how to use encryption and digital signatures in Ruby.

I'd be happy to slot in at the May meetup onwards if there's something available?

**Comment by paulfioravanti** [comment]
Hi Nathan,

Thanks for the submission! Just to confirm a few points:

- Can I assume that this is to be a 15 minute full length presentation and not a 5 minute lightning talk (it's fine to be either!)
- Can I assume that you're still using your `@nathantesler` Twitter account?

**Comment by nathantesler** [comment]
Think it's probably best as a full length presentation. And yep, that's my Twitter

**Comment by paulfioravanti** [comment]
Okay, great, thanks, Nathan! We'll lock you in for the [May 14 meetup](https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/jwptrqyzhbsb/).

**Comment by paulfioravanti** [comment]
Hey @nathantesler , thanks for speaking on Tuesday!

If you wanted to share your presentation materials, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
