### ISSUE TITLE
Exercism Challenge - High Scores

### ISSUE THREAD

**Issue by Rainbow-Ninja** [rails-oceania/roro#222]
I would like to complete next months (May 14th 2019) exercism challenge and present my code. From the brief synopsis I've read this is more aimed at beginners I would assume and  would about take 5mins, 10 at the very most if people want to ask a load of questions.

My Twitter name is TheCodeLessTravelled --> @CodeTravelled
My GitHub is Rainbow-Ninja
My mugshot is attached:

![pic](https://user-images.githubusercontent.com/48858686/55871000-1fb6ae80-5bcd-11e9-860a-80184dab10c0.jpg)

Cheers
Jo Dunham from GenTech at Coder Academy

**Comment by paulfioravanti** [comment]
Thanks so much @Rainbow-Ninja! You are locked in for the High Scores Exercism problem at the May meetup! 🎉

**Comment by Rainbow-Ninja** [comment]
Hey hey!
I finally got a chance to finish the exercism challenge tonight. I went to hit the submit link but it's not working. Suggestions? Should I link it here?

**Comment by paulfioravanti** [comment]
Hi Jo,

Great to hear that you finished the exercise!

When you say that submission is not working, what exactly do you mean? I thought that submission to Exercism was done with the CLI, so which submit link are you referring to?

As for linking your solution here, that would be great! I can see you have an [ExercismChallenges](https://github.com/Rainbow-Ninja/ExercismChallenges) repo, so we can put a link to that in the RORO meetup materials for posterity.

**Comment by Rainbow-Ninja** [comment]
After much ado today I've discovered the problem with me submitting is that I run zsh on my terminal and for some reason that causes a common issue with exercism. I'm trying to sort it, but if I can't I'll ask one of my lecturers for a hand on Monday    On Friday, 26 April 2019, 11:31:36 am GMT-4, Paul Fioravanti <notifications@github.com> wrote:  
 
 
Hi Jo,

Great to hear that you finished the exercise!

When you say that submission is not working, what exactly do you mean? I thought that submission to Exercism was done with the CLI, so which submit link are you referring to?

As for linking your solution here, that would be great! I can see you have an ExercismChallenges repo, so we can put a link to that in the RORO meetup materials for posterity.

**Comment by Rainbow-Ninja** [comment]
I got it!!!
https://exercism.io/my/solutions/62e4180e51894536860ded0d4a7d9d88

that's the link. Do I need to do anything more? Do I bring my laptop on the night or need to get there early or any of that? I'll have my lappy with me and probably be early anyway since I'll be coming right after a class. But yer let me know what else i need to doCheersJo
    On Friday, 26 April 2019, 11:31:36 am GMT-4, Paul Fioravanti <notifications@github.com> wrote:  
 
 
Hi Jo,

Great to hear that you finished the exercise!

When you say that submission is not working, what exactly do you mean? I thought that submission to Exercism was done with the CLI, so which submit link are you referring to?

As for linking your solution here, that would be great! I can see you have an ExercismChallenges repo, so we can put a link to that in the RORO meetup materials for posterity.

**Comment by paulfioravanti** [comment]
Bring your laptop on the night, and if you have any specific cables that you use to hook up to an external screen, maybe those too (there will be some at the venue, so don't worry too much).

It would probably be best if you arrived a bit before everything starts just so you can do a tech check and make sure everything that you want to display on screen can get displayed as expected.

**Comment by paulfioravanti** [comment]
Hey @Rainbow-Ninja , thanks for speaking on Tuesday!

If you had any presentation materials to share, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet. Otherwise, feel free to tweet out the public link to your Exercism solution and we'll retweet that.
