### ISSUE TITLE
How we halved our memory consumption in Rails with jemalloc

### ISSUE THREAD

**Issue by carmenhchung** [rails-oceania/roro#223]
Thanks for proposing or suggesting a talk for RORO Sydney!

For talk proposals, please provide the following information:

- Name of talk (in the title field): _How we halved our memory consumption in Rails with jemalloc._
- Brief summary of the talk content: _Based off of [this](https://medium.com/rubyinside/how-we-halved-our-memory-consumption-in-rails-with-jemalloc-86afa4e54aa3) blog article, my lightning talk will run through how my company cut our memory consumption by half (and rapidly increased speed) in our Rails app by implementing jemalloc. I'll run quickly through how to implement jemalloc, how to test its results, and what our final results were._
- Intended audience - beginners, intermediates, advanced, all levels
  (feel free to use Github Labels, located on the right of the screen, to specify this): _All levels_
- Which month's meetup you would like to present at: _May 2019._
- Length of talk: full-length talk (15 minute) or lightning talk (5 minute)
  (feel free to use Github Labels, located on the right of the screen, to specify this): _Lightning talk_
- Your Twitter username (if you have one): _[@carmenhchung](https://twitter.com/carmenhchung)_
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck
  (if you don't specify one, we'll see if we can find one from your social media accounts): _https://avatars1.githubusercontent.com/u/30306087?s=400&u=2d976faaa1ec1b3b0f531d8ed5c7c0ae06b6dff5&v=4_

For talk suggestions, please provide the following information:

- What you would like to see a talk about
- What kinds of things you would like to see covered in such a talk

**Comment by paulfioravanti** [comment]
Thanks for the submission, @carmenhchung! I'm sure a great many people in our community will be interested in hearing this! Consider your place in May's meetup secured!

**Comment by carmenhchung** [comment]
Thanks @paulfioravanti - I'm excited for it! 🥳

**Comment by dondonz** [comment]
Very excited for this talk!

**Comment by carmenhchung** [comment]
Aww thanks @dondonz. As always, I'm inspired by you! :)

**Comment by paulfioravanti** [comment]
Hey @carmenhchung , thanks for speaking on Tuesday!

If you wanted to share your presentation materials, when you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
