### ISSUE TITLE
The Future of Ruby On Rails 

### ISSUE THREAD

**Issue by jwolf81** [rails-oceania/roro#224]
[Ruby on Rails RORO Presentation .pdf](https://github.com/rails-oceania/roro/files/3088000/Ruby.on.Rails.RORO.Presentation.pdf)
Brief summary
Future of Ruby by Jerome Yewdall at The Onset

This is a lightning talk on the future of Ruby on Rails as predicted by Ruby Engineers.

For many startups, Ruby is a language of choice and as they scale, the decision to stay with or move away from Ruby becomes an important one.

We aimed to investigate the future of Ruby, and invited 400 Ruby on Rails Engineers to take part in our report. This talk shares our insights on the current landscape, the threats to Ruby on Rails' future, it's attractiveness to startups and which additional technologies engineers are learning to future-proof themselves for the coming years..

A mix of insights, collaboration with engineers and hopefully some healthy debate!

Intended audience 
- All levels 

Month to present 
- June 2019

Length of talk:
Lightning talk - 5 minutes
Your Twitter username - @jerome_yewdall

**Comment by paulfioravanti** [comment]
Sounds good, @jwolf81! Consider your spot in the June meetup reserved!

**Comment by paulfioravanti** [comment]
Change in speaker details for this issue. The speaker will now be [Sean McCartan](https://www.linkedin.com/in/sean-mccartan-76a7191/).
