### ISSUE TITLE
Exercism Challenge - Acronym

### ISSUE THREAD

**Issue by elloo** [rails-oceania/roro#226]
Hi! I'd like to present next month's (11th of June) exercism challenge and provide my solution to it. It will be a lightning talk aimed towards beginners.

Twitter: @ewelinloo
![Headshot](https://pbs.twimg.com/profile_images/1008496024615247872/034Ov8VS_400x400.jpg)

**Comment by paulfioravanti** [comment]
Thanks very much @elloo! You're all locked in for the June meetup!

**Comment by paulfioravanti** [comment]
Thanks for sharing your solution last night, Ewe Lin! If you have your solution on a [Gist](https://gist.github.com/), or if you have it published on your Exercism profile, then please tweet out a link to it at `@rorosyd` and we'll give it a retweet.
