### ISSUE TITLE
A tour of dry-schema and dry-validation 1.0

### ISSUE THREAD

**Issue by timriley** [rails-oceania/roro#227]
👋 Hello! I'd like to propose a talk for the **June 11th** meeting (if you still have a free slot!)

### A tour of dry-schema and dry-validation 1.0

The release of dry-validation 1.0 is just around the corner, so now is the perfect time to learn about its powerful approach to data validation.  

If your Ruby app accepts external input (hint: yes, it does!), then this talk is for you. We’ll:

- Take a fresh look at why we validate in the first place
- Run through dry-validation’s rationale and history
- Learn how it works (along with its new companion, dry-schema)
- See it in action in a typical app, and
- Discover how it can improve our app architecture

You’ll leave with a couple of new (and newly API stable!) tools to use, as well as a new appreciation for the importance of data validation in any kind of application.

**Intended audience**: All levels
**Length of talk**: Full-length (15 minutes)
**Twitter handle**: [@timriley](https://twitter.com/timriley)

And here's a piccie:

![Tim Riley](https://user-images.githubusercontent.com/3134/58378243-4477b180-7fd4-11e9-90cf-191cf0b18038.jpg)

Thanks! If you could let me know sometime this coming week if there's space for the talk, that'll leave me enough time to make sure it's good and ready :)

**Comment by paulfioravanti** [comment]
Hey Tim, we definitely have a spot for you at the next meetup! Thanks for the submission, and please consider your place locked in!

**Comment by timriley** [comment]
Thanks @paulfioravanti!

**Comment by filterfish** [comment]
\o/

**Comment by paulfioravanti** [comment]
Thanks for the talk last night, Tim!

If you plan to share your slides, when you have a few moments, could you please export them PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

**Comment by timriley** [comment]
Thanks Paul! Link to slides tweeted and also here for completeness: https://speakerdeck.com/timriley/a-tour-of-dry-schema-and-dry-validation-1-dot-0

:)
