### ISSUE TITLE
How to debug a running process.

### ISSUE THREAD

**Issue by filterfish** [rails-oceania/roro#228]
You start rails and make a few requests; looks good. And then it all grinds to a halt. What next?

My prosed talk hopes to give you some tools with which to work out what happened. How do you debug a process that's still running (or may have been running in production for a year)? How do you know if it's stuck in an infinite loop? Or if it's waiting for a network resource?

This will be a gentle approach to working out "WTF is my machine/app doing!"

**Comment by paulfioravanti** [comment]
You're in just in time. Thanks, Richard! Talked locked in!

**Comment by paulfioravanti** [comment]
Thanks for the talk last night, Richard!

If you plan to share your slides, when you have a few moments, could you please export them PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
