### ISSUE TITLE
Using Deis to deploy with docker

### ISSUE THREAD

**Issue by tobyhede** [rails-oceania/roro#23]

**Comment by holodigm** [comment]
New and shiny! :+1:

**Comment by tobyhede** [comment]
I am still willing and able to do this talk

**Comment by bradly-swart** [comment]
upvote

**Comment by holodigm** [comment]
Hi @tobyhede Would you like to do this next week, the 9th?

**Comment by holodigm** [comment]
Awesome talk @tobyhede Shipped
