### ISSUE TITLE
A tale of gems and opals

### ISSUE THREAD

**Issue by cyclotron3k** [rails-oceania/roro#230]
I made a gem to scrape Opal card information.

This is a talk about screen scraping and gem production.

Audience: beginners & intermediates
Month: July
Length of talk: 15 minutes?
Twitter: @cyclotron3k

**Comment by paulfioravanti** [comment]
Awesome, thanks, Aidan! Locked in for July! Great talk name, too! 😄

**Comment by paulfioravanti** [comment]
Hey @cyclotron3k, just confirming that you're still all good for next week!

**Comment by cyclotron3k** [comment]
@paulfioravanti  yep, all set!

**Comment by paulfioravanti** [comment]
Thanks for the presentation last night, @cyclotron3k! Like your previous talks, if you're going to share your slide decks, make sure to tweet them out tagging rorosyd and we'll give them a re-tweet!
