### ISSUE TITLE
Why does diversity in tech need "Debugging"?

### ISSUE THREAD

**Issue by coderdan** [rails-oceania/roro#231]
I'd like to do a lightning talk on "Debugging Diversity", a film project I've been working on about gender diversity in tech. I'd like to show the trailer (approx 2mins) and a few supporting slides (about 5-7m in total).

More info here: https://debuggingdiversity.com

Audience: all levels
Month: July (there is an Indiegogo campaign during July so would be good timing)
Length of talk: 5-7minutes
Twitter username: https://twitter.com/danieldraper
Link to, or upload of, a photo of yourself: twitter profile pic is fine

**Comment by paulfioravanti** [comment]
Mate, you're on.

**Comment by coderdan** [comment]
Thanks, @paulfioravanti !

**Comment by paulfioravanti** [comment]
Hey @coderdan , thanks for speaking last night!

If your slide deck is something that you're happy to share publicly, then by all means please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet!
