### ISSUE TITLE
A beginner's guide to learning Ruby

### ISSUE THREAD

**Issue by lifeparticle** [rails-oceania/roro#232]
I would like to talk about how to learn Ruby, if you are learning a language for the first time or you used code in different languages. This beginner's guide will help you to up and running
with Ruby world.

Link: https://github.com/lifeparticle/Ruby-Cheatsheet

- Intended audience: all levels
- Month: August
- Length of talk: 10 minutes
- Photo: https://mahbub.ninja/image/dp.png

**Comment by paulfioravanti** [comment]
Awesome, @lifeparticle, thanks for the submission! We still have a spot open for the July meetup next week if you would like it, otherwise, August is all good!

**Comment by lifeparticle** [comment]
My pleasure @paulfioravanti, I think it's not done yet! I would like to go for August, if that's not an issue. Thanks!

**Comment by paulfioravanti** [comment]
Not an issue at all! We'll lock you in for August :)

**Comment by paulfioravanti** [comment]
Hey @lifeparticle, just want to confirm a few things now that RORO is on in a few days:

1. You're still good to do your talk
2. I'm a bit uncertain as to what your name/preferred name is, so is it Mahbub Zaman?
3. Do you have a Twitter account? If so, what is it?

**Comment by lifeparticle** [comment]
@paulfioravanti, yes I'm good to do my talk. Mahbub Zaman is fine. I don't have Twitter. Yes please, you can use my LinkedIn photo!

Thanks!

**Comment by paulfioravanti** [comment]
Thanks again, Zaman for your presentation last night! Your slides have now been tweeted out, so I hope you continue to enjoy your Ruby journey!

**Comment by lifeparticle** [comment]
My pleasure Paul, thank you for your time and kind words. Haha sure I'll :)
