### ISSUE TITLE
Exercism Challenge Raindrops

### ISSUE THREAD

**Issue by liuderek97** [rails-oceania/roro#233]
I would like to talk about the exercism challenge Raindrops tomorrow night Tuesday 9th of July at CoderAcademy:

- Intended Audience: all

- Exercism Challenge: Raindrops 

- Twitter Handle: @DerekLi45549491

Thanks for proposing or suggesting a talk for RORO Sydney!

**Comment by paulfioravanti** [comment]
Thanks very much, Derek! You're all locked in for July 9! Just remember, though, the meetup will be at FluidIntel this month (111A Union St, McMahons Point)!

**Comment by paulfioravanti** [comment]
@liuderek97 no photo available of yourself?

**Comment by paulfioravanti** [comment]
Well done last night, @liuderek97! If you have your code up on a [Gist](https://gist.github.com/), or if you have published your solution publicly up on Exercism, please let us know the link by tweeting it out to `@rorosyd` and we'll give it a retweet!
