### ISSUE TITLE
Exploring Houses and Hanami

### ISSUE THREAD

**Issue by RocketRobC** [rails-oceania/roro#234]
PropiFind, an Exploration of Houses and Hanami.

Length: Full Length

Target: Anyone interested in a high level overview of the Hanami framework.

Synopsis: This presentation takes a high level overview of the Hanami framework through the eyes of a personal project for helping buy a house. 

When: July 2019

**Comment by paulfioravanti** [comment]
Nice work on Tuesday, Rob! How do you feel about putting a link to your app up on Twitter and the README in place of a link to a slide deck?
