### ISSUE TITLE
Help with installing excerism challenge

### ISSUE THREAD

**Issue by Phillip8232** [rails-oceania/roro#236]
### issue
I've been having trouble installing the challenge
when i try to download the exercism challenge using:

> exercism download --exercise=isogram --track=ruby

it says
 zsh: command not found: excerism

i've also tried doing exercism.exe download --exercise=isogram --track=ruby to download it but it doesn't work :c 

### as well as request to do challenge in the next talk
![A](https://user-images.githubusercontent.com/48192707/62089145-3469a000-b2ab-11e9-8a2a-161efa0864b7.png)

Excersim challenge 
i'll be doing the Isogram challenge
it will be aimed to beginners
it will be a lighting talk 
the photo for the talk

**Comment by Phillip8232** [comment]
oh i put 2 photos my bad.

**Comment by paulfioravanti** [comment]
Thanks for volunteering, @Phillip8232 !

As for the installation issue...

> zsh: command not found: excerism

You may have a spelling issue 😉 Copy and paste the command below and see how you go.

`exercism download --exercise=isogram --track=ruby`

**Comment by Phillip8232** [comment]
![problem](https://user-images.githubusercontent.com/48192707/62419761-a0913d00-b6cb-11e9-81dd-4d724694c356.png)

I tried this
![help](https://user-images.githubusercontent.com/48192707/62419748-42fcf080-b6cb-11e9-89f9-859f5fd2f712.png)
but then i get this and im really confused if it has worked or not?
![help2](https://user-images.githubusercontent.com/48192707/62419774-d7675300-b6cb-11e9-8119-67d6347e74f9.png)

**Comment by paulfioravanti** [comment]
After you did that, did you try running: `exercism download --exercise=isogram --track=ruby` again? It looks like you configured things correctly.

**Comment by paulfioravanti** [comment]
@Phillip8232 how did you go? Do you need any more help?

**Comment by paulfioravanti** [comment]
@Phillip8232 do you have a Twitter account? If so, please let me know what it is so we can share it in the slide decks and social media.

**Comment by paulfioravanti** [comment]
Also, what is your full name?

**Comment by Phillip8232** [comment]
i finished the challenge i've gotten it to work but i can't submit the challenge sorry for the late reply

**Comment by Phillip8232** [comment]
[isogram.zip](https://github.com/rails-oceania/roro/files/3490537/isogram.zip)
this was the finshed isogram that i could not submit :/

**Comment by Phillip8232** [comment]
oh and my full name is phillip lim

**Comment by paulfioravanti** [comment]
Thanks, Phillip. Do you have a Twitter account?

**Comment by Phillip8232** [comment]
yes it's https://twitter.com/PhilLikes2code

**Comment by paulfioravanti** [comment]
Thanks for your presentation last night, @Phillip8232! You did great! 🎉
