### ISSUE TITLE
Exercism: Armstrong Numbers

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#239]
I will present [my solution to the Exercism Armstrong Numbers problem](https://exercism.io/tracks/ruby/exercises/armstrong-numbers/solutions/bf8a425dd0dc4e738ecc47c8a4484493).

Twitter: [@paulfioravanti](https://twitter.com/paulfioravanti)

**Comment by RocketRobC** [comment]
Looking forward to it!

*Rob Cornish*
----------------------------------------
+61 415 183 555
@: rob@robcornish.net
Twitter: robcornish <http://www.twitter.com/robcornish>
=======================
