### ISSUE TITLE
Rails Rescue - managing technical debt in legacy apps

### ISSUE THREAD

**Issue by tobyhede** [rails-oceania/roro#24]

**Comment by holodigm** [comment]
Oooh the pain! Great topic Toby :+1:  You want to do February?

**Comment by damncabbage** [comment]
I would love to see this. :smile:

**Comment by holodigm** [comment]
Great talk @tobyhede ! Thanks. Have you put this up anywhere yet?

**Comment by mootpointer** [comment]
Shipped!
