### ISSUE TITLE
Debugging rails (A.K.A what to do when 💩 👊 the fan)

### ISSUE THREAD

**Issue by sameera207** [rails-oceania/roro#240]
## Brief summary of the talk content

No matter how good you write your code, bugs are inevitable, this may be due to a change of requirements, some corner case you missed or can be anything. Also, you might be inherited the base code and all of a sudden it became your code now... 

Either way, when a bug comes up, it's always pressed for time, It may be affecting your business and getting a fix is a race against the time. IN 
this talk I'll share a few tips I learned over the years on locating and debugging rails issues

- reading error messages/logs
- debugging techniques (E.g where to start to look at)
- frontend/backend debugging tools
- writing some specs to save time (when the reproduction of the error involves complex steps)
- How to get help online (Good practices on posting in SO)

## Intended audience - 

beginners, intermediates. 

## Which month's meetup you would like to present at
October 2019

## Length of talk: full-length talk 
(15 minutes) 

## Your Twitter username (if you have one)

sameera207 (twitter)

**Comment by paulfioravanti** [comment]
Hey @sameera207 , thanks for speaking last night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
