### ISSUE TITLE
Exercism: Saddle Points

### ISSUE THREAD

**Issue by 2xroygbiv7** [rails-oceania/roro#241]
I am good to present my solution to the Saddle Point Exercism challenge

Patrick Dunn
Twitter: @theonevehicle
0414 909 593

**Comment by mathewdbutton** [comment]
Amazing, thanks so much for volunteering for this Patrick, you're locked in for October 8th. Have you got a photo we can use to put into the slides?

**Comment by 2xroygbiv7** [comment]
Can you use the photo from Twitter?
https://twitter.com/theonevehicle/photo

**Comment by mathewdbutton** [comment]
Ah yes, of course, on it. Thanks again!

**Comment by paulfioravanti** [comment]
Hey @2xroygbiv7 , thanks for speaking last night!

When you have a few moments, could you please put your slides up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.
