### ISSUE TITLE
Teaching Rails: What I Unlearned so my Students could Succeed

### ISSUE THREAD

**Issue by rishter** [rails-oceania/roro#242]
This talk covers principles of teaching programming to absolute beginners, using Rails as a vehicle. We'll discuss why learning to teach is important for every developer, and go through some first principles that I've learned over 2 years of introducing Rails to new programmers. Some elements we'd discuss are:
- Ramping up to complexity
- Using analogies and humor
- How to get students excited (what we call the stoke)
- Tooling
- Some other fun stuff :)

This talk can be appreciated by those at any level, but people who have some familiarity with rails architecture (routing, components, ActiveModel, etc.) will walk away understanding how they might teach Rails as well. It's ideally a 20-30 minute talk, but can be adapted to 15 minutes if necessary. 

I'd love to give this talk at the November meetup, here's a fun photo of me:
![me](https://user-images.githubusercontent.com/552786/66439884-dad8db00-ea7c-11e9-8478-07cd19323fc5.jpg)

**Comment by mathewdbutton** [comment]
Squishy! Thanks for volunteering to give a talk, we really appreciate it. You're locked in for November the 12th, you may also certainly have your 20-30 minutes as well. We're looking forward to it.

**Comment by mathewdbutton** [comment]
@rishter do you have a Twitter account? If so, what is it, so we can put it in the meetup details.

**Comment by mathewdbutton** [comment]
@rishter We've had a wee change of plans with Novembers RORO, it clashes with an event we'd like to go and figure a bunch of the Sydney Ruby community would like to go to it as well. As a result we've postponed November's RORO meetup by a week, [here is the tweet for reference](https://twitter.com/rorosyd/status/1189380669006204928?s=20). So your talk will now be on the 19th of November, I hope that still works for you, but please reach out if it does not.

**Comment by rishter** [comment]
Sounds good! Also, sorry for missing the other comment, I do not have a twitter but I guess people can find me on [LinkedIn](https://www.linkedin.com/in/rhymes-with-squishy/)

**Comment by rishter** [comment]
@mathewdbutton [here's the link](https://docs.google.com/presentation/d/1ME_79AynkDXQUBepO1_s_idx_7LDEVuNeyLXPUNmtPI/edit?usp=sharing) to view my slides!

Please send it over to whatever list y'all have for everyone :)

**Comment by rishter** [comment]
@mathewdbutton @paulfioravanti @RocketRobC would love to hear any feedback you have for me as well!

**Comment by paulfioravanti** [comment]
Thanks for the link, @rishter! Shared! https://twitter.com/rorosyd/status/1196917039610286080
