### ISSUE TITLE
Building a simple app at Rails Girls using Ruby on Rails

### ISSUE THREAD

**Issue by josephine-c** [rails-oceania/roro#245]
Jo (https://github.com/josephine-c & @jytc_) and Jo (https://github.com/Rainbow-Ninja & @CodeTravelled) to present "Building a simple app at Rails Girls using Ruby on Rails"

Intended audience - beginners (probably) or all levels

Which month's meetup you would like to present at: November 2019

Length of talk: Probably lightning talk (5 mins)

**Comment by paulfioravanti** [comment]
Awesome 🎉 ! Thanks so much for submitting a talk @josephine-c and @Rainbow-Ninja! You're locked in for November!

**Comment by mathewdbutton** [comment]
Hey Team JoJo @josephine-c @Rainbow-Ninja! 
Thanks so much for doing your talk last night, you guys did great. Do you have a link to your slides handy, that way I can tweet them out as well as a link to the repo

**Comment by josephine-c** [comment]
There ya go. thanks Mat!
https://docs.google.com/presentation/d/1NLFnwFTuqXzUuvNqjfJza-5wlJAC0fb70j8PzhE_NOk/edit?usp=sharing

**Comment by josephine-c** [comment]
https://github.com/josephine-c/food_puppy
https://github.com/josephine-c/plantme
