### ISSUE TITLE
Simple Cipher Exercism Problem - Nov 2019 

### ISSUE THREAD

**Issue by suwindev19** [rails-oceania/roro#246]
**Simple Cipher Caesar** 

Su Win - by https://github.com/suwindev19 & @Su77491710
-The talk will focus on Exercism.io challenge, "_Implement a simple shift cipher like Caesar and a more secure substitution cipher_."
[https://exercism.io/tracks/ruby/exercises/simple-cipher](url)

Su will explore the following items from from a student's perspective:
1. Simple ciper Caesar concepts
2. Review ruby code
3. Do live demo and share lessons learnt by doing this challenge talk.  

- Intended audience - beginners, intermediates
- Which month's meetup you would like to present at: Thursday 19 November 
- Length of talk: full-length talk (15 minute)

**Comment by mathewdbutton** [comment]
🎉 Thanks @suwindev19! you are booked in for November!

**Comment by paulfioravanti** [comment]
Hey @suwindev19, do you have a favourite profile pic of yourself that we can add to the RORO slide deck to introduce you?

**Comment by mathewdbutton** [comment]
Hey @suwindev19 ! 
Thanks so much for doing your talk last night, it seemed like you really learnt a lot and it was really great to see. Do you have a link to your slides somewhere so we can share them on twitter and add the link to our November slides.

**Comment by suwindev19** [comment]
Hi Matthew,
I am really sorry about my late reply. I am relatively new to github account and didn't see your messages until now. I have definitely learnt a lot! Thank you for giving me the time slot.  I have attached the powerpoint slides. 

Thanks again. 
Su

[20191119_SimpleCipher_RoRoSydney.pdf](https://github.com/rails-oceania/roro/files/3883285/20191119_SimpleCipher_RoRoSydney.pdf)

**Comment by paulfioravanti** [comment]
@suwindev19 Would it be possible for you be able to put your slides up on a slide-sharing site like [SpeakerDeck](https://speakerdeck.com/) or [SlideShare](https://www.slideshare.net/), and then tweet out a link to them at `@rorosyd`? That way, we can get your deck as much exposure as possible :)

**Comment by suwindev19** [comment]
Thanks Paul for letting me know. :) I will upload the slides and share with rorosyd.
