### ISSUE TITLE
Rails Layout/Template Inheritance - March 2020

### ISSUE THREAD

**Issue by tian-im** [rails-oceania/roro#248]
- Topic: How to organize layouts and their partials in Layout/Template Inheritance fashion
- Intended audience - intermediates who know about Rails layout and rendering
- Which month's meetup you would like to present at: Nov 2019
- Length of talk: full-length talk (15-20mins)
- Your Twitter username: @tian_im
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: https://slides.com/tian-im/rails-layout-template-inheritance/edit

**Comment by paulfioravanti** [comment]
Thanks for the submission, @tian-im ! Would you mind doing your talk at the December meetup? If you're already prepared, then perhaps you can be a backup in case we get a sudden cancellation.

**Comment by tian-im** [comment]
Can't do Dec, I will be away in the early Dec. Yeah, I can be the backup

**Comment by paulfioravanti** [comment]
Since you won't be around for February, perhaps we can do your talk in March or April 2020?

**Comment by tian-im** [comment]
Yep, sounds good, let's make it March 2020

**Comment by mathewdbutton** [comment]
Hey @tian-im just checking to see if you're still okay to do this? or would you like to push it to another month? it's no trouble. I realise we scheduled this a while ago now and I forgot to follow up.

**Comment by tian-im** [comment]
Yep, I will do it

**Comment by hhemanth** [comment]
Hey @tian-im , thanks for speaking Tuesday night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

Thanks

**Comment by tian-im** [comment]
Done, I will put the link here as well just in case:

https://slides.com/tian-im/rails-layout-template-inheritance
