### ISSUE TITLE
Exercism Challenge - Meetup

### ISSUE THREAD

**Issue by NicFisher** [rails-oceania/roro#249]
Hey! I would like to complete next months exercism challenge and give a quick presentation on it. I believe its the [Meetup](https://exercism.io/my/solutions/a5a9c9930bd54a2ab44e9e9ccbc7e22d) challenge?

- Name of talk: Exercism Challenge - [Meetup](https://exercism.io/my/solutions/a5a9c9930bd54a2ab44e9e9ccbc7e22d).
- Which month's meetup you would like to present at: December
- Length of talk: 5 minutes
- Your Twitter username: Don't have one

![image](https://user-images.githubusercontent.com/19625093/69311547-a9108200-0c80-11ea-8d8e-0499a67e64e9.png)

**Comment by mathewdbutton** [comment]
Hey @NicFisher 

I've just double checked and yeah it's called meetup.

Thanks so much for volunteering. You're locked in for December 10th.

**Comment by mathewdbutton** [comment]
Thanks for speaking last night Nic, you really checked that one off the list. Now it's time for a full on presentation in 2020!!! I'll chat to socks and make it happen! 😉
