### ISSUE TITLE
Mentorship

### ISSUE THREAD

**Issue by lengarvey** [rails-oceania/roro#25]
I want to give a quick talk about the importance of mentorship and how it relates to training and hiring. I'll give some quick reasons on why this important and things you can do. I feel it's relevant because we have lots of new people entering our community and industry and we should be supporting them properly.

**Comment by bradly-swart** [comment]
+1

**Comment by holodigm** [comment]
:+1:

**Comment by holodigm** [comment]
Great talk @lengarvey ! Thanks. Did you have a deck for this one?

**Comment by mootpointer** [comment]
Shipped!
