### ISSUE TITLE
Protobufs for beginners by a beginner

### ISSUE THREAD

**Issue by mathewdbutton** [rails-oceania/roro#251]
### Brief summary of the talk content
This talk will talk about what protobufs are and what problems they can solve

### Intended audience 
beginners
### Which month's meetup you would like to present at
December 2019
###  Length of talk: full-length talk (15 minute) or lightning talk (5 minute)
Full-length talk, if you're lucky
### Your Twitter username (if you have one)
@matpushbuttons
### Link to, or upload of, a photo of yourself that will appear in the meetup slide deck
You already got plenty

**Comment by mathewdbutton** [comment]
Well done me for presenting, I did an awesome job, woo me

**Comment by mathewdbutton** [comment]
Here are my slides
https://github.com/mathewdbutton/talks/blob/master/protobufs-for-beginners/protobufs-for-beginners.pdf

**Comment by paulfioravanti** [comment]
Noice. Updated README with that info: https://github.com/rails-oceania/roro/blob/master/2019/12/README.md

**Comment by paulfioravanti** [comment]
Oh, also, tweet the link out from your own Twitter account so ROROSyd can re-tweet it! May as well get all the internet points possible.
