### ISSUE TITLE
Intro to Juptyer Notebooks for Ruby

### ISSUE THREAD

**Issue by rowena-s** [rails-oceania/roro#252]
Talk Content: TBD, this is will be the result of a research/experiment project I am yet to start. Putting this here as an idea for now. If anyone has made something substantial with Jupyter or has tips on how/where to get started, would love to hear about it. Will be a full length talk.
 
Outline for now is:
- What is Jupyter
- Why should you use it/ what is it good for.
- How to get started.
- Talk about what I did with it

**Comment by paulfioravanti** [comment]
Definitely interested in seeing this! I touched Jupyter briefly in an AI course that used Python, and thought the concept was really cool!

**Comment by mathewdbutton** [comment]
Hey @rowena-s I'm just going to 👉 prod you to see how this was coming along.

**Comment by rowena-s** [comment]
It's in my conscious to-do list :) Turns out it's not used much outside of the Python/data science world so still looking for inspiration for a thing to build/demo with it.

**Comment by mathewdbutton** [comment]
Cool, no worries just thought I'd try my luck.

**Comment by rowena-s** [comment]
This has dropped significantly down my list of things to work on so closing it for now. Will re-open if motivation strikes.
