### ISSUE TITLE
An intro to Elixir for Rubyists

### ISSUE THREAD

**Issue by mathewdbutton** [rails-oceania/roro#254]
So I know that both of you have expressed interest in doing a beginner elixir intro at RORO @joshprice and @wiserfirst I was wondering if either of you would be keen to do a wee presentation for us for Feb's RORO?

**Comment by joshprice** [comment]
Sign me up!

**Comment by joshprice** [comment]
I'll be covering Pattern Matching and comparing to Ruby 2.7's experimental pattern matching

**Comment by wiserfirst** [comment]
Great! Thanks @joshprice. I could also do a quick one just covering why Elixir is a good idea if you guys think that could be helpful.

**Comment by paulfioravanti** [comment]
I'm okay with that if you are @mathewdbutton

**Comment by mathewdbutton** [comment]
Hey @wiserfirst thanks for volunteering, but if it's alright we might ask you to do your follow up talk another month as we're getting close to having a full meetup and would like to split up the elixir talks, I hope that's okay.

**Comment by mathewdbutton** [comment]
Hey @joshprice I'm just checking you're still good to present for the meetup on Feb 11th?

**Comment by mathewdbutton** [comment]
Hey @joshprice Thanks for presenting, if you have your slides uploaded anywhere I can share them on twitter.
