### ISSUE TITLE
Gentle introduction to Dreamcast programming with mruby

### ISSUE THREAD

**Issue by yujiyokoo** [rails-oceania/roro#255]
Happy new year!

As briefly discussed in person and on Twitter, I'd like to do a short presentation on mruby programming on Dreamcast. It would cover basic concepts and hopefully include demonstration of running ruby code on Dreamcast.

It is not intended to be too technical but it will require a little programming knowledge.

Contents would cover:
* what is Dreamcast
* what is mruby
* how to build Dreamcast binaries
* how to build mruby binaries for Dreamcast
* how to run the built binary

Proposed Date: 11 February 2020
Length: 15 minutes
Twitter username: @yujiyokoo

Image: I've uploaded one: https://user-images.githubusercontent.com/583965/72875567-e1dbde80-3d37-11ea-96e2-a2a2d3fdbb61.jpeg
Or, use this one: https://pbs.twimg.com/profile_images/1128332488734982144/Mg85KK2L_400x400.jpg

**Comment by mathewdbutton** [comment]
@yujiyokoo you bloody legend! Thanks for doing this, I'm so damn pumped about this talk! You are locked in my friend.

**Comment by yujiyokoo** [comment]
Great! Thanks for the opportunity!

**Comment by mathewdbutton** [comment]
Hey @yujiyokoo I'm just checking you're still good to present for the meetup on Feb 11th?

**Comment by yujiyokoo** [comment]
Hi @mathewdbutton yes! I'll be there unless I or my flight on Tuesday have problems getting there!

**Comment by mathewdbutton** [comment]
Thanks again @yujiyokoo for presenting for us on Tuesday it was great!

**Comment by paulfioravanti** [comment]
Obviously, you can't share your slide deck online, @yujiyokoo, so instead, please send a Dreamcast with your presentation software. You know, just for reference :wink:
