### ISSUE TITLE
'A Message to the Stars', RubyConf AU talk

### ISSUE THREAD

**Issue by damncabbage** [rails-oceania/roro#257]
> In 1977, NASA launched the _Voyager_ probes into space. In addition to the actually important equipment, each spacecraft carried one gold-plated copper phonographic record: our message to the stars. This 'vinyl' record contains greetings, sounds, music, ... _and_ a hundred diagrams and photographs all inscribed on the disc as audio!
>
> In this talk, we're going to play the role of the aliens, and try to understand what they sent.
>
> We'll use Ruby to learn about reading and interpreting audio, making pictures from whatever numbers you want, how to slap together a prototype to get fast feedback, while digging a little bit into the magic of history and space.

... Or a shorter summary:
> In 1977, NASA launched the Voyager probes into space. Each carried a copper ‘vinyl’ record, with music, speech… and 115 images, all inscribed on the disc as audio! In this talk we’ll pretend to be aliens; we’ll use Ruby to read the audio, recreate the images, and learn some space history too. 🚀✨

---

Happy to present this in March, if you'd like. :)

Original talk length was 35 minutes; happy to do it in 30, or painfully lop pieces off to get it down to 25. (This talk isn't viable without major renovation at a shorter length than that, unfortunately.)

Handle: [@damncabbage](https://twitter.com/damncabbage)
Photo: https://user-images.githubusercontent.com/133028/75152130-78972300-575c-11ea-94c2-fda1826a881e.jpeg

**Comment by mathewdbutton** [comment]
Yaaaaahoooo! I'm so pumped for round 2 of this.

**Comment by hhemanth** [comment]
Hey @damncabbage , thanks for speaking last night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

Thanks
