### ISSUE TITLE
Dev Environment on Steroids

### ISSUE THREAD

**Issue by hhemanth** [rails-oceania/roro#259]
Summary of the Talk

**Brief summary of the talk content**
In this talk I am going to share my experience trying to switch from Rubymine to Spacemacs. I will also share some tips and tricks on how to beef up your DEV environment. My aim in this talk is to introduce the audience to the awesome editor [Spacemacs](https://www.spacemacs.org/). I want to share tips and tricks so that you can try Spacemacs. Though Spacemacs is built on emacs and it can be intimidating at first, it can be simple to learn and use if you get the right guidance. The purpose of this talk is to provide that impetus. 

- Which month's meetup : **April**
- Length of talk: **30 mins**
- Your Twitter username : **@hhemanth**
- Link to my photo - https://drive.google.com/file/d/1_ujHrzW3d0fGl0R6yDlOBl3Y8uRIsuip/view?usp=sharing

**Comment by mathewdbutton** [comment]
Yahoooo! thanks @hhemanth you're locked in for March.

**Comment by mathewdbutton** [comment]
Well take this out of March as we're full and add it to another month :)
