### ISSUE TITLE
Where Rails Magic Goes Wrong

### ISSUE THREAD

**Issue by FluffyJack** [rails-oceania/roro#26]
Subtitle: How we're pissing off beginners and how we end up frustrated teaching them

**Comment by FluffyJack** [comment]
* Why I hate blog posts by senior developers
* Does Rails have bad UX?

**Comment by holodigm** [comment]
This sounds interesting Jack :+1:  How does March sound?

**Comment by FluffyJack** [comment]
I'll start making the slides and finding gifs :)

**Comment by FluffyJack** [comment]
I only just realised I'll be teaching every Tuesday night for the next three months, I won't even be able to come along :( maybe some time in the future.

**Comment by holodigm** [comment]
Thanks Jack, we'll keep it on the back burner :+1:

**Comment by mootpointer** [comment]
So jack... How does June sound for you?

**Comment by FluffyJack** [comment]
Sounds like a plan, my grand entrance back into not working when RORO is on :D

**Comment by mootpointer** [comment]
Just so you know, we’ll probably be shifting the date, since the usually scheduled rorosyd would be the day after rails camp.

**Comment by FluffyJack** [comment]
As long as it's not Monday or Wednesday night that's fine :)

**Comment by holodigm** [comment]
Hi Jack, still good for June 9th?

**Comment by FluffyJack** [comment]
Yeah lets do it @holodigm! :)

**Comment by holodigm** [comment]
Nice! :+1:

**Comment by FluffyJack** [comment]
Ah! @holodigm I stuffed up! My class was moved because of the public holiday! I'm an awful person and have to ask to delay this one again :'( And the email and stuff has been sent out! I'm so sorry!

**Comment by holodigm** [comment]
No worries Jack, maybe next month?

**Comment by holodigm** [comment]
@FluffyJack  Are we good for July?

**Comment by FluffyJack** [comment]
For real this time yes haha

**Comment by holodigm** [comment]
Awesome :+1: See you then :)

**Comment by holodigm** [comment]
Thanks Jack, look forward to seeing you again soon! :+1: Shipped
