### ISSUE TITLE
Build a neural network from zero with pure ruby, by Enrique

### ISSUE THREAD

**Issue by enriquesalceda** [rails-oceania/roro#260]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk
**Build a neural network from zero with pure ruby**

- Brief summary of the talk content
**Explain simply how a neural network works, and how to implement an easy neural network with ruby that will work**

- Which month's meetup you would like to present at
**March at Shippit**

- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
**15 mins**

- Your Twitter username (if you have one)
enriquesalceda

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
<img width="401" alt="Screen Shot 2020-03-06 at 3 05 40 pm" src="https://user-images.githubusercontent.com/5007193/76050575-f7d9f180-5fbb-11ea-97ba-b2f89a21cfea.png">

**Comment by mathewdbutton** [comment]
🎉 You're locked in for March 10th!

**Comment by cyclotron3k** [comment]
Great talk!

**Comment by hhemanth** [comment]
Hey @enriquesalceda , thanks for speaking on Tuesday night!

When you have a few moments, could you please export your slides to PDF and put them up on the slide-sharing platform of your choice (Slideshare, SpeakerDeck etc) and tweet the slides link out to `@rorosyd`, and we'll give it a retweet.

Thanks
