### ISSUE TITLE
What's new in Sonic Pi V3.2

### ISSUE THREAD

**Issue by rowena-s** [rails-oceania/roro#262]
Thanks for proposing a lightning talk for RORO Sydney!

 New features of the latest version of Sonic Pi - new visualisations and more accessible UI.
 Preferably present in ~~April~~ whenever it's safe to have large public gatherings again :)
Copy Image from March's slides :)

**Comment by mathewdbutton** [comment]
Hey @rowena-s 
I hope the self isolation is treating you well, we're looking to try and do the next RORO virtually, and we wanted to know if you'd be interested in joining in on this experimental ROROSyd?

**Comment by rowena-s** [comment]
Sure! I can help you test it out 🐹

**Comment by mathewdbutton** [comment]
Brilliant, you can be our guinea pig!

**Comment by rowena-s** [comment]
I've got an update profile pic for ya! 😄 

https://drive.google.com/file/d/1_mIqpXlONdUkwLmR21vXLMZv0SLYcQL2/view?usp=sharing

**Comment by mathewdbutton** [comment]
Hey @rowena-s 

Are you around Thursday evening (April 9th) around 8pm for a wee test drive of the virtual meetup, it's using zoom ( I know, I know ) do you think you'll be free ?

**Comment by rowena-s** [comment]
yep, I can make myself available if it's for 10-15 mins.
