### ISSUE TITLE
Exercism challenge: Nucleotide count 

### ISSUE THREAD

**Issue by hirengondhiya** [rails-oceania/roro#266]
- Name of talk 
      Exercism challenge: Nucleotide count
- Brief summary of the talk content
     Walk through the challenge requirements and the solution
- Which month's meetup you would like to present at
May 2020
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by mathewdbutton** [comment]
Woooh! thanks @hirengondhiya for volunteering for the exercism.

Do you have a photo you'd like us to use in the slides to introduce you?

**Comment by hirengondhiya** [comment]
Hey Mathew,
Thanks for asking.
My photo can be downloaded from 
https://hirengondhiya.github.io/src/assets/profile-image.jpg

Thanks,
Hiren

**Comment by mathewdbutton** [comment]
great! thanks @hirengondhiya, thought I'd just check.

**Comment by mathewdbutton** [comment]
Hey @hirengondhiya, 
Just checking to make sure you're still okay to present your solution to the Nucleotide Count exercism for next Tuesday (May 11th).

**Comment by mathewdbutton** [comment]
Well done @hirengondhiya!
