### ISSUE TITLE
Get your team up to speed on <whatever you like> with this One, Simple Trick!

### ISSUE THREAD

**Issue by tracymu** [rails-oceania/roro#267]
Come marvel at the amazing experience our dev team had when we pooled our training budget and created our very own conference!

I can do this in June.

This isn't really going to be 15 mins I don't reckon, but it would be a nice mid-wayer, around 10 maybe.

I can take a lot of questions, talk related and personal, to stretch it out :)

you can use this github photo right?

**Comment by mathewdbutton** [comment]
It can be as little or as long as you like. Yeah I can use your GitHub profile.
Thanks, you're locked in for June!

**Comment by mathewdbutton** [comment]
Thanks for speaking @tracymu!
