### ISSUE TITLE
Exercism Challenge: Protein Translation

### ISSUE THREAD

**Issue by r0ss26** [rails-oceania/roro#268]
**Summary:** Walk through my solution to the protein translation exercism challenge.
June 2020

**Comment by mathewdbutton** [comment]
🎉 YEEEEHAAAA! 🎉  Thanks @r0ss26. You're locked in for June 9th!

Do you also have a preferred photo we can use on the slides?

**Comment by r0ss26** [comment]
![DSC_4434_Crop_Small_B W](https://user-images.githubusercontent.com/29884993/83713685-25424400-a66c-11ea-9751-50e908206783.png)

**Comment by mathewdbutton** [comment]
Thanks for having a go @r0ss26 you nailed it

**Comment by r0ss26** [comment]
Thanks :smile:
