### ISSUE TITLE
How to prepare for AWS Solutions Architect Associate certification 

### ISSUE THREAD

**Issue by hhemanth** [rails-oceania/roro#269]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk: How to prepare for AWS Solutions Architect Associate certification 
- Brief summary of the talk content : I will share my experience preparing for AWS How to prepare for AWS Solutions Architect Associate certification exam
- Which month's meetup you would like to present at : June 
- Link to, or upload of, a photo - https://avatars3.githubusercontent.com/u/486803?s=460&u=fa78acd59228fffb2a2d70c79770ea806cbcb9a6&v=4

**Comment by mathewdbutton** [comment]
THANKS!!!!!!
