### ISSUE TITLE
Disentangle a new fangled image mangler

### ISSUE THREAD

**Issue by glasnt** [rails-oceania/roro#27]
Or: How not to use rails, and other stories

**Comment by holodigm** [comment]
:+1:  Love it :) When would you like to do this? March?

**Comment by glasnt** [comment]
Can we make it April?

**Comment by holodigm** [comment]
Done :)

**Comment by holodigm** [comment]
Hi Katie, Are you still down for this talk in  2 weeks? :)




Kym McInerney

technical director - AirService Digital


codes: osrc.dfm.io/holodigm
twitter: @holodigm
skype: kym_mcinerney







—

**Comment by glasnt** [comment]
Of course! I even have my slides ready

**Comment by holodigm** [comment]
Awesome :)





Kym McInerney

technical director - AirService Digital


codes: osrc.dfm.io/holodigm
twitter: @holodigm
skype: kym_mcinerney







—

**Comment by holodigm** [comment]
Great talk Katie :+1:  Love you style :)

**Comment by glasnt** [comment]
Cheers! If I can think of another ruby talk, I'll be back :D
My slides can be found here http://glasnt.com/talks/2015_04_RoroSyd/

I can totally resolve this 'issue'.
