### ISSUE TITLE
Exercism Challenge

### ISSUE THREAD

**Issue by NathansStuff** [rails-oceania/roro#275]
Hi, I just started learning to code at coderacademy and one of the TAs spoke about this roro meetup. I want to give a talk about the exercism challenge (at the October roro).
Thanks, 
Nathan

**Comment by mathewdbutton** [comment]
Thanks for taking on the challenge @NathansStuff! We're excited to hear your solution. Feel free to DM `@rorosyd` or `@matpushbuttons` if you have any questions or if we can help.

Just in case it was missed the exercism challenge is "Binary Search Tree" a classic computer science data structure. 

You my friend are locked in for October 12th

**Comment by NathansStuff** [comment]
Excellent news, thankyou @mathewdbutton ! I look forward to the challenge and will definitely keep you in mind if I need some guidance, thankyou for taking the time. 

I'll see you then

**Comment by mathewdbutton** [comment]
WHOOPS! @NathansStuff Sorry I said October 12th but it's actually October 13th my bad

**Comment by mathewdbutton** [comment]
Hey @NathansStuff do you have a profile photo I can use for my slides on Tuesday. Happy to use the one from Twitter, just checking if you had a preference.

**Comment by NathansStuff** [comment]
Yeah, the twitter one is fine. Just to confirm a few details:
6?
Do I need to show slide deck/link github anything or just present via share screen or similar?

**Comment by mathewdbutton** [comment]
> 6?
I'm assuming you're talking about the meetup time, yeah the "doors" open at 6, we'll have 15 minutes for everyone to get comfy and get started at 6:15pm or there abouts

>  Do I need to show slide deck/link github anything or just present via share screen or similar?
You can do as little or as much as you like, no requirements, most people just run through the problem, that could be literally you showing the readme in your editor, or on some slides and then they walk us through their code, but it's really up to you. We're just interested in your solution and how you found it :)

**Comment by mathewdbutton** [comment]
Thanks for running through your solution @NathansStuff, you cool with me sharing the recording of your presentation?

**Comment by NathansStuff** [comment]
Yeah, no worries at all
