### ISSUE TITLE
Exercism coding challenge

### ISSUE THREAD

**Issue by Finbob12** [rails-oceania/roro#276]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
- Which month's meetup you would like to present at
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

Exercism Coding Challenge

Hi, My name's Fin, I'm currently studying at Coder Academy on the Fast Track course and love coding challenges!
I'd love to do the "matrix" problem for the October meetup. I'd hopefully break down how I solved the problem, also hopefully refactored a better solution and any issues that I came across while doing so.

Thanks,
![Duck](https://user-images.githubusercontent.com/58685757/94493703-9ff12980-0230-11eb-8584-d88203a6d02f.jpg)

**Comment by mathewdbutton** [comment]
Yahoo! thanks @Finbob12 for putting yourself out there. Looking forward to hearing your solution. You're locked in for October 13th. Let me know if there is anything we can do to help

**Comment by mathewdbutton** [comment]
Hey while I remember, do you have a twitter handle? I'll be adding it to our presentation slides is all.

**Comment by Finbob12** [comment]
Hi Matthew, thanks so much for the opportunity to present.
My twitter handle is '@The_Sneaker_Dev'

Looking forward to presenting.

**Comment by Finbob12** [comment]
Update on the coding challenge I'll be doing.
Daniel and I both selected to do the same 'Matrix' challenge so I am swapping to the 'twelve-days' challenge.

Thanks,

**Comment by mathewdbutton** [comment]
Nice one on the talk evening @Finbob12, are you cool with me posting the recording of your talk online?

**Comment by Finbob12** [comment]
Hi Mat, thanks so much for letting us come and present! Yes that is absolutely fine.
