### ISSUE TITLE
Sydney RORO - Exercism Coding Challenge

### ISSUE THREAD

**Issue by waldowred5** [rails-oceania/roro#277]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- - Exercism Challenge (Matrix Problem)
- Brief summary of the talk content
- - Discussing the code behind the solution to the matrix problem
- Which month's meetup you would like to present at
- - October
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by mathewdbutton** [comment]
Great! thanks for volunteering to present your solution @waldowred5. You're locked in for October 13th. Looking forward to seeing your solution. Let us know if we can help at all.

**Comment by mathewdbutton** [comment]
Hey @waldowred5 while I remember, do you have a twitter handle? I'll be adding it to the slides is all. Also just to confirm, is your name Waldow? I can't find your name anywhere.

**Comment by waldowred5** [comment]
Hi @mathewdbutton, 
Twitter handle is '@WaldowTheDev'
Full name is Daniel Waldow for reference, but usually go by Waldow. 
Keen to speak at RORO!

**Comment by mathewdbutton** [comment]
Many thanks for your talk this evening Waldow, are you cool with me posting the recording of your talk online?

**Comment by waldowred5** [comment]
Sure am that would be great. 

Thanks for hosting and the invite this evening!

Cheers,
Daniel
