### ISSUE TITLE
Exercism coding challenge

### ISSUE THREAD

**Issue by jacinyan** [rails-oceania/roro#278]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
- Which month's meetup you would like to present at
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

Hi, my name is Jacin, a student currently studying at Coder Academy too. 

I’d like to give a lightning talk about the Exercism Acronym challenge. I can see some of my fellow students filled the slots for the October meetup, so it'd be great if I could do one in November. 

There should be a brief walk-through of how I break down the problem, hopefully with a neat solution. 

Cheers,
Jacin

**Comment by mathewdbutton** [comment]
@jacinyan Thanks so much for putting yourself out there! We really appreciate it.

We'd love to have you talk, Sure we can lock you in for November 10th no worries. Let me know if you have any questions or if there is anything I can help you with.

**Comment by jacinyan** [comment]
Thank you Matthew, see you all in Nov~~

**Comment by mathewdbutton** [comment]
Hey @jacinyan are you still good to present your solution next Tuesday (Nov 10th

**Comment by jacinyan** [comment]
Oh, sorry for this late reply @mathewdbutton. The workload this term has grown 'exponentially' and I must have missed the push notification or something.   

Yeah, I am still good to go. How would I send you the picture ?

Cheers

**Comment by mathewdbutton** [comment]
No trouble here @jacinyan thanks for still wanting to present your challenge even with so much work on. I can just use your github/twitter photo, or you can upload an image here by clicking on the
> Attach files by dragging & dropping, selecting or pasting them.

Button at the bottom of the comment box
![Screen Shot 2020-11-07 at 3 33 12 pm](https://user-images.githubusercontent.com/1100707/98432031-96e85780-210e-11eb-93f7-45f0ed8c58d9.png)

**Comment by jacinyan** [comment]
Yep, just the GitHub photo then if you guys dont mind~~~~

**Comment by jacinyan** [comment]
@mathewdbutton

**Comment by mathewdbutton** [comment]
@jacinyan, is it alright if I put your solution up on YouTube?

**Comment by jacinyan** [comment]
Sure~~(even though I just presented something very common😂)

**Comment by jacinyan** [comment]
@mathewdbutton
