### ISSUE TITLE
Ruby Pokemon in Terminal

### ISSUE THREAD

**Issue by NathansStuff** [rails-oceania/roro#279]
Shooting for the December Roro, a 15minute talk about developing Pokemon Ruby in Ruby

**Comment by mathewdbutton** [comment]
Sick, thanks Nathan, Looking forward to it, you're locked in for December.

**Comment by hhemanth** [comment]
@NathansStuff You are confirmed for December. Just confirming with you.

**Comment by mathewdbutton** [comment]
@NathansStuff mate, thanks for coming through with highly anticipated talk. I'm gutted I wasn't around to see it, I'll definitely be checking out the recording when it gets uploaded.
