### ISSUE TITLE
EventMachine with ssl/TLS.

### ISSUE THREAD

**Issue by paradisaeidae** [rails-oceania/roro#28]
I have a talk sketched out which steps through the path taken to implement EventMachine with ssl/TLS.
With the recent security foci, TLS is a 'warming' issue.
So too is the rise of nodeJS alleged performance advantages.
With the release of Ruby 2.2, there are performance opportunities.
Some of which have been factored into the recent EventMachine releases.
Do I need more in a description here?

**Comment by holodigm** [comment]
:+1:  Sounds good. Would you like to do this at the March meetup?

**Comment by paradisaeidae** [comment]
Possibly.
How many minutes would I have?

**Comment by holodigm** [comment]
15

**Comment by paradisaeidae** [comment]
Well, as much as I'd like to do the presso, 15 is really too tight for this one.

**Comment by paradisaeidae** [comment]
Hi Kym,
So 15 mins is the 'standard' roro slot now?
If so then to present at all I would have to shuffle it all in there sometime.
So put me down for it. Whichever month suits.

**Comment by holodigm** [comment]
Hi Mark, Yeah,15 mins. I think in a case like this where you want to convey a large amount of info, maybe consolidate to 15 minute talk and then maybe a blog post? Let me know what you think. We have a sponsor for March so turnout should be good.

**Comment by paradisaeidae** [comment]
Ok. It's to be doing.March is ok.                                                                                                                                                                                                                                                                          MarkT                                                                                                                                                                                                                                          From: Kym McInerneySent: Wednesday, 25 February 2015 14:12To: rails-oceania/roroReply To: rails-oceania/roroCc: MarkTSubject: Re: [roro] EventMachine with ssl/TLS. (#28)Hi Mark, Yeah,15 mins. I think in a case like this where you want to convey a large amount of info, maybe consolidate to 15 minute talk and then maybe a blog post? Let me know what you think. We have a sponsor for March so turnout should be good.

—Reply to this email directly or view it on GitHub.

**Comment by paradisaeidae** [comment]
Hi Kym, I'd like to show a cool/hot video as a seque/intro/interlude.
It's around 3mins. Worth turning the sound up.

**Comment by mootpointer** [comment]
I’ll see what I can manage.




A.

**Comment by holodigm** [comment]
Thanks Andrew

**Comment by paradisaeidae** [comment]
Hi Kym, Andrew,
Last time I was there I noticed the free wifi was a bit 'wavvy'.
Usually no issue, my Telstra 4G covers most areas.
But there it seems the 4G does not leak into the back space.
Is there a wired connect 'net possible?

**Comment by mootpointer** [comment]
I wouldn’t bank on it. What specifically do you need a connection for?




A.

**Comment by paradisaeidae** [comment]
Hi,I have a no-net contingency plan.Moving to it.                                                                                                                                                                                                                                                                          MarkT                                                                                                                                                                                                                                          From: Andrew HarveySent: Monday, 2 March 2015 17:35To: rails-oceania/roroReply To: rails-oceania/roroCc: MarkTSubject: Re: [roro] EventMachine with ssl/TLS. (#28)I wouldn’t bank on it. What specifically do you need a connection for?




A.

On Mon, Mar 2, 2015 at 4:40 PM, MarkT <notifications@github.com> wrote:

> Hi Kym, Andrew,
> Last time I was there I noticed the free wifi was a bit 'wavvy'.
> Usually no issue, my Telstra 4G covers most areas.
> But there it seems the 4G does not leak into the back space.
> Is there a wired connect 'net possible?
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/rails-oceania/roro/issues/28#issuecomment-76661303

—Reply to this email directly or view it on GitHub.

**Comment by paradisaeidae** [comment]
Some show-notes:
One liners in context of this evenings yakitty:
#This will be seen with direct calls:
ruby -v -ropenssl -rfiddle -e 'puts Fiddle::Function.new(Fiddle.dlopen(nil)\
["SSLeay_version"], [Fiddle::TYPE_INT], Fiddle::TYPE_VOIDP).call(0)'

#However, ruby itself uses the openssl compiled with itself:
ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION' 

#Not to be confused with the ruby glue library:
ruby -ropenssl -e 'puts OpenSSL::VERSION' 

#This will show the valid ssl_versions
ruby -ropenssl -e 'puts OpenSSL::SSL::SSLContext::METHODS'

#Test for TLSv1_2 context availability
ruby -ropenssl -e 'puts OpenSSL::SSL::SSLContext.new.ssl_version = :TLSv1_2'

**Comment by mootpointer** [comment]
Shipped!
