### ISSUE TITLE
Exercism: Tournament

### ISSUE THREAD

**Issue by samhammond87** [rails-oceania/roro#280]
Hey Mat!

Thanks for hosting on Tuesday, I had a great time!  I'm a fellow Coder Academy student along with Nathan, Fin and Waldow and I was hoping I could put my name down for December or January to solve a Ruby challenge and present it? If there are no spots no worries at all but otherwise let me know what you might need from me!

![SamHammond](https://user-images.githubusercontent.com/69779780/96081231-a0621380-0f04-11eb-8fdb-2d5e30f5ba8c.JPG)

**Comment by samhammond87** [comment]
woooah that's a very large photo of me right in your face! Haha sorry about that.

**Comment by mathewdbutton** [comment]
Hahaha @samhammond87 the profile photo is just the resolution I was looking for! Enormous. Sure thing, you're welcome to pick up the exercism challenge for December (January we have the month of) you could do November's if you wanted to do it earlier, as we've got no takers for the `dart` exercism challenge yet.

**Comment by samhammond87** [comment]
I really appreciate it thanks @mathewdbutton!! I'll stick to the December one if that's ok? I'd rather have the extra time to consolidate my knowledge as I still feel a bit shaky with some things.

**Comment by mathewdbutton** [comment]
No troubles at all, I thought I'd check. I'll drum up a challenge over the weekend for you and we'll go from there. Also if there is anything I can do to help you feel a little less shaky, please do hit me up and I'll help if I can

**Comment by samhammond87** [comment]
Thank you!! I think (and somewhat frustratingly) there's nothing more I can do except practice, practice and more practice.  But i'll always take a resource recommendation if you have any that you think are outstanding!

**Comment by mathewdbutton** [comment]
@samhammond87, you'll be just fine, it just takes time. 

Your exercism challenge should you choose to accept it is "Tournament"
`exercism download --exercise=tournament --track=ruby`

Hop onto Exercism and take a look, this is the challenge I would like you to solve for December. Let me know if you'd like clarification on anything :).

**Comment by hhemanth** [comment]
@samhammond87 You are confirmed for December. Just making sure you are fine for December

**Comment by samhammond87** [comment]
Hi @hhemanth, I confirm and am looking forward to it!

**Comment by mathewdbutton** [comment]
Thanks for speaking @samhammond87! I'm gutted I wasn't able to see your presentation on Tuesday, I heard it went well. Are you okay with us uploading the recording of your presentation to Youtube?

**Comment by samhammond87** [comment]
Thanks for the opportunity! That's fine to upload to youtube.
