### ISSUE TITLE
Darts Exercism

### ISSUE THREAD

**Issue by MikeRogers0** [rails-oceania/roro#282]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- *Name of talk (in the title field):* ✅
- *Brief summary of the talk content:* I'm going to take you through how I solved the Darts Exercism with a a push goal of making some visual representation.
- *Which month's meetup you would like to present at:* November ( On the 10th, 7am for me :D )
- *Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)*: https://twitter.com/mikerogers0

**Comment by mathewdbutton** [comment]
Sweeeeet thanks Mike! You're locked in for November the 10th!

**Comment by mathewdbutton** [comment]
@MikeRogers0, is it alright if I put your solution up on YouTube?

**Comment by MikeRogers0** [comment]
Please do!!! That would be so awesome!
