### ISSUE TITLE
Exercism: Space Age

### ISSUE THREAD

**Issue by bencefulop** [rails-oceania/roro#283]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk:  Exercism presentation (task to be assigned by Mathew B)
- Brief summary of the talk content: TBA
- Which month's meetup you would like to present at: 8th December
- A photo of yourself: https://user-images.githubusercontent.com/67093836/97818177-1b913b00-1cf5-11eb-9d0c-dc6a4f9d5b7b.JPG

**Comment by mathewdbutton** [comment]
Hey @bencefulop finally got around to this.

The challenge I've chosen for you is called "Space Age"
`exercism download --exercise=space-age --track=ruby`

If I can help with anything to let me know.

**Comment by bencefulop** [comment]
Thanks heaps @mathewdbutton. Will work on it for the December meetup!

**Comment by hhemanth** [comment]
@bencefulop  You are confirmed for December. Just making sure you are fine for December

**Comment by bencefulop** [comment]
@hhemanth yes, I'm all set for December. Looking forward to it!

**Comment by mathewdbutton** [comment]
Nice work @bencefulop, thanks for speaking last night. Are you cool if we submit the recording of your presentation to YouTube?

**Comment by bencefulop** [comment]
Thanks @mathewdbutton. Yes absolutely, go ahead!
