### ISSUE TITLE
Lightning Talk: N+1 & Eager loading & Beyond 

### ISSUE THREAD

**Issue by peaonunes** [rails-oceania/roro#284]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk: N+1 & Eager loading & Beyond 
- Brief summary of the talk content: The N+1 problem is one of the most common issues when our applications grow. We will discuss what is that, some ways to prevent it, and going beyond that.
- Which month's meetup you would like to present at: December
- https://twitter.com/peaonunes/photo

This would be a short talk, 5-10min should be enough!

**Comment by mathewdbutton** [comment]
Hey @peaonunes,

Thanks for volunteering to speak! We're unfortunately all booked up for December, the next available date won't be till February (we usually take January off), would you like us to put you down for Feb? (I realise it feels like a lifetime away)

However we're still waiting on confirmation for one person to check if they're still available to speak on the 8th. If we don't hear anything from them we'll certainly let you know.

**Comment by peaonunes** [comment]
> Hey @peaonunes,
> 
> Thanks for volunteering to speak! We're unfortunately all booked up for December, the next available date won't be till February (we usually take January off), would you like us to put you down for Feb? (I realise it feels like a lifetime away)
> 
> However we're still waiting on confirmation for one person to check if they're still available to speak on the 8th. If we don't hear anything from them we'll certainly let you know.

No worries, I def came late to the party this month hahaha 
We can schedule for Feb in the meantime. I might even come up with a different talk until there, so let's keep chatting.

**Comment by mathewdbutton** [comment]
Seems like we're all confirmed for December @peaonunes but if you're still keen we'd love to have you as the first speaker of the year next year in Feb. We'll be in touch so don't worry about a thing.

**Comment by peaonunes** [comment]
> Seems like we're all confirmed for December @peaonunes but if you're still keen we'd love to have you as the first speaker of the year next year in Feb. We'll be in touch so don't worry about a thing.

No worries mate! Let's keep in touch.

**Comment by mathewdbutton** [comment]
Hey @peaonunes, I hope you had a nice break!

I was wondering if you were still interested in presenting on Feb 9th?

**Comment by peaonunes** [comment]
> Hey @peaonunes, I hope you had a nice break!
> 
> I was wondering if you were still interested in presenting on Feb 9th?

Yeah! I think I may need more time though, maybe 15-20min if that's okay 🤔

**Comment by mathewdbutton** [comment]
Of course you can! 20 minutes is fine by us. Great thanks for confirming!

You're locked in as our first speaker on the 9th of Feb!
