### ISSUE TITLE
Tinderellas, Data, & Bar Charts: My adventures down the Tinder rabbit hole

### ISSUE THREAD

**Issue by syrashid** [rails-oceania/roro#285]
- Brief summary of the talk content
An absolute deep dive into analyzing the publicly available data from Tinder's API and using a little bit of ruby magic and some excel to put together an oddly disturbing amount of analysis
- Which month's meetup you would like to present at
As soon as possible, pretty flexible really.  Melbourne Ruby would be appreciated, but given we're all locked at home any really.
- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
~15 min

Below is an article I wrote on it if you're keen on getting a sneak preview
https://syrashid.medium.com/tinderellas-data-bar-charts-my-adventures-down-the-tinder-rabbit-hole-9bf540d796a7

**Comment by syrashid** [comment]
Absolutely no problem at all.  I would love to speak to RORO Sydney.  Is there anything special I'll need to prepare beforehand besides the presentation?

**Comment by mathewdbutton** [comment]
Great! Well @syrashid you're locked in for Tues Feb 9th. Thanks so much.

Just a few things:
- If you could RSVP to our meetup to make sure you get the zoom link when it goes up
https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/hlnmbsyccdbmb/
- Are you okay with us recording your talk and chucking it up on the RubyAU Youtube channel? (no trouble if you'd rather not)
- Also do you have Twitter, if so what's your handle so we can include you in our tweets
- Lastly are you cool if we use your github profile image for our presentation slides? otherwise is there a preferred image you'd like to use?

**Comment by syrashid** [comment]
Just RSVPd
Absolutely fine with recording, I was going to ask you if I could if you weren't already
No twitter unfortunately
And of course for the photo, no worries at all.  

Thank you, super excited for the opportunity and can't wait to meet your little tribe in Sydney!

**Comment by mathewdbutton** [comment]
> No twitter unfortunately
No trouble at all

Brilliant we're pumped to have you speak as well and looking forward to meeting you virtually!

**Comment by syrashid** [comment]
@mathewdbutton Hey Mathew I noticed the talks had been uploaded besides the tinder one :(  I assume it had something to do with it being inappropriate for RORO Sydney?  If so at the very least would it be possible for me to get a copy of the recording for my own use?

Sy

**Comment by mathewdbutton** [comment]
Hey @syrashid, yeah RubyAU determined that the talk didn't align with their code of conduct and asked me not to upload your video to their YouTube channel. I'll have some time this weekend to upload it to google drive or something and then share the link here.

**Comment by syrashid** [comment]
Hey @mathewdbutton just checking in.  One thing I was wondering, so I can make the presentation more inclusive in the future and potentially not offensive, is what areas of the presentation did RubyAU have an issue with?  I'd rather know now and remove/rework those sections before presenting again and seriously offending someone in the future.  Thank you so much for your support and hope you're having a wonderful holiday weekend!

**Comment by mathewdbutton** [comment]
Hey @syrashid,
I've sent you an email with the URL to download your talk, hopefully it works okay.
