### ISSUE TITLE
What is Crystalball

### ISSUE THREAD

**Issue by langsharpe** [rails-oceania/roro#287]
We've been using this and having some success. Would like to share more broadly what it is and how it works.

It's a "Regression Test Selection library for RSpec". It picks a subset of your tests to run based on which files you have changed. It's useful for test suites that take a long time to run.

- March 2021
- Photo: https://photos.app.goo.gl/s4SHbrGejNZSKN4r6
- https://github.com/toptal/crystalball

**Comment by mathewdbutton** [comment]
My apologies for the late reply @langsharpe.

This sounds great, We'd love to have you present. Thank you so much!

You're locked in for March 9th!

**Comment by mathewdbutton** [comment]
I'm a little behind schedule here, but thank you again for speaking @langsharpe, I'm just double checking you're cool with us posting your talk to Youtube (I really need to add this to the issue template)

**Comment by langsharpe** [comment]
Yes. Please post 👍🏻

**Comment by mathewdbutton** [comment]
thanks @langsharpe
