### ISSUE TITLE
I wanted to do A quick pitch of my business to potential developers

### ISSUE THREAD

**Issue by Lee1984** [rails-oceania/roro#288]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Quick pitch
- Just introduce my business and anyone who wants to help on the code
- march

**Comment by mathewdbutton** [comment]
Hey @Lee1984

Thanks for creating an issue however the presentations and lightning talks are really only for knowledge sharing if you're looking for developers we have a "Who's Hiring" section at the end of the meetup where people looking for work and people offering work can give a short summary of what they're looking for.

**Comment by Lee1984** [comment]
Awesome

Sent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
