### ISSUE TITLE
Exercism: Linked List

### ISSUE THREAD

**Issue by sugendran** [rails-oceania/roro#289]
Depending on what time the exercism section is I might be able to show it - ideally the earlier the better.

Wasn't entirely sure what API was expected, so I did the following:

```ruby
class Element
  attr_reader :value
  attr_reader :next_element

  def initialize(value, next_element = nil)
    @value = value
    @next_element = next_element
  end
end

class List
  include Enumerable

  def initialize
    @head = nil
  end

  def peek
    @head.nil? ? nil : @head.value
  end

  def push(value)
    element = Element.new value, @head
    @head = element
    self
  end

  def pop
    popped = @head
    @head = popped.next_element
    popped.value
  end

  def each(&block)
    elem = @head
    while elem
      block.call(elem.value)
      elem = elem.next_element
    end
  end
end
```

and some tests, which could do with a tidy:

```ruby
require "rspec"
require "linked_list"

describe Element do
  context "next element" do
    it "initialised with nil by default" do
      element = Element.new 1
      expect(element.next_element).to eql(nil)
    end

    it "will point to next element" do
      second_element = Element.new 2
      element = Element.new 1, second_element
      expect(element.next_element).to eql(second_element)
    end
  end
  context "value" do
    it "returns the value, duh!" do
      element = Element.new 1
      expect(element.value).to eql(1)
    end
  end
end

describe List do
  context "mutation" do
    it ".push" do
      list = List.new
      list.push 1
      expect(list.peek).to eql(1)
      list.push 2
      expect(list.peek).to eql(2)
    end
    it ".pop" do
      list = List.new
      list.push(1).push(2)
      popped = list.pop
      expect(list.peek).to eql(1)
      expect(popped).to eql(2)
    end
  end
  context "enumerable" do
    it ".each" do
      list = List.new
      list.push(1).push(2).push(3)
      collector = []
      list.each do |val|
        collector.push(val)
      end
      expect(collector).to contain_exactly(1, 2, 3)
    end
    it ".sum" do
      list = List.new
      list.push(1).push(2).push(3)
      expect(list.sum).to eql(6)
    end
  end
end
```

**Comment by mathewdbutton** [comment]
Hey @sugendran, Sorry for the late reply. Thanks for working on the exercism challenge for March.

We can certainly bump you to the front of the queue for presenting 👍 no trouble at all.

You've done a great job whipping this up! Normally one signs up for an exercism account and works through the challenge that's provided there. They give you the test cases which give you an indication of the API and you just fill in the blanks. However you've done this without any of their hints, so you definitely get bonus points.

This my fault for the mis-communication, I didn't explain it very well on twitter. However I don't think that should matter as it would still be great for you to showcase your solution and explain a little bit about a linked list and how it works.

**Comment by mathewdbutton** [comment]
Thanks so much for offering to share your solution @sugendran. I just wanted to check if you're okay with us posting your solution on our Youtube channel

**Comment by sugendran** [comment]
sorry, forgot to get back to you. Happy for it to be shared.

**Comment by mathewdbutton** [comment]
Thanks @sugendran
