### ISSUE TITLE
Lightning Talk: Debugging ruby network requests with chrome devtools

### ISSUE THREAD

**Issue by gingermusketeer** [rails-oceania/roro#29]
In the age of APIs and microservices seeing what is happening over the network is going to be a massive time saver. This talk is going to demo using [ruby_inspector](https://github.com/gingermusketeer/ruby_inspector) to gain visibility over what your app is doing

**Comment by holodigm** [comment]
Brilliant, thanks Max :+1:

**Comment by mootpointer** [comment]
@gingermusketeer Are you still good to do this this month?

**Comment by gingermusketeer** [comment]
@mootpointer Yep

I will make sure that my talk does not rely on the internet this time :)

**Comment by holodigm** [comment]
:+1:  Good practice for http://railscamp-sydney-2015.ruby.org.au/ :smile:

**Comment by gingermusketeer** [comment]
@holodigm haha yea.

:( I wont be able to make it...

**Comment by holodigm** [comment]
:'(

**Comment by holodigm** [comment]
Thanks Mark :+1:
