### ISSUE TITLE
Github Actions &  Rails

### ISSUE THREAD

**Issue by hhemanth** [rails-oceania/roro#290]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk : Github Actions &  Rails
- Brief summary of the talk content : How to use Guthub Actions  for your Rails Apps
- Which month's meetup you would like to present at : April 21

Twitter @hhemanth

**Comment by mathewdbutton** [comment]
THANKS HEMANTH!
