### ISSUE TITLE
Docker for Developer Happiness

### ISSUE THREAD

**Issue by MikeRogers0** [rails-oceania/roro#291]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field) [X]
- Brief summary of the talk content:

Docker allowed me to extract lots of my apps complexity by reducing the amount of dependencies I had to install. I want to share information about how to get up & going, with enough working knowledge to have fun :D

- Which month's meetup you would like to present at:
March

- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
~15 minutes

- Your Twitter username (if you have one): MikeRogers0

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by mathewdbutton** [comment]
Thanks @MikeRogers0 you're my hero as usual
![swoon](https://user-images.githubusercontent.com/1100707/110308200-f2dad280-8053-11eb-883a-eabf613f61b0.gif)
