### ISSUE TITLE
Seeding Data In Ruby On Rails

### ISSUE THREAD

**Issue by MikeRogers0** [rails-oceania/roro#293]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content: "A good `seeds.rb`, helps every app grow. Let's go through the techniques for seeding so you'll actually want to do it." - https://talks.mikerogers.io/seeding-data-in-ruby-on-rails/
- Which month's meetup you would like to present at: April
- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!): 15 minutes
- Your Twitter username (if you have one): MikeRogers0
- Are you happy to have your talk published on the RubyAU YouTube channel?: Yes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts): See Twitter :)

**Comment by mathewdbutton** [comment]
YEEEHAAA!

**Comment by mathewdbutton** [comment]
As per usual thanks for speaking mate, especially on such short notice

**Comment by MikeRogers0** [comment]
@mathewdbutton Happy to mate! The Ruby AU crowd is always so lovely & supportive, it's always a pleasure :)
