### ISSUE TITLE
Introduction to mutation testing

### ISSUE THREAD

**Issue by HashNotAdam** [rails-oceania/roro#294]
- What mutation testing?
- Introduce the mutant gem
- How does mutation testing make your code better?
- Discuss the ways in which mutant modifies your code in search of gaps in your tests
----
- Length: Happy to stick to 15 minutes
- Twitter: [HashNotAdam](https://twitter.com/HashNotAdam)
- Happy to have your talk published?: Sure thing
- [Link to a photo of yourself](https://www.dropbox.com/s/q0c9bgfzuy290b2/IMG_1510.JPG?dl=0)

**Comment by mathewdbutton** [comment]
Thanks @HashNotAdam, you're locked in for our June Meetup 🎉
