### ISSUE TITLE
Making the most of the current developer job market - whether you're job searching or not 

### ISSUE THREAD

**Issue by debbieteakle** [rails-oceania/roro#295]
**Making the most of the current developer job market - whether you're job searching or not** 
The developer job market has seen some ups and downs (or more accurately, downs and ups) in the last year and a half. I’ll be talking about what’s happening now and what that means for you whether you are job searching or not.
- June 2021
- 15 min
- Twitter [@debteakle](https://twitter.com/DebTeakle) and [LinkedIn](https://www.linkedin.com/in/debbieteakle/)
- Happy to have your talk published on the RubyAU YouTube channel? Yeppers
- [profile pic](https://avatars.githubusercontent.com/u/1418916?v=4)

**Comment by mathewdbutton** [comment]
Thanks @debbieteakle You're the best. You are all locked in for our June meetup
