### ISSUE TITLE
JWTs, what ruby developers need to know

### ISSUE THREAD

**Issue by mooreds** [rails-oceania/roro#296]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Title: JWTs, what ruby developers need to know
- Summary: 

JSON Web Tokens (JWTs) are portable, stateless identifiers. They are often used to control access to APIs, but can be used in other contexts as well. The problem they solve is how to share identity details in a scalable, secure way.

In this talk, I’ll dive deep into that problem, as well as how JWTs should be used, both in generation and in consumption. I’ll also cover what kind of signing algorithms are available, when you should avoid a JWT and how to revoke them. I’ll also include working code samples showing how to generate or consume JWTs. There are several ruby libraries to generate or consume these; I'll touch on them.

- Which month's meetup you would like to present at: November or Jan
- Length of talk: this is typically a 30 minute talk without code examples. LMK if I should try to chop it to 15.
- Your Twitter username: mooreds
- Are you happy to have your talk published on the RubyAU YouTube channel?: yes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![DMoore1](https://user-images.githubusercontent.com/91825/118893542-d06cfd00-b8bf-11eb-82e1-a1a99c81a158.JPG)

**Comment by mathewdbutton** [comment]
Happy to keep the talk at 30 minutes @mooreds.

You're locked in for November! I think this is officially the most organized we've been for a meetup so far in the future 😆

**Comment by mooreds** [comment]
haha, sounds great!

**Comment by mooreds** [comment]
Yes, still planning on it! Thanks for checking in.

**Comment by mathewdbutton** [comment]
@mooreds MUSIC TO MY EARS 🎶 👂. It looks like it'll be on the 9th of November (it's the second Tuesday of every Month) 6pm AEDT (Sydney Time).

**Comment by mooreds** [comment]
Great. I double checked my calendar, and am looking forward to it. Please provide the zoom/video chat link whenever is convenient.

**Comment by mathewdbutton** [comment]
Hey @mooreds,
Here's the [video chat link](https://us02web.zoom.us/j/84834916944?pwd=SWlQOGJsbEZwNkNwVVk4Q25WaVNRZz09) for the meetup this week. You can find more details [here](https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/bwxdqsyccpbmb/)

Tuesday, November 9, 2021
6:00 PM to 8:15 PM AEDT

Talks usually start at 6:20 (we do 15 minutes of chitchat if we can manage it and then I do a little spiel before we get into talks). 

Let me know if you have any questions

**Comment by mooreds** [comment]
I'm good, see you then.

**Comment by mathewdbutton** [comment]
Thank you again for your time @mooreds that presentation was fantastic!

I'll post on twitter when the recording is out.

**Comment by mooreds** [comment]
thanks for having me!
