### ISSUE TITLE
Finding and avoiding Vulns in Ruby - Talk placeholder 

### ISSUE THREAD

**Issue by developersteve** [rails-oceania/roro#299]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
- Which month's meetup you would like to present at
- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
- Your Twitter username (if you have one)
- Are you happy to have your talk published on the RubyAU YouTube channel?
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by mathewdbutton** [comment]
@developersteve just another bump if you're still interested in doing this

**Comment by developersteve** [comment]
@mathewdbutton yup totally am, let me put something together

**Comment by mathewdbutton** [comment]
Sweet! that'd be great @developersteve. Let me know if I can help with anything!

**Comment by mathewdbutton** [comment]
@developersteve bump!

**Comment by developersteve** [comment]
Apologies @mathewdbutton, just recently changed companies and still gearing up to do some pressos. Ill check in with some security folks and see if they are keen.

**Comment by mathewdbutton** [comment]
No trouble @developersteve thanks for getting back to me. I appreciate it.
