### ISSUE TITLE
The Full Monty Hall - My Bad Livecoding Skills Exposed

### ISSUE THREAD

**Issue by freshtonic** [rails-oceania/roro#30]
[The Monty Hall Problem](https://en.wikipedia.org/wiki/Monty_Hall_problem) is the name of a mind bending probability problem that flies in the face of common sense intuition.

I'll attempt to live code a simulation to prove that everyone's common sense sucks ;)

But hey, livecoding!  I'll fail to write even the most basic Ruby live and you can all have a jolly entertaining good laugh.

**Comment by holodigm** [comment]
Nice :+1:

**Comment by mootpointer** [comment]
Shipped!

**Comment by mondaydreaming** [comment]
This was an awesome presentation @freshtonic !!

**Comment by freshtonic** [comment]
Thanks @mondaydreaming  :)
