### ISSUE TITLE
Action Cable 101

### ISSUE THREAD

**Issue by djs070** [rails-oceania/roro#301]
- Brief summary of the talk content

An introduction to the change from request-response to event-driven web using ActionCable

- Which month's meetup you would like to present at

Open to suggestion

- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)

Approx 10 mins

- Your Twitter username (if you have one)

NA

- Are you happy to have your talk published on the RubyAU YouTube channel?

Yes

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

Will provide :)

**Comment by mathewdbutton** [comment]
Hey @djs070, would you be interesting in presenting in August?

**Comment by djs070** [comment]
Hey @mathewdbutton, I think I can do that! The talk is mostly ready, just finishing a few code demos

**Comment by mathewdbutton** [comment]
@djs070 Sweeet! let us know if that changes at all, otherwise I've got you down for the meetup on Tuesday, August 10th!

Thanks Dan!

**Comment by djs070** [comment]
👍

**Comment by mathewdbutton** [comment]
Thanks @djs070 for the presentation, it was really interesting!

I'll post a link here to the recording when it's up

**Comment by mathewdbutton** [comment]
Here's a link to your recording, thanks again @djs070 

https://youtu.be/XDR9Jf1HEZk
