### ISSUE TITLE
A Rails Journey: From Paramedicine to Surfing Mountains

### ISSUE THREAD

**Issue by nerdi** [rails-oceania/roro#302]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- A talk about my journey into Rails and Software development and the opportunities it has created.
- August
- Doubt it'll go to 15 minutes. I just don't like hearing my own voice for that long. Hope I don't waffle.
- dansolocreative (not much to see here I am afraid)
- Are you happy to have your talk published on the RubyAU YouTube channel? Sure.
![DanProfileSnow](https://user-images.githubusercontent.com/1147027/128117466-39d7ccc9-9623-47ea-bf93-dfdc9870c047.jpeg)

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by mathewdbutton** [comment]
Love it thanks Dan, you're locked in for our August 10th Meetup!

**Comment by mathewdbutton** [comment]
Thank you @nerdi, your talk was great, so damn interesting. I'm definitely looking you up if we ever find ourselves getting to Japan for skiing!

I'll post the video here when it's up and on twitter as well.

**Comment by mathewdbutton** [comment]
Here's a link to your recording! Thanks again @nerdi 
https://youtu.be/rTx51yiirVM
