### ISSUE TITLE
It's dangerous to go alone! Take this.

### ISSUE THREAD

**Issue by aldhsu** [rails-oceania/roro#307]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
  - Finding your way in a codebase that is new to you
- Which month's meetup you would like to present at
  - March 
- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
  - 15 mins
- Your Twitter username (if you have one)
- Are you happy to have your talk published on the RubyAU YouTube channel?
  - Yes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![6347283](https://user-images.githubusercontent.com/6347283/155432248-c0fed631-539b-4201-ba86-bf83bcedb86e.jpeg)

**Comment by mathewdbutton** [comment]
Sorry it took a whole month but now for the moment you've all been waiting for.

https://youtu.be/UsDlzCFVi_U

Thanks again @aldhsu
