### ISSUE TITLE
I'm just curious why markdown is counted

### ISSUE THREAD

**Issue by peterroe** [rails-oceania/roro#309]
I'm just curious why markdown is counted

Can you answer for me?

**Comment by mathewdbutton** [comment]
Hello @peterroe, I'm not sure I understand your question, sorry.

Could you please elaborate? Are you asking if we accept talks about markdown?

**Comment by peterroe** [comment]
I see that your repo counts the markdown language, but my repo does not, for example: https://github.com/peterroe/peterroe.icu

![@$5H_ )QY3ZLYWWM$ Q@ N6](https://user-images.githubusercontent.com/59404696/156481561-d955598e-d8da-4b7e-bd13-0a2045000346.png)
]

**Comment by peterroe** [comment]
> Hello @peterroe, I'm not sure I understand your question, sorry.
> 
> Could you please elaborate? Are you asking if we accept talks about markdown?

Even if there is a `.md` file in my project

**Comment by mathewdbutton** [comment]
Oh right, I wonder if it's because it's such a small percentage of the content of your code base, it's not counted. Where as this repo is almost completely markdown? 🤷 not sure sorry.

**Comment by peterroe** [comment]
I guess not. Most of the files in the repo are markdown files。such as:  [github.com/peterroe/peterroe.icu/tree/master/pages/notes](https://github.com/peterroe/peterroe.icu/tree/master/pages/notes). 

Thank your answer my question again.

**Comment by peterroe** [comment]
> Oh right, I wonder if it's because it's such a small percentage of the content of your code base, it's not counted. Where as this repo is almost completely markdown? 🤷 not sure sorry.

Hey, bro. Finally I find that because of `.gitattributes` file，it's content can control count language types.

**Comment by mathewdbutton** [comment]
Ahhhhh! thank you, the mystery is solved! Glad you figured it out.
