### ISSUE TITLE
Profiling rails apps with the x-ray-machine

### ISSUE THREAD

**Issue by MadRabbit** [rails-oceania/roro#31]
Hey there,

I thought I'll put up my hand for a lighting talk and speak about my [x-ray machine](https://github.com/MadRabbit/x-ray-machine) thing and its usage in profiling rails apps. a short 5 mins slot will be fine.

If i can make it to the March 2015 that would be awesome.

**Comment by MadRabbit** [comment]
not sure how one edits labels on those things, but just in case you're wondering, it's an "intermediate, advanced" kinda thing

**Comment by holodigm** [comment]
Nice one Nic. When would you like to do this one?

**Comment by MadRabbit** [comment]
this roro if that's a possibility

**Comment by holodigm** [comment]
Done, nice one :+1:

**Comment by MadRabbit** [comment]
awesome, thanks!

**Comment by mootpointer** [comment]
Shipped!
