### ISSUE TITLE
Encrypting your radioactive models for security, speed and queryability!

### ISSUE THREAD

**Issue by coderdan** [rails-oceania/roro#310]
- Brief summary of the talk content

Protecting PII in your application using ActiveRecord field encryption is a great idea...but there are some gotchas! The best approaches for security and performance aren't always obvious and searchability virtually vanishes.

In this talk I'll share how to set up ActiveRecord EncryptedRecord in Rails 7, what security considerations to make and some bonus tips including how to encrypt non-string fields. If it's OK, I'd like to mention of my company, [CipherStash](https://cipherstash.com) at the end, but please let me know if this is not appropriate.

We are also happy to sponsor an event if you are looking.

- Which month's meetup you would like to present at

Any month but June.

- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)

I'll keep it to 15mins.

- Your Twitter username (if you have one)

@danieldraper 

- Are you happy to have your talk published on the RubyAU YouTube channel?

Yep!

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

![dan-head](https://user-images.githubusercontent.com/522225/166226449-0a1f695f-9478-4575-888a-1a1d573181ac.jpeg)

**Comment by mathewdbutton** [comment]
Hey @coderdan thanks for submitting an issue, we'd love to have you speak, that topic sounds great!

> Which month's meetup you would like to present at

Does May 31st (the last Tuesday of the month) work? https://www.meetup.com/Ruby-On-Rails-Oceania-Sydney/events/dgmsssydchbpc/

> I'll keep it to 15mins.

I keep forgetting to remove this part, as we don't have as many time constraints since going online. You're welcome to speak for longer if you'd like to, sorry about that.

> If it's OK, I'd like to mention of my company, [CipherStash](https://cipherstash.com/) at the end, but please let me know if this is not appropriate.

Yeah sure if you'd like to mention it at the end that is okay by us.

**Comment by coderdan** [comment]
That sounds great @mathewdbutton!

**Comment by mathewdbutton** [comment]
Amazing you're locked in for our May meetup! I'll start putting the word out! Thanks again @coderdan

**Comment by mathewdbutton** [comment]
Thanks a million for speaking last Tuesday @coderdan, that was a cracking talk.

You're video can be found here https://youtu.be/Hc52LTZx5kI
