### ISSUE TITLE
Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [rails-oceania/roro#311]
The project is currently missing the Code of Conduct which defines standards for how to engage in a community. If you want that then I would like to add a Pull Request with the Code of Conduct. 

Please let me know what you think about that.

**Comment by mathewdbutton** [comment]
Hi @FahimFBA, thanks for reaching out. 

We lean on the code of conduct mentioned at the bottom of the README
https://ruby.org.au/policies/code-of-conduct

So I think we're okay for a code of conduct. While I do agree it could be made more obvious that this applies to the repo as well as our community events.

**Comment by FahimFBA** [comment]
I completely get that. Thanks for pointing that out. I am closing the issue now.

**Comment by mathewdbutton** [comment]
Thanks for taking the time to ask @FahimFBA I really appreciate it
