### ISSUE TITLE
The Multiverse of Madness: How to manage state complexity across multiple databases like a true Sorcerer Supreme....

### ISSUE THREAD

**Issue by tarun-pacifica** [rails-oceania/roro#326]
- Brief summary of the talk content
_"The most common use-case a developer will encounter in Rails is a 1:1 relationship between database & application BUT in the complex world of production environments, an application is often required to manage state across multiple data sources. Between existing and upgraded and old to new databases, offshore & onsite, legacy & current, staging, test and production environments, backups, machine learning, event stores & data lakes, the permutations are endless. Here I share tips & tricks on how to traverse multiple database management like a Sorcerer Supreme..._
- Which month's meetup you would like to present at
_March 2023_
- [Connect via linked in ](https://www.linkedin.com/in/tarunmookhey)
- Are you happy to have your talk published on the RubyAU YouTube channel?
_Yes_
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
https://ga-core.s3.amazonaws.com/production/uploads/instructor/image/1841/thumb_tarun.jpg

**Comment by cheddachedda** [comment]
Hey Tarun, we'd love for you to do this talk tomorrow! Thanks so much for offering on short notice

**Comment by cheddachedda** [comment]
Thanks for stepping in @tarun-pacifica. I'm closing this now

**Comment by Yasmin-A95** [comment]
Hi Tarun, your talk has been uploaded to the Ruby Australia YouTube channel, check it out [here](https://www.youtube.com/watch?v=QZnLmpeXRi0). If you'd like to choose a thumbnail feel free to send one over, perhaps if you still have the slides we could use one of those?
