### ISSUE TITLE
Steno Coding Luhn checksums

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#327]
Thanks for volunteering for to showcase the Exercism challenge at RORO Sydney!

Please provide the following information:

- Name of challenge
  Luhn
- Which month's meetup you would like to present at
  April 2023
- Are you happy to have your talk published on the RubyAU YouTube channel?
  Yes
- Your Twitter username (if you have one)
  [`@paulfioravanti`](https://twitter.com/paulfioravanti)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
  [Photo](https://www.dropbox.com/s/f4alvdvqd2rztwc/Paul.jpg?dl=1)

If possible, I'd like to have a full-length speaker slot.

This talk aims to introduce stenography: shorthand writing that you may have seen used by court reporters and captioners. I'm going to show how steno can be used for coding/Ruby, and then I'm planning to live code the Luhn solution using steno.

**Comment by cheddachedda** [comment]
Woah @paulfioravanti , this sounds super, super interesting! We'd love to give you a full speaker slot for this. - Dan

**Comment by cheddachedda** [comment]
Hey Paul, all good for tonight?

**Comment by paulfioravanti** [comment]
@cheddachedda sure am! I've got some gear set up for my talk, so I'll come along around 5 p.m. to do all that.

**Comment by paulfioravanti** [comment]
@cheddachedda please ping this issue when the video goes up! 🙏

**Comment by Yasmin-A95** [comment]
Hi Paul, thank you so much for your talk. It has been uploaded to the Ruby Australia YouTube channel, check it out [here](https://www.youtube.com/watch?v=3W9_k2CXrXE). Unfortunately the start of the recording was cut off but I uploaded what I could. If you'd like to choose a thumbnail feel free to send one over, perhaps if you still have the slides we could use one of those?

**Comment by paulfioravanti** [comment]
Thanks, @Yasmin-A95! I've just started putting it out on the socials. I didn't actually have a slide deck for this talk, so I guess if you wanted a thumbnail, you could do what I've done in the past, and use the MC slide deck that says the name of the talk and has the speaker's picture on it.

**Comment by Yasmin-A95** [comment]
No worries @paulfioravanti. That's a good idea, cheers :)
