### ISSUE TITLE
Biohacking the developer

### ISSUE THREAD

**Issue by leesheppard** [rails-oceania/roro#328]
- Programming on the right side of the brain, hacking our minds to increase performance and be more productive.
- Which month's meetup you would like to present at = April 11th meetup
- Length of talk = 20 minutes
- Your Twitter username = @leesheppard
- Are you happy to have your talk published on the RubyAU YouTube channel? = yes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts) = (modify the w_ and h_ to scale if needed)  https://res.cloudinary.com/leesheppard/image/upload/c_scale,h_250,w_250/v1679958092/photos/lee_sheppard_profile.jpg

**Comment by cheddachedda** [comment]
Hey Lee, this sounds like a great talk for our April meetup. I'll assign it to you - Dan

**Comment by cheddachedda** [comment]
All good for tonight?

**Comment by leesheppard** [comment]
@cheddachedda I've had something come up this morning and not sure I'll be able to make it tonight.

**Comment by cheddachedda** [comment]
Sorry we missed you, Lee! Hope we can try again next month, or any other month

**Comment by Yasmin-A95** [comment]
Hey Lee, are you interested in giving this presentation for the [upcoming meetup on the 9th of May](https://www.meetup.com/en-AU/ruby-on-rails-oceania-sydney/events/bxdkdtyfchbmb/), we'd love to have you if you're willing.
