### ISSUE TITLE
Railway Oriented Programming - Patterns of functional programming paradigm

### ISSUE THREAD

**Issue by arpanlepcha** [rails-oceania/roro#329]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk : Railway Oriented Programming - Patterns of functional programming paradigm
- Brief summary of the talk content
  Introducing functional programming paradigm in ruby using Railway Oriented Programming and Monads. Examples through the usage of [Deterministic Gem](https://github.com/pzol/deterministic ).
- Which month's meetup you would like to present at
   April / May whichever works
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
  ~ 20 mins
- Your Twitter username (if you have one)
    N/A
- Are you happy to have your talk published on the RubyAU YouTube channel?
  Yes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by dkdam** [comment]
Hey @arpanlepcha , your proposal sounds awesome and we're happy to slot your speech in for April's meet-up this month.

**Comment by cheddachedda** [comment]
Hey @arpanlepcha could we please have your name and a photo so we can put it on our Meetup page and on our slides? Cheers, Dan.

**Comment by arpanlepcha** [comment]
Hey @cheddachedda certainly,
Name: Arpan Lepcha
Photo: https://drive.google.com/file/d/1yc1GfixlANQh8yDePZbyaFQoOx9ci1Fz/view?usp=share_link

**Comment by cheddachedda** [comment]
Thanks Arpan! See you on Tuesday

**Comment by cheddachedda** [comment]
Hey Arpan, all good for tonight?

**Comment by arpanlepcha** [comment]
Hey @cheddachedda , yeah see you today 6.

**Comment by dkdam** [comment]
https://meet.google.com/rju-nqfu-mku
