### ISSUE TITLE
Talk proposal: A (hagiographical) history of object relational mapping

### ISSUE THREAD

**Issue by maetl** [rails-oceania/roro#33]
Actual title TBD.

In 2003, object relational mapping was infamously described as “the Vietnam of computer science”. Then Rails came along. I want to talk about the legacy of object relational mapping in the software industry (good and bad), with special reference to the evolution of ActiveRecord in Rails, and why—in 2015—more and more people are rejecting the ActiveRecord style, in favour of immutable data structures and CQRS.

I intend this talk to be historically accurate, but will include some fairly strong opinions about the social history of software (hence the hagiographical disclaimer). Most of the talk will be appropriate for a beginner to mid-level audience, particularly those with a Rails app or two behind them. There will be a couple of brief excursions into conceptual/architectural heresy that more advanced people will appreciate (hopefully).

**Comment by holodigm** [comment]
Nice :+1:

**Comment by mootpointer** [comment]
Do we have an actual title?

**Comment by maetl** [comment]
### The Rise and Fall of Object-Relational Mapping

**Comment by holodigm** [comment]
:grinning: I kinda liked the proposal title. Thanks Mark

**Comment by holodigm** [comment]
Great talk tonight @maetl :+1:

**Comment by holodigm** [comment]
Hi @maetl. Is this talk available online? A few points I wanted to explore further

**Comment by maetl** [comment]
@holodigm I’m working on a transcript/interpretation of the talk, which will include all the links/references that weren’t mentioned in the slides. Will ping you when that’s available.

**Comment by maetl** [comment]
@holodigm Transcript available here: http://maetl.net/talks/rise-and-fall-of-orm

Get it while it’s :hotsprings:

**Comment by holodigm** [comment]
Brilliant, thanks Mark :+1:
