### ISSUE TITLE
Exercism: [Hamming]

### ISSUE THREAD

**Issue by rodrigonikolof** [rails-oceania/roro#330]
Thanks for volunteering for to showcase the Exercism challenge at RORO Sydney!

Please provide the following information:

- Name of challenge => Hamming
- Which month's meetup you would like to present at => May 23
- Are you happy to have your talk published on the RubyAU YouTube channel? Yes
- Your Twitter username (if you have one) => No Twitter
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts) [Photo](https://media.licdn.com/dms/image/C5603AQGtZN1NZW_VIA/profile-displayphoto-shrink_800_800/0/1579997903623?e=2147483647&v=beta&t=l0cwmYPFNY6utm6dmylKWdND9b48tQdZGVInJIO0cGM)

**Comment by Yasmin-A95** [comment]
Thanks for volunteering @rodrigonikolof, we'd love to give you the exorcism slot for our May 9 meetup. Don't forget to [register](https://www.meetup.com/en-AU/ruby-on-rails-oceania-sydney/events/jpcrctyfchbmb/) if you haven't already, and feel free to reach out to me or any of the other organisers if you need anything at all.

**Comment by rodrigonikolof** [comment]
Awesome @Yasmin-A95. Thanks so much! Looking forward to it 😎

**Comment by cheddachedda** [comment]
Hey Rod, thanks for demoing the exercism last week. Hope to see you at the next one
