### ISSUE TITLE
I would like to show the app I am working on as a recent graduate from General Assembly in March

### ISSUE THREAD

**Issue by loudringphone** [rails-oceania/roro#331]
Hi, I am a recent gradudate from General Assembly in March and I feel that job hunting is stressful; therefore while looking for a job, I am also working on a little project to kill the stress

I just started working on this eCommerce app in April. Although it is not really related to Ruby as I am using React and Firebase for this app, I would like to share my interests in movies and the efforts I have been putting into this project.

If possible, I would like to present in May and I am happy to have my talk published on the YouTube channel.

The link for the app is as below.
https://videostore.netlify.app/

https://www.linkedin.com/in/winston-lau/
https://winstonsportfolio.netlify.app/
Best regards,
Fung

**Comment by Yasmin-A95** [comment]
Hi Fung, thanks for your talk proposal we'd love to have you speak at our [upcoming RORO](https://www.meetup.com/ruby-on-rails-oceania-sydney/events/bxdkdtyfchbmb/) on May 9. Let me or any of the other organisers know if you need anything :)

**Comment by loudringphone** [comment]
Thanks Yasmin! I will go to the app's site to demostrate the app. I just implemented the stripe client and server integration. It is quite challenging but it is rewarding!

**Comment by cheddachedda** [comment]
Hey Fung/Winston thanks for presenting your eCommerce app last week! Hope to see at the next one
