### ISSUE TITLE
Ruby on Rails on Raspberry PI

### ISSUE THREAD

**Issue by johnofsydney** [rails-oceania/roro#334]
I will present Rails running on a Raspberry pi.
I will walk through the code, 
- the gems allowing connection to inputs and outputs
- using cron and rake to make time based requests
How to use relays to switch high current devices
Temperature Sensors
(if god and mable wifi is willing) 
- interactive session using ngrok
- receiving webhooks

- Which month's meetup you would like to present at
- July

- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
- 20 minutes

- Your Twitter username (if you have one)
- No

- Are you happy to have your talk published on the RubyAU YouTube channel?
- Sure

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
- please use the one from Ruby Australia Slack

**Comment by cheddachedda** [comment]
Hey John, this sounds like it'd be a cracking topic. We'd love to lock you in for July 11 if you're still keen.
