### ISSUE TITLE
Developer Productivity and standing out in the current market

### ISSUE THREAD

**Issue by davemcp** [rails-oceania/roro#335]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- [x] Name of talk (in the title field)
- [x] Brief summary of the talk content
- [x] Which month's meetup you would like to present at
- [x] Are you happy to have your talk published on the RubyAU YouTube channel?
- [x] Your Twitter username (if you have one)
- [x] Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Summary:**
As companies reduce their hiring, the productivity of existing teams becomes ever more important, and how can ICs stand out in this current market to hiring managers with reduced headcount growth.
**Monthly meetup:**
July 2023
**Published to RubyAU YT:**
Yep, happy for the talk to be published
**Twitter handle:**
[boymc](https://www.twitter.com/boymc)
**Headshot:**
![dave_small_4](https://github.com/rubyaustralia/roro/assets/121343/0b1fc8b2-e634-4da8-b4c1-487dafae1237)

**Comment by Yasmin-A95** [comment]
Hi @davemcp, thanks for proposing a talk. We'd love to have you at our July 11 meetup. Feel free to reach out to me or any of the other organisers if you need anything, otherwise we'll see you there.
