### ISSUE TITLE
Hanami 2.0 – an alternative to Rails?

### ISSUE THREAD

**Issue by cheddachedda** [rails-oceania/roro#337]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

### Name of talk (in the title field)
Hanami 2.0 – an alternative to Rails?

### Brief summary of the talk content
My early learnings of the Hanami framework and how it differs to Rails
A look at how Hanami handles providers, dependency injection and the repository pattern.

### Which month's meetup you would like to present at
August

### Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
20 mins

### Your Twitter username (if you have one)
www.linkedin.com/in/daniel-nguyen-ror

### Are you happy to have your talk published on the RubyAU YouTube channel?
Yep

### Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
tbd

**Comment by Yasmin-A95** [comment]
Thanks Dan. Here's a link to the youtube video https://youtu.be/PEU2XcnGdlw
