### ISSUE TITLE
A brief history of rails releases

### ISSUE THREAD

**Issue by Coreastreet** [rails-oceania/roro#338]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field): A brief history of rails versions and their accompanying features/updates.
- Brief summary of the talk content: I will go over the different versions of rails releases and the features that each newer version added or removed. This is useful for developers who have to deal with older versions and update business applications to the latest version. Special focus on the replacement of Webpacker by Hotwire. 
- Which month's meetup you would like to present at: August meetup.
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!): 15 - 25 minutes
- Your Twitter username (if you have one): @Coreastreet
- Are you happy to have your talk published on the RubyAU YouTube channel?: Yes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts): 
![image](https://github.com/rubyaustralia/roro/assets/38857013/ca5a244f-c635-4da7-b8a4-fa179fcb9d75)

**Comment by Yasmin-A95** [comment]
Hi Justin, we'd love to have you back as a speaker for our [August meetup](https://www.meetup.com/ruby-on-rails-oceania-sydney/events/291724636/). If you have any questions or need help with anything leading up to the event, feel free to reach out to me or any of the other organisers.

**Comment by Yasmin-A95** [comment]
Can I grab a link to your linkedin to tag you in a post advertising you as a speaker?

**Comment by Coreastreet** [comment]
https://www.linkedin.com/in/justin-ye-software-developer/

**Comment by Coreastreet** [comment]
Hi Roro,

Sorry for the late notice, but I will no longer be giving this presentation due to conflicting scheduled activities.

Regards,
Justin

**Comment by Yasmin-A95** [comment]
Thanks for letting us know @Coreastreet, we'd be happy to have you back some other month if you'd like to present it in a future meetup.
