### ISSUE TITLE
Minimax for Ultimate Tic Tac Toe in Ruby

### ISSUE THREAD

**Issue by loudringphone** [rails-oceania/roro#339]
Hi RORO,

I would like to show my Minimax for Ultimate Tic Tac Toe in Ruby, if you still need a speaker on 8 Aug. I built the game in JS, but for the meetup, I have turned it to ruby! I woud talk about what alpha beta pruning, board evaluation and depth search are!

https://github.com/loudringphone/ultimate-tic-tac-toe-with-minimax-in-ruby

**Comment by Yasmin-A95** [comment]
Hey Winston, we'd love to have you speak tomorrow. Thanks for proposing another talk.

**Comment by Yasmin-A95** [comment]
Hi Winston, thanks again for speaking. Here's a link to your youtube video: https://www.youtube.com/watch?v=ZxOpnW3olfs
