### ISSUE TITLE
Fun with Blocks

### ISSUE THREAD

**Issue by damncabbage** [rails-oceania/roro#34]
Banal subtitle: "What Blocks, Procs and Lambdas Are and What They Are Useful For."

(For the May meetup. `beginner` and `intermediate`, please. The uses may get a little advanced, but I'll keep it accessible to newbies as well if I can at all help it.)

**Comment by holodigm** [comment]
Thanks Rob, when would you like to do this one?

**Comment by holodigm** [comment]
Thanks Rob :+1:

**Comment by mootpointer** [comment]
```ruby
proc do
  return :success
end

```

Shipped.

**Comment by holodigm** [comment]
It sucks I could see this one @damncabbage Do you have it up anywhere?

**Comment by damncabbage** [comment]
@holodigm:
I don't have my little post-it note annotations yet, but the slides are up here: http://robhoward.id.au/talks/2015/05/fun-with-blocks/

**Comment by holodigm** [comment]
Thanks mate :+1:
