### ISSUE TITLE
Ruby Roars (making games with Dragon Ruby)

### ISSUE THREAD

**Issue by aquillo-au** [rails-oceania/roro#340]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Brief summary of the talk content
Quick intro to dragon ruby, showing how it works a small game I'm working on and why developers should consider trying out a dragon ruby project
- Which month's meetup you would like to present at
Oct, Nov or Dec
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
Can either do a lightning talk just with a quick intro to dragon ruby or a 18 minute one showing some apps built with some of the differences in design choices when coding for games rather than web.

- Your Twitter username (if you have one)
N/A
- Are you happy to have your talk published on the RubyAU YouTube channel?
Yep

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![349327133_260933046441366_329088861869289564_n](https://github.com/rubyaustralia/roro/assets/40282417/c975ab3e-03a4-41c3-9249-da78fceba624)

**Comment by Yasmin-A95** [comment]
Hey Ben, we'd be glad to have you back for our [October 10](https://www.meetup.com/ruby-on-rails-oceania-sydney/events/rzbrgtyfcnbnb/) meetup. As always reach out to me or any of the other organisers if you need anything
