### ISSUE TITLE
Entrepreneurship talk: Starting an EdTech caompany to teach Ruby

### ISSUE THREAD

**Issue by MatBnc** [rails-oceania/roro#341]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content: Overview of what an EdTech company does and how build one from 0 to 1. Going through the steps and multiple workstreams needed to start a company for anyone potentially interested in launching their business.
- Which month's meetup you would like to present at: October 10th
- Length of talk: 10-15 min
- Your Twitter username: n/a
- Are you happy to have your talk published on the RubyAU YouTube channel?: sure!
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: 
<img width="552" alt="Screenshot 2023-08-28 at 14 23 40" src="https://github.com/rubyaustralia/roro/assets/108807159/5632a09a-4864-4e26-80d5-7292e3be233c">

**Comment by Yasmin-A95** [comment]
Hey Matt, we'd love to have you speak at either our [September 12th](https://www.meetup.com/ruby-on-rails-oceania-sydney/events/295191185/) or [October 10th](https://www.meetup.com/ruby-on-rails-oceania-sydney/events/rzbrgtyfcnbnb/) meetup. 

I know we discussed having your talk in October, but one of our September speakers fell through so if you're still available for our September event we'd be glad to have you. Let me know what would suit you, and as always feel free to reach out to me or any of the other organisers if you need anything.

**Comment by MatBnc** [comment]
Hey there,

I have two very busy weeks ahead, so I wouldn't have time to prepare something custom made;

However, this is shortened version of a lecture I gave at the University of Sydney on entrepreneurship and how to build an international company teaching code (Ruby!) in just a few years.

If you like the content and story I have to tell (you can read it in the presentation notes) - and don't think it's too much "selling something", which I believe it isn't - then happy to have a 10 min speaking time in September :)

Here are the slides ( https://docs.google.com/presentation/d/1mD8cURDcpKu_DAqqbWwm6vBZqOJI5kMwUPq3TvqBVK0/edit?usp=sharing )

Let me know,

Cheers,

Matteo

Matteo Bianchi
Founder @ Le Wagon Sydney ( https://www.lewagon.com/sydney )
+61 466 428 893

Rated 4.98/5 by 20k+ graduates
Switchup ( https://www.switchup.org/bootcamps/le-wagon ) | Coursereport ( https://www.coursereport.com/schools/le-wagon#/reviews )

Sent via Superhuman ( ***@***.*** )

**Comment by MatBnc** [comment]
Hey there,

As I haven't heard back on this topic, I'll have to sit this one out for September - let's keep in touch for the October one :)

Cheers

Matteo

Matteo Bianchi
Founder @ Le Wagon Sydney ( https://www.lewagon.com/sydney )
+61 466 428 893

Rated 4.98/5 by 20k+ graduates
Switchup ( https://www.switchup.org/bootcamps/le-wagon ) | Coursereport ( https://www.coursereport.com/schools/le-wagon#/reviews )

Sent via Superhuman ( ***@***.*** )

**Comment by Yasmin-A95** [comment]
Closing this issue as we discussed it on linkedin and had to postpone the talk for now :)
