### ISSUE TITLE
Resiliency Patterns: Crafting Fail-Safe Systems with Proven Patterns

### ISSUE THREAD

**Issue by the-dina** [rails-oceania/roro#344]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
**Explore the essentials of resiliency patterns in Ruby. We'll cover key strategies like Circuit Breakers and Retry Logic to enhance application reliability, using practical Ruby examples for robust, fail-safe systems.**
- Which month's meetup you would like to present at
 **March**
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
**20 minutes**
- Your Twitter username (if you have one)
- Are you happy to have your talk published on the RubyAU YouTube channel?
**Yes**
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
**The github one is fine, thanks.**

**Comment by Yasmin-A95** [comment]
Thanks for proposing a talk Dina, this sounds like a great one. We'd love to have you at our March meetup.

**Comment by the-dina** [comment]
Thanks a lot @Yasmin-A95  for organising the events so perfectly! Looking forward to it!

**Comment by Yasmin-A95** [comment]
Hey @the-dina, the organisers and I decided to do mob programming for this meetup to switch up the format a bit. But would you still be interested in giving this talk in May? (we'll be skipping April due to Rubyconf)
