### ISSUE TITLE
Live demo: Build and deploy a Ruby app using Docker and Traefik

### ISSUE THREAD

**Issue by andypalmer** [rails-oceania/roro#347]
- Brief summary of the talk content
Live demonstration of making a simple Ruby app, building a docker image and deploying to a docker host running traefik as reverse proxy (including automatic letsencrypt certificate fetching)
- Which month's meetup you would like to present at
June
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
25 minutes
- Your Twitter username (if you have one)
[@andypalmer](https://x.com/andypalmer)
- Are you happy to have your talk published on the RubyAU YouTube channel?
Yes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![andy_avatar](https://github.com/rubyaustralia/roro/assets/71322/fab7b73a-9ea0-4a70-a671-3f95a4d8b3ae)

**Comment by cheddachedda** [comment]
Hey Andy, we'd love to have you present this next Tuesday, if that's alright with you

25 mins is probably the max that we want a talk going for, mainly to be conscious of people's attentiveness. If you can be conscious of keeping the audience engaged (breaks, interaction, etc.), that'd be handy. We'll provide a timer for you to see during your talk.

Cheers,
Dan

**Comment by andypalmer** [comment]
Hey Dan,
No worries. Happy to be there.
It's a live-coding thing (mainly because without that, it'd be "Here's the single command to deploy to Docker! Whoop, done!") but the plan is to do this while engaging with the group, so 🤞 I can keep their attention for a pomodoro.
Cheers,
Andy

**Comment by cheddachedda** [comment]
Love it! Love some live coding
