### ISSUE TITLE
Lets build a video game!

### ISSUE THREAD

**Issue by MadRabbit** [rails-oceania/roro#35]
Well, for those who are sick of concatenating strings for browsers all day long, thought maybe I could come over and show ruby where people don't use ruby normally. Video games!

I'd like to show how to build a kick ass game with ruby and gosu; and maybe inspire someone to have some fun with ruby outside of web.

[BLIP]__WARNING__[/BLIP] life hacking and heaps of fun are imminent!

**Comment by MadRabbit** [comment]
that will be a full length 20mins talk for intermediate/advanced pips, and an ave inducing show for the rest

**Comment by joneslee85** [comment]
this one kicks ass mate, what game do you have in mind? Angry Bird? Tetris?

**Comment by MadRabbit** [comment]
well, don't make me spoil all the details for you

**Comment by holodigm** [comment]
Nice one Nik :+1:  For May?

**Comment by MadRabbit** [comment]
yup

**Comment by maetl** [comment]
:+1:

Brings back memories of a weird game I made a few years ago with @banister: https://github.com/banister/tremolo

**Comment by mootpointer** [comment]
Thanks mate! Great talk...

Shipped!
