### ISSUE TITLE
Talk Proposal: Creating an in-place, distributed, content editing service from scratch!

### ISSUE THREAD

**Issue by asceresini** [rails-oceania/roro#36]
A 20min talk on a side project three of us started that makes editing content on sites quick and easy, that anyone can do.

The side project is about:

1. Edit your content directly from your own site, on the page where it appears!
2. Keep your message in sync across sites, regardless of where they are hosted or which technology they run on.

I will talk about:

- How we plan to simplify editing content online
- The underlying technologies and how we use them. This includes:
 - Rails
 - KnockoutJS
 - Test automation
 - Continuous integration 
 - Continuous deployment

**Comment by holodigm** [comment]
Sounds very interesting Anthony :+1:  For May?

**Comment by mootpointer** [comment]
My encourage is to make it principally about technology, and not too much about product :)

**Comment by holodigm** [comment]
I second Andrews encouragement also ;)

**Comment by asceresini** [comment]
Hi!

Yes for may would be good. Will definitely be around the technology and
challenges we encountered relating to cross origin.

**Comment by mootpointer** [comment]
Shipped!
