### ISSUE TITLE
lightning: distributed development in a nutshell

### ISSUE THREAD

**Issue by tobyhede** [rails-oceania/roro#37]
Some handy tips, tricks and tools for running or surviving in a distributed team

**Comment by bradly-swart** [comment]
+1

**Comment by holodigm** [comment]
Nice one Toby. Tomorrow night?

**Comment by mootpointer** [comment]
Erm… You mean next week?




A.

**Comment by tobyhede** [comment]
Sign me up

**Comment by mootpointer** [comment]
Loved it. Thanks Toby.

Shipped.
