### ISSUE TITLE
Lightning: Component based rails architecture primer

### ISSUE THREAD

**Issue by agenteo** [rails-oceania/roro#38]
Component based architecture is complementary to good object oriented practices and uses namespaces, test driven development and Ruby gems to gradually define a Rails application boundaries and enforce an internal dependency structure.

I'll go trough some points of my primer article http://teotti.com/component-based-rails-architecture-primer/

**Comment by holodigm** [comment]
Nice :+1:  For tomorrow night?

**Comment by agenteo** [comment]
yup

**Comment by holodigm** [comment]
Nice one, to bad I'm OS for this one.

**Comment by mootpointer** [comment]
Thanks Enrico!

Shipped.
