### ISSUE TITLE
Lightning: Regex in Ruby - Beginner

### ISSUE THREAD

**Issue by leckylao** [rails-oceania/roro#39]
Lightning talk for tonight 12/05/15. Some tips and tricks when using capture match in Ruby

**Comment by holodigm** [comment]
Hi Lecky, did you do this one last month? I was in the US.

**Comment by leckylao** [comment]
Hi Kym, no I did not. Was full.

**Comment by holodigm** [comment]
This month?

**Comment by leckylao** [comment]
Yep, I can do this month

Regards,
Lecky Lao

**Comment by holodigm** [comment]
Shipped
