### ISSUE TITLE
Tootle: Returning to Rails

### ISSUE THREAD

**Issue by agrimm** [rails-oceania/roro#40]
I did six months of Rails back in 2007, six years of Ruby, and now I'm returning to Rails, in the commercial sector.

This talk describes what it's like making the change before I forget what life was like pre-Rails.

I'm in an unusual position, as I have experience of programming in Ruby, but am somewhat new to Rails.

This talk could result in a lot of discussion (or at least I hope it does!). Some of the topics I touch upon may be similar to #26 by Jack Watson-Hamblin.

A draft of my talk is available at https://www.slideshare.net/secret/K9bbnp8eAFiRZF . I haven't checked with my employer whether it's ok with my talk, but I don't see any reason they wouldn't be.

**Comment by holodigm** [comment]
Hi Andrew, when would you like to do this talk?

**Comment by agrimm** [comment]
This month (Tuesday, 9 June).

**Comment by holodigm** [comment]
Brilliant, thanks :+1:

**Comment by holodigm** [comment]
Thanks @agrimm  :) Shipped
