### ISSUE TITLE
Working as a junior developer

### ISSUE THREAD

**Issue by agrimm** [rails-oceania/roro#41]
Presentation request. Congratulations! You've acquired your first programming job! Now what? What's involved, and how do you work effectively when you don't know everything?

**Comment by holodigm** [comment]
Hi Andrew, For next week?

**Comment by agrimm** [comment]
This is a presentation request, not a presentation. I want someone else to give this talk.

**Comment by holodigm** [comment]
Thanks Andrew :+1:

**Comment by mendokusai** [comment]
This is actually a great idea. Worst is I'd totally do it, _and_ I'll be in town, but the CEO is shouting dinner.

**Comment by wayne5540** [comment]
This is a great topic! And I think this could be taken by 2 viewpoints, `what senior can help`, and `what junior should do`.
