### ISSUE TITLE
Lightning: Automated Database Design, OttaDD -beginner

### ISSUE THREAD

**Issue by aaronongtw** [rails-oceania/roro#43]
GA student wanting to give a quick preview on an app that automates/and/or provide a dynamic tutorial for database design in Rails for beginners. 
The app allows user to use visual representation of database flow and structure and returns a step by step guide on how to set up the basic crud system. Automated database generation based on User design may be discussed subject to completion by next Tuesday. 
I am still very new at ruby as I have only started Ruby coding for two weeks. However, I do believe that a proper tutorial system will definitely help newbies such as myself improve productivity and understanding of Rails. 

https://ottadd.herokuapp.com/

Is currently still under development but has basic functionality. The site is alittle unstable and incomplete at the moment but will be ready by Friday.
Also I apologise for having the user to create a login. It was part of the requirement of our project.

**Comment by holodigm** [comment]
Awesome Aaron. Nice work, see you Tuesday night :)

**Comment by holodigm** [comment]
Great talk @aaronongtw  More please :) Shipped
