### ISSUE TITLE
Lightning: RSpec 3.3 what's new, what's cool

### ISSUE THREAD

**Issue by JonRowe** [rails-oceania/roro#44]
Quick lightning talk on new stuff coming in RSpec 3.3

**Comment by holodigm** [comment]
:+1:

**Comment by mootpointer** [comment]
While I’m sure it will be enlightening. s/lightening/lightning/ :D

**Comment by JonRowe** [comment]
![mad_men_salute](https://cloud.githubusercontent.com/assets/162976/7974129/4a477fa2-0aa1-11e5-92c6-73485c92ca5c.gif)

**Comment by holodigm** [comment]
Thanks @JonRowe  Informative as always, looking forward to the next one. Shipped.
