### ISSUE TITLE
App developer as a Web developer  - (Hybrid apps with Ionic Framework)

### ISSUE THREAD

**Issue by sameera207** [rails-oceania/roro#45]
I would like to talk about how we can develop hybrid mobile apps using the technologies we already know like `Rails`, `Angular` etc

Talk will primarily based on [Ionic Framework](http://ionicframework.com/) and hoping to cover the followings. 

* Basic structure of an ionic app, and how its familiar to us as web/rails developers
* How to make use of native app functionalities , available plugins
* How to test your app, (on browser, simulator, devise)  
* Deploying your app for testing ( some 3rd party services)
* `ionic` echo system and their tools.
* tradeoffs of Hybrid apps 

cheers,

sam

**Comment by holodigm** [comment]
Sounds like an interesting crossover talk @sameera207 . For July?

**Comment by sameera207** [comment]
@holodigm , Yep, I'm good for July :+1:

**Comment by holodigm** [comment]
Awesome, see you there :+1:

**Comment by holodigm** [comment]
Great talk, thanks. :+1:  Shipped
