### ISSUE TITLE
Monads in Ruby

### ISSUE THREAD

**Issue by carlwoodward** [rails-oceania/roro#46]
:money_with_wings: :moneybag: :dollar: :+1: :+1: :+1: :+1: :+1: :money_with_wings: :moneybag: :dollar: :money_with_wings: :moneybag: :dollar: :money_with_wings: :moneybag: :dollar: :+1: :+1: :+1: :+1: :+1:

**Comment by juliocesar** [comment]
Please change title to "Monads in Rubby".

**Comment by holodigm** [comment]
If you turn up @juliocesar you can call it what you like...

**Comment by holodigm** [comment]
For July @carlwoodward ?

**Comment by carlwoodward** [comment]
Yes please.

On Tue, Jun 23, 2015 at 10:44 PM, Kym McInerney <notifications@github.com>
wrote:

> For July @carlwoodward <https://github.com/carlwoodward> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails-oceania/roro/issues/46#issuecomment-114482033>.
>



-- 
Carl Woodward
88cartell.com
0412 218 979

**Comment by holodigm** [comment]
Awesome, done, looking forward to it :+1:
