### ISSUE TITLE
Why readable tests are important and one trick to set you straight

### ISSUE THREAD

**Issue by coderdan** [rails-oceania/roro#47]
Why readable tests are important and one trick to set you straight - Dan Draper [@danieldraper](https://twitter.com/danieldraper)

**Comment by holodigm** [comment]
Thanks Dan, great talk and the first syntactically normalised talk request ever :D :+1:

**Comment by holodigm** [comment]
Nice one Dan :+1: 
Shipped

**Comment by coderdan** [comment]
:)
