### ISSUE TITLE
WebSocket in Ruby and on Rails - Pros and Cons of ActionCable

### ISSUE THREAD

**Issue by leckylao** [rails-oceania/roro#49]
I've done a presentation of "WebSocket in Ruby on Rails" on RORO 11-02-2013. Time to revisit it after 2 years with Rails 5 ActionCable. 

Was thinking to talk on July's RORO but will need 15 minutes of it so probably better move it to presentation on August....

**Comment by holodigm** [comment]
:+1:

**Comment by holodigm** [comment]
Thanks Lecky, Great info in this talk :+1:  Shipped
