### ISSUE TITLE
How to unslow your rails dev server in 5 mins or less

### ISSUE THREAD

**Issue by MadRabbit** [rails-oceania/roro#51]
Oh, hi. So, I thought maybe you give me a 5 minutes lightning talk slot the next week, and I'll show a very little known trick how to make a rails app to load several times faster in the dev env.

Livecoding! It's gonna be awesoooome! You know you wanna see some magic with threads and stuff

**Comment by holodigm** [comment]
Nice one Nic :+1:

**Comment by MadRabbit** [comment]
sweet, thanks!

**Comment by tobyhede** [comment]
:+1:

**Comment by holodigm** [comment]
Awesome tip Nik :+1:  Can you send through details of your gem?

**Comment by MadRabbit** [comment]
i actually have a blog post about that http://nikolay.rocks/2015-08-06-unslow-rails-dev all the details are in there

**Comment by holodigm** [comment]
Brilliant, thanks Nik. Shipped.
