### ISSUE TITLE
Proposal: Interviews: how do they even?

### ISSUE THREAD

**Issue by tobyhede** [rails-oceania/roro#52]
A lightning introduction to technical interviews for junior to intermediate developers.

**Comment by holodigm** [comment]
:) Is this a request or proposal for tomorrow night?

**Comment by tobyhede** [comment]
Proposal for tomorrow if there is space.

**Comment by holodigm** [comment]
Awesome, yes indeed.

**Comment by MadRabbit** [comment]
we should get @corinnebrady to talks tomorrow as well to get the whole set!

**Comment by holodigm** [comment]
:+1:

**Comment by holodigm** [comment]
Love your work Toby :+1: Shipped
