### ISSUE TITLE
What I look for when hiring

### ISSUE THREAD

**Issue by puyo** [rails-oceania/roro#54]
What I look for when hiring Rails developers.

**Comment by puyo** [comment]
(Presented at GA to good reception.)

**Comment by holodigm** [comment]
:+1: Nice one Greg. Which one would you like to do next month?

**Comment by puyo** [comment]
Hmm, since we have some intermediate talks by the looks of it, I'll do this more beginnery one.

**Comment by holodigm** [comment]
Thanks Greg :)
