### ISSUE TITLE
Command prompt tips & tricks

### ISSUE THREAD

**Issue by puyo** [rails-oceania/roro#55]
Some advice to get oriented, unstuck and such, for beginners.

http://www.slideshare.net/gregmcintyre/command-line-for-railsgirls-attendees

**Comment by holodigm** [comment]
:+1: Nice one Greg. Which one would you like to do next month?

**Comment by joshuapaling** [comment]
@puyo I saw you give this at Rails Girls, and I think it'd be good for GA grads, too. Tracy and I are trying to ensure there's a beginner-friendly talk each month. Are you interested in presenting this yourself sometime?

And if not, are you cool if someone else uses/modifies your slides to give the same talk?

**Comment by puyo** [comment]
I'm happy to, yes!

**Comment by tracymu** [comment]
Hey Greg, we're sorted for June and July right now. (Although, July we do need lightning talks)

Would you be able to do August? 

Also, I love the look of your maintainable CSS one and hope to lock you in for that one when you're available again... though don't want to be too greedy :)

**Comment by joshuapaling** [comment]
@puyo We could fit you in this August if you're interested?

**Comment by puyo** [comment]
Sure. How many minutes should I aim for?

**Comment by joshuapaling** [comment]
Cool! This month so far we have two full length talks and 1 lightning - plus you. Normally we'd have 3 lightning. So, we're kinda flexible. Anywhere between 5 and 15 minutes would be OK. Let us know though, because eg. if you're aiming for 5 mins, and someone else asks to give a lightning talk, we'll let them. If you're aiming for 15min, we'll hold them off til next meetup.

**Comment by puyo** [comment]
I think I could cut it down from 75 minutes to 15.

**Comment by joshuapaling** [comment]
Haha cool. Well, 15m it is then. 👍

**Comment by puyo** [comment]
Updated slides: http://gregorymcintyre.com/slides/command-prompt/#/

**Comment by joshuapaling** [comment]
Thanks Greg, very entertaining.
