### ISSUE TITLE
Composition

### ISSUE THREAD

**Issue by damncabbage** [rails-oceania/roro#58]
Sticking methods together for maximal reusability.

(Lightning talk; _Intermediate_ tag, please. Happy to do it next week if you'd like.)

**Comment by holodigm** [comment]
Brilliant, thanks Rob :+1:

**Comment by damncabbage** [comment]
Err. Minus the `beginner` tag, please. :sweat_smile:

**Comment by damncabbage** [comment]
I've finished preparing the talk. I tried to shrink this down as much as I can, and I'm just under _ten minutes_; I can't remove much more without making it unintelligible. Is there any chance of a "short talk" billing instead? :worried: (I can push it to next month if you'd prefer.)

**Comment by holodigm** [comment]
All good Rob, we only have a few talks tomorrow night so going over will be fine.




Kym McInerney

CTO - AirService Digital

twitter: @holodigm
skype: kym_mcinerney









—

**Comment by damncabbage** [comment]
Video and PDF slides for it are here: http://robhoward.id.au/talks/2015/09/composition-and-pipelines/

**Comment by holodigm** [comment]
:+1:  Brilliant, thanks Rob :)

**Comment by holodigm** [comment]
Great talk Rob, thanks :+1:
