### ISSUE TITLE
Trailblazer: Leaving The Rails Way

### ISSUE THREAD

**Issue by apotonick** [rails-oceania/roro#59]
> "The puristic Rails Way isn’t appropriate for projects with a
> complexity greater than a 5-minute blog." -- _Someone._

Many developers have long started to introduce new abstraction layers into their growing Rails apps. 

[Trailblazer](http://trailblazerb.org) is a framework that brings a high-level architecture to web development. Let's discover domain objects, operations, form objects, view models, rethink authorisation and callbacks, and see how Trailblazer helps you building solid, sustainable Rails projects that suck less.

**Comment by holodigm** [comment]
Nice :+1:
