### ISSUE TITLE
Hopscotch: simplifying complex business logic 

### ISSUE THREAD

**Issue by gogogarrett** [rails-oceania/roro#64]
We wrote a gem at work [Blake](http://dev.blake.com.au/)  that helps dealing with complex logic in a ruby app, and I would love to share it with everyone. Cheers

**Comment by holodigm** [comment]
:+1: Thanks Garrett, this month?

**Comment by gogogarrett** [comment]
Yep, sounds good. :+1:

**Comment by holodigm** [comment]
Nice work Garrett. Love your style :+1:  Shipped.
