### ISSUE TITLE
RuboCop: Automatic code style checking for Ruby

### ISSUE THREAD

**Issue by agrimm** [rails-oceania/roro#66]
An introduction to RuboCop. This talk will be primarily aimed at people who haven't used it, but may discuss real-world issues with the gem as well.

This is a talk proposal (not a request for someone to give a talk), and is intended to be a longish lightning talk.

Edit 8/11/15: Link to slideshare is http://www.slideshare.net/agrimm/rubocop-54869297

**Comment by holodigm** [comment]
Thanks Andrew, for next week?

**Comment by agrimm** [comment]
Yes.

**Comment by holodigm** [comment]
:+1:

**Comment by holodigm** [comment]
Great stuff Andrew :+1:  Shipped.
