### ISSUE TITLE
Maskara - making frontend Rails development easier for everyone

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/roro#67]
Maskara is an experimental new gem for easing the coupling between Rails developers and frontenders.

I'll demonstrate what the gem can do to keep these two groups out from under each other's feet, and maybe even to build a contract between them.

An intermediate lightning talk.

**Comment by holodigm** [comment]
:+1:

**Comment by holodigm** [comment]
Nice work Simon. Shipped :+1:
