### ISSUE TITLE
Calyx: A generative grammar DSL

### ISSUE THREAD

**Issue by maetl** [rails-oceania/roro#69]
If there’s a free slot, I’d quite like to demo some stuff I’ve been working on for creating intricate texts with a randomised generative grammar DSL (I still haven’t come up with a good way to describe this unfortunately). This will be relevant to anyone who’s interested in artistic uses of Twitter bots and game design in Ruby, or wants to impress their co-workers by replacing lorem ipsum sample data with generative text that’s directly relevant to the users of their app.

May segue into a talk about different methods in computer generated literature and natural language processing.

**Comment by holodigm** [comment]
Sounds interesting :) :+1:
