### ISSUE TITLE
Lightning: CORS in APIs with Rails 4 - Beginner

### ISSUE THREAD

**Issue by wiserfirst** [rails-oceania/roro#70]
So you are implementing your new API, wanting to deploy it to a separate domain, and then access your API by making Ajax requests from the front end.

Well, that wouldn't work because of the same-origin security policy. To get around that, I think the best solution is Cross-origin resource sharing (CORS).

I'll talk about how does CORS work and how to implement it in Rails 4

**Comment by holodigm** [comment]
:+1: Nice one :)
