### ISSUE TITLE
Lightning: DGraph - Graph Database serving GraphQL

### ISSUE THREAD

**Issue by manishrjain** [rails-oceania/roro#71]
You heard how useful GraphQL is, so now learn about [DGraph](https://github.com/dgraph-io/dgraph)
- What is DGraph?
- Performance, scalability and implemented GraphQL features
- Demo with 21M RDF triples from [Freebase Film Data](http://www.freebase.com/film).
- Future plans

**Comment by holodigm** [comment]
For Feb 9 next month @manishrjain ?

**Comment by manishrjain** [comment]
Sure!

**Comment by mootpointer** [comment]
We missed you on February 9th, are you still interested in giving this talk?

**Comment by manishrjain** [comment]
Let's postpone it for now -- I think I'll have more to say once we have implemented a few more GraphQL features. Maybe in a few months.

**Comment by tracymu** [comment]
Hey @manishrjain  How are you feeling about GraphQL now?

**Comment by manishrjain** [comment]
Hi Tracy,

Sorry going a bit busy with a new release. Would be good to do this in a
couple of months.

Cheers,
Manish

**Comment by tracymu** [comment]
No problem 👍

**Comment by tracymu** [comment]
Hey @manishrjain  let us know when you're keen to do this talk!

**Comment by tracymu** [comment]
Hey @manishrjain - would you like me to close this issue or are you still interested in presenting at some point?

**Comment by tracymu** [comment]
(oops accidentally closed)

**Comment by manishrjain** [comment]
Hey @tracymu ,

I'd like to give a full talk on Dgraph -- I suppose that'd be 25 mins or so. I'll talk about our version of GraphQL (called GraphQL+- for lack of better name for now), and why standard GraphQL didn't work for us. Also, I'll demo running queries via Dgraph, over 21M Freebase film data.

**Comment by tracymu** [comment]
Hey @manishrjain - is there any way you'd be able to cut this talk down, or maybe spread it over 2 talks? If it's heavily technical and including a demo, I think it might be a bit more digestible that way.

**Comment by manishrjain** [comment]
I can talk more about the features, and demo. Instead of design. Depending
upon interest, I can then do a separate one on design.

**Comment by tracymu** [comment]
Cool, would you be able to do 15 mins in May?

**Comment by manishrjain** [comment]
Hey @tracymu,

@sungwoncho from my team knows Ruby on Rails, and would love to demo a use case built with Rails and Go. He'll reach out to you!

**Comment by tracymu** [comment]
Ok, thanks a lot @manishrjain 

It would be great if you could let us know ASAP if you're able to present @sungwoncho - so that we can lock in our lineup

Cheers

**Comment by sungwoncho** [comment]
@tracymu I can give 15 min talk in May.

**Comment by tracymu** [comment]
Hello @sungwoncho 

Please note the venue for next Tuesday
https://github.com/rails-oceania/roro/wiki/rorosyd-May-2017

**Comment by joshuapaling** [comment]
Thanks a lot for speaking last night @sungwoncho. Are your slides online anywhere? If you reply with a link, I'll post it in the #rorosyd slack channel.

**Comment by sungwoncho** [comment]
Thanks for hosting @joshuapaling. My slides are hosted on GitHub: https://sungwoncho.github.io/presentations/20170509-dgraph.html#/
