### ISSUE TITLE
Labels for all Sydney talk related issues

### ISSUE THREAD

**Issue by agrimm** [rails-oceania/roro#72]
I'm trying to edit https://github.com/rails-oceania/roro/wiki/rorosyd-topics so that there's a single link that shows every issue relevant for people wanting to propose or request a talk in Sydney.

Should every proposed full-length talk, every proposed lightning talk, and every requested talk based in Sydney share a label indicating that it's based in Sydney?

**Comment by joshuapaling** [comment]
At this point, the only use for the issues section is for Sydney presentations. So, I'd say for not it's fine just to link to the issues tab without any filters.

**Comment by agrimm** [comment]
@joshuapaling Fixed for not. :) https://github.com/rails-oceania/roro/wiki/rorosyd-topics/_compare/e0ca0c90ff06dbeb3c0a61e24ef93d9bc918ad65...7c1e765267178240d32f6811a9cd570ecd159ae9

**Comment by joshuapaling** [comment]
ha, woops. For now. Thanks Andrew.
