### ISSUE TITLE
Transitor: A PORO state machine in the spirit of Pundit!

### ISSUE THREAD

**Issue by coderdan** [rails-oceania/roro#74]
There are as many state machines for ActiveRecord as there are opinions on Rails. But pretty much all of them have the same things in common: they are geared around ActiveRecord, have high complexity and are hard/tedious to test.

So, after having fallen in love with Pundit (the Plain Old Ruby Object approach for policies), I thought I'd have a go at doing it for state machines. Hence Transitor.

I've been working on this gem for a while and would like to share it as an RFC of sorts. Its also a good reason to push me to finish writing docs for it.

**Comment by mootpointer** [comment]
Full length for February 9 2016?

**Comment by holodigm** [comment]
Good for next week @coderdan ?

**Comment by coderdan** [comment]
Yep I'm in!

**Comment by coderdan** [comment]
Oh no! I just realised I'll be on a plane to Ruby conf that night!

**Comment by mootpointer** [comment]
How would you feel about April or May for this one?

**Comment by coderdan** [comment]
May works. I'll be on my Honeymoon in April! :)

**Comment by tracymu** [comment]
Is this cool for May @coderdan  ?

**Comment by coderdan** [comment]
Yep that's fine by me!

**Comment by coderdan** [comment]
@tracymu @mootpointer I emailed Kym last week but haven't had a response. I've been called down to Canberra at the last minute and I'm not going to be able to speak tomorrow :( Do you have a back up??

**Comment by holodigm** [comment]
We are still looking

**Comment by tracymu** [comment]
Hey, I have someone.

**Comment by coderdan** [comment]
Sorry, everyone. I honestly thought emailing someone directly would be a more effective way of communicating rather than getting a comment lost in a thread. I'll just update the issues next time.

**Comment by holodigm** [comment]
:D 👍

**Comment by joshuapaling** [comment]
@coderdan It's been a while so I'll close this issue for now - but if you're still interested in giving this talk please re-open.

**Comment by joshuapaling** [comment]
Funnily enough I just arrived at this issue via google while searching for state machines that don't depend on active record! I'm trying to break a circular dependency that can't be done without such a state machine.
