### ISSUE TITLE
Clean code; Later == never

### ISSUE THREAD

**Issue by markadrianagbuya** [rails-oceania/roro#75]
We often sacrifice the cleanliness of code as a tradeoff to meet deadlines. We promise to refactor it and clean it up later. However, the features keep rolling in and later becomes never.

During the talk I want to discuss:
- why writing clean code is important
- how writing clean code actually saves time
- how to develop the habit of writing clean code as you go
- simple & practical techniques in Ruby to write cleaner code

This is my first talk proposal! I'm excited but pretty nervous too. This talk is targeted more to beginners and talks about simple and what may seem like trivial techniques. But I hope it sheds some light on how effective the simple techniques may be for writing cleaner and more readable code.

**Comment by holodigm** [comment]
Hi @markadrianagbuya is this a lightning or 15 minute preso?

**Comment by markadrianagbuya** [comment]
15 minutes

**Comment by mootpointer** [comment]
Are you open to giving this talk in April?

**Comment by markadrianagbuya** [comment]
I might still be in Manila for RubyConf at that time. I'm doing this talk at RubyConfPH on the 9th April in Manila, so I was hoping to get some more practice and feedback by doing it in March at Roro. But I understand if slots are full.

**Comment by mootpointer** [comment]
@markadrianagbuya I may have messed up the scheduling for tomorrow, so you may have a slot.

I'll have to confirm later today, but would you be able to present (to be clear, this is not yet confirmed, I'm just checking if you're available at all)

**Comment by mootpointer** [comment]
Okay! We've got space for you tomorrow if you want to present, but we can survive without. It's up to you! :)

**Comment by markadrianagbuya** [comment]
Ahh I wish I was more prepared! I'll be there to watch tomorrow but I'll sit out this round :) Thanks!

**Comment by markadrianagbuya** [comment]
Here are the slides I presented at RubyConfPH 2016: https://www.slideshare.net/secret/naGlq9VKhbdQQx. It's a 25 min talk so I'll have to condense it down. I'll be busy in April and May but I'm open to present after that if there are slots!

**Comment by tracymu** [comment]
Hey @markadrianagbuya  - would you be available to present on this at the next Roro (14th June) ? I think it matches really well with the other talks we have that night!

**Comment by markadrianagbuya** [comment]
Yes I'm available! Great. I'll just need to shorten the talk a little to fit into the 15 min slot

**Comment by tracymu** [comment]
Awesome, looking forward to it  - you're locked in.

**Comment by holodigm** [comment]
This was a great talk Mark, thanks very much 👍
