### ISSUE TITLE
Event Sourcing, part 2

### ISSUE THREAD

**Issue by vonconrad** [rails-oceania/roro#76]
Hello lovely Sydney people!

I'd like to follow up my RubyConf talk, which was meant to make people curious about Event Sourcing, with a talk about some of the practicalities, how to go about it, and where to start.

For those who missed my RubyConf talk, I'll quickly recap that before launching into particulars.

I'd allow for 45 mins for this talk.

**Comment by gogogarrett** [comment]
Hell yeah! :+1:

**Comment by markadrianagbuya** [comment]
Nice! I'm definitely interested in learning more about the practicalities of event sourcing. I think I'll need this in an upcoming project.

**Comment by jessicace** [comment]
Yay!

**Comment by holodigm** [comment]
Hi @vonconrad You're looking to present this at the March 8 meetup?

**Comment by vonconrad** [comment]
@holodigm Whenever convenient! April is looking tricky, but either March, May, or possibly June should work.

**Comment by holodigm** [comment]
That's awesome mate. Much appreciated. The team has a few things in the pipeline for the Sydney meetup which we need to wrangle and then we'll be in touch in the next week or so :+1:

**Comment by vonconrad** [comment]
Sounds good. No rush. 😊

**Comment by mootpointer** [comment]
@vonconrad Is there any chance of paring down to ~30 minutes? 45 minutes would mean that we have no more room for talks. (Normally we have 3 x 15min talks)

**Comment by vonconrad** [comment]
@mootpointer I'm sure that would be possible!

**Comment by mootpointer** [comment]
@vonconrad Did we confirm you properly for tomorrow, or did I do that in my head?

**Comment by vonconrad** [comment]
@mootpointer Unfortunatey not. :confused: I didn't realise you wanted me to speak this month, and I can't make it over to Sydney on this short notice. I'm sorry--we'll have to do it another time (or not at all). :disappointed:

**Comment by mootpointer** [comment]
Yeah. Sorry about that. Can we lock in April now?

A.

**Comment by vonconrad** [comment]
Assuming that's April 12, that should be fine. 👍

**Comment by holodigm** [comment]
That's great, thanks Sebastian @vonconrad. Locked in for next week. Looking forward to it :)

**Comment by vonconrad** [comment]
See you then! :)

**Comment by maetl** [comment]
I can’t make it tonight unfortunately, but I’m using event sourcing fairly heavily in my work right now anyway—so in my case you’d be preaching to the converted.

But @vonconrad—if you are gonna show any cool/funny new slides/ideas on the topic, feel free to drop a link to them here afterwards. Have fun!

**Comment by mootpointer** [comment]
Shipped! Thanks @vonconrad.

**Comment by joshuapaling** [comment]
Really nice talks, thanks :+1:

**Comment by airservice-deployer** [comment]
Thanks Sebastian! Great talk and great to see you up this way. Come back soon :)

**Comment by holodigm** [comment]
Thanks Sebastian! Great talk and great to see you up this way. Come back soon :)

**Comment by vonconrad** [comment]
My pleasure! Thanks for having me! 😊
