### ISSUE TITLE
Morphing your Ruby into Civic Tech

### ISSUE THREAD

**Issue by keithpitty** [rails-oceania/roro#77]
Were you inspired by the closing keynote at RubyConf AU recently to use your tech skills to become more engaged in the political process? If so, this talk is for you!

Keith Pitty (@keithpitty) and Henare Degan (@henare) will introduce you to some fascinating open source Ruby projects that also allow you to contribute to civic tech.

**Comment by keithpitty** [comment]
@mootpointer just wondering whether the organisers would like @henare and I to present this month. It would be great to know so that we can prepare. // @holodigm

**Comment by mootpointer** [comment]
Hi Keith,

There should definitely be time for a lightning talk this month. Let's lock it in!

**Comment by henare** [comment]
@mootpointer woohoo, thanks! Really looking forward to this :sparkles:

**Comment by keithpitty** [comment]
@mootpointer having discussed this with @henare today, we now realise it might be difficult to squeeze this talk into 5 minutes. Do you think 10 minutes would be ok?

**Comment by mootpointer** [comment]
That should be fine :smile:
