### ISSUE TITLE
Proposal: Move rorosyd

### ISSUE THREAD

**Issue by mootpointer** [rails-oceania/roro#81]
Our venue has been the subject of some discussion for months now. We've had issues with King St Brewhouse, with noise, seating and sub-optimal AV equipment (like that month where we were almost doing presentations using PAL resolution because of a projector change).

In this issue, I'd like to lay out my thoughts on why we should make the move, the details of the move, some of the implications of the move that we're aware of and our efforts to minimise negative effects. From there, we'd like to open it up for community discussion.

After the discussion, we'll take that on board as organisers and make a call.

_This is going to be a long post. I make no apologies for that. Buckle up._

# Some History
Someone can better fill in the history of rorosyd, since my first rorosyd wasn't until mid-2007. From what I can glean from trawling the mailing list archives, we were at Job Futures from ? until [August 2007](https://groups.google.com/d/msg/rails-oceania/jV4sLh-eX8Y/8MfvUWzjjzoJ) when it moved to the Crown Hotel thanks to Matta booking a room. I think this may was my first rorosyd. For those interested, [this is what rorosyd looked like](https://www.flickr.com/photos/moot_pointer/albums/72157601472529753).

From there at some point (I think while I was travelling), rorosyd moved to the Trinity Bar, where it stayed until [May 2014](https://groups.google.com/d/msg/rails-oceania/Bdb2uJPvMmE/N7akftinrh8J). We did have one rorosyd takeover (sorry about that), where we all traipsed to The Shelbourne to hear Yehuda Katz (not until after we heard from some corporate overlords).

I feel like this is useful just to remember where we've been. Within that, it is probably worthwhile thanking all the people who have helped organise or support rorosyd over the years. I'm afraid I'm going to miss someone if I try, but: Jason Crane, Matt Allen, Lachie Cox, Keith Pitty, Ben Askins, Tim Lucas, Steve Ringo, Kym McInerney, Joss Paling and Tracy Mu Sung.

# King St Brewhouse

We moved to King St Brew House after feeling like we'd reached capacity at Trinity Bar. The Trinity was great to us. We only occasionally had issues, like random Army dudes heckling, but overall it worked well. Having a whole floor to ourselves was pretty great.

Early in the days of King St, we had significant teething issues with the sound. Eventually we mostly ironed that out when we learned we could play with the big mixing desk. It's still not great, but it doesn't drop out randomly any more and we don't have to shout, so I take that as a win.

## The Sound Problem
One of the frequent complaints in the recent [rorosyd survey](https://notcode.typeform.com/report/KlcOOt/HL26) was being able to hear at the back of the venue. Those curtains don't stop much sound getting through. That means if there's a game of pool or even a couple of conversations happening on the other side, those at the back of the room have a hard time hearing. In the mean time, I find myself cranking the volume which means those at the front of the room are being blasted.

## Seating
The long tables are great for before the meetup starts, but once we're going, they're decidedly sub-optimal for fitting people into the room and giving everyone a seat. I've had people tell me that the tables make things feel more clique-y, which is an interesting observation. I feel like for the consumption of talks, we could probably do better.

## The Pub
I have to say, I really like the King St Brewhouse's beer selection. If we are to move I think I'll miss it a bit. The food is... not bad, but it doesn't compare to The Trinity's steaks :smiley:.

# The Move
It is in this context that we as organisers began looking for a venue to move to. The main reason people come to rorosyd is for to learn from the talks (weighing in at 81% of the respondents). The second is to socialise (79% of respondents). Let's call them a tie. Currently I'd say our venue facilitates socialising moderately well and that it facilitates learning from the talks moderately poorly. We're looking for a new venue that will enable us to have both.

As a community manager in 2013, I spent a lot of time looking for a higher capacity venue to host the Yehuda Katz takeover. Let me say this now: It is really hard to find a pub or bar which is conducive to a meetup of our size which will not require a minimum spend or other unacceptable conditions for an area takeover.

The various issues I came up against when I was looking included: large minimum bar spend ($2k+), minimum food pre-purchase (apparently to meet RSA requirements) and security issues. Admittedly, these issues were ones that I found three years ago, but I have no reason to believe anything will have changed much in the elapsed time.

So as I said on Tuesday: _We're not going to find a better pub_. Now I could be wrong on that one. Please if you have ideas, let me know.

# The Offer
Pivotal are moving into new digs in Sydney, and as part of the fit-out, they've included a dedicated events space. I've chatted to some folks at Pivotal who have offered that space for us to use as the rorosyd venue. I am inclined to take them up on that offer. The space would give use room for another 50% growth in attendance and would better facilitate talks.

![pivotal](https://cloud.githubusercontent.com/assets/126967/13720880/00c413da-e869-11e5-83aa-8e1cb02fa4f3.jpg)

The space becomes available in May, (and is still under construction) so I don't have proper pictures for you, but I trust that Pivotal know what they're doing. They host meetups in their spaces in New York as well as San Francisco (and possibly other places that I don't know about).

From our discussions, we will not be ceding control of rorosyd to Pivotal. They occasionally offer talks, but we are not required to include them. Kym, Joss, Tracy and I will still be responsible for the direction and running of the evenings.

As an added bonus, the new pivotal space also has a rooftop terrace which looks out over the city. That seems like a pretty great space to socialise in (at least in the warmer months). I'm not sure about the logistics of moving between the two spaces, but I'm sure we can work something out.

![terrace](https://cloud.githubusercontent.com/assets/126967/13720882/1a3d29b4-e869-11e5-8ad8-e08171351e74.jpg)

### Food and Drink
Moving into a new space, we can't just buy our own food and drink at the venue. That means we have a requirement for sponsored food and drink. That means we need sponsors. We're working with Ruby Australia to see if we can work through them to make that happen.

Let me be clear, we're talking about *food*. Not Pizza. We're currently looking into options for this. If you want to help with this, that would be most appreciated.

### Socialisation
I'm assuming we'll be able to have some space within the event space to socialise, but being Sydney, until all the bars are closed down by the state government, I'm sure we can find some places to kick on to. Once the bars are shut down, I guess we'll have to go to Barangaroo or the Star :trollface: 

The terrace may also be an option (and a glorious one at that) for hanging out. 

### Not a pub
I understand that it's been a point of pride that rorosyd is not in an office. I agree with that. It has been great in many ways, but I think that now is the time to see if we can make an office work. Our aim this year as organisers is to ensure that we have high quality talks, and those are wasted if they're given in an environment that is not conducive to hearing them.

# So now what?
I have a lot more rant to go, but I feel like this is getting pretty long at this point, and I'd like to hear some other perspectives. We may split of some of the unresolve sub-issues like food and sponsorship into their own issues if it looks like we're going down the venue change route.

This is not something that we propose lightly. We understand that moving venue will change the character of rorosyd. We also believe it's for the best.

I ask that in our discussion, we keep in mind the [code of conduct](http://ruby.org.au/code-of-conduct.html) as that applies to here. Please think the best of those you are interacting with and contribute constructively.

**Comment by nicholashibberd** [comment]
Sounds like a great option to me. Thanks for the comprehensive post!

**Comment by damncabbage** [comment]
This sounds like a great opportunity to try something new; thanks for putting the effort into to surveying, preparing and proposing this. :smiley:

**Comment by andys** [comment]
That offer looks great and well worth giving it a several month test evaluation!

**Comment by MelissaKaulfuss** [comment]
Wow! Impressed with the detail and effort that's gone into the survey and the report – really great :)
Not that I've every been to Sydney's RORO meetup –– I would if I was ever there at the right time. 
But, I have been to King St Brewhouse and I have to say, it's noisy and it's a pub (not that I mind) but in the efforts of it being comfortable for everyone, Pivotal would be a great option. And if Ruby AU can assist with food and drinks even better.

**Comment by coderdan** [comment]
Thanks for the comprehensive analysis @mootpointer!

I love the social elements of the Ruby community and I don't want those to stop but I do feel like as a community we have an opportunity to give newcomers more support and learning opportunities. An office may be a better place to do that and perhaps will help make those not interested in beer feel more comfortable about attending.

Having been to Pivotal's SF offices I'm confident that they will create an awesome space that will not take away from the social elements. I'd also add that two other office-based meetups I've attended - SydJS and ProductHunt - have both been very enjoyable despite being in an office.

So, I think the Pivotal offer is a great opportunity!

**Comment by coderdan** [comment]
As a side note: I think I counted just one woman in the photos from 2007. Although there is still room for lots of improvement, things have progressed a lot since then!

**Comment by lightningdb** [comment]
For the history, from memory: Pre-Job Futures, RORO was hosted at Digital Nomads on Mary Street in Surry Hills. My first one was in late-2006 I think (ran into Lachie Cox, who I hadn't seen in 10 years since high school!) - roughly eight to twelve people sitting around talking pretty informally about Ruby stuff. Good times!

**Comment by mootpointer** [comment]
Ah thanks @lightningdb. I knew there was some history I was missing.

**Comment by leesheppard** [comment]
Seems quite a good choice, not exactly under contract if the group decision is to relocate elsewhere again if this is unsuitable. Thank you for taking the time to do the response.

**Comment by robjacoby** [comment]
I'd just like to throw a suggestion for food/drink that BrisRuby uses, which is where we have our meetup first, and then we all go to a local restaurant afterwards for food/drink/socialising.

This works well for us because the restaurant provides good food, cheaply, and is extremely fast at turning out the food. It also allows us to not be distracted while the talks are happening.

Admittedly, our numbers are considerably smaller than rorosyd, however it may be an option to consider?

**Comment by benaskins** [comment]
Well done @mootpointer, this sounds like a great move.

**Comment by suranyami** [comment]
+1 from me.

**Comment by joshuapaling** [comment]
@robjacoby how many talks do you typically have, and how long do they run for? What time do you start the meetup, and what time do you usually find yourself having dinner?

**Comment by keithpitty** [comment]
Thanks for all your efforts on this, @mootpointer!  Much appreciated.  :+1: for trying the new venue.

**Comment by mootpointer** [comment]
Shipped!

**Comment by keithpitty** [comment]
😄
