### ISSUE TITLE
Empathy Driven Development - Documentation

### ISSUE THREAD

**Issue by sjahandideh** [rails-oceania/roro#82]
Hi guys, I've been recently playing around with different aspects of Empathy Driven Development and how we can add some aspects of it to our Ruby coding exercises. I plan to give a series of talks about EDD in 2016 and I'd like to start with documentation.

This talk targets everybody from beginners to advanced programmers.
I need 15 to 20 min for it.

**Comment by joshuapaling** [comment]
Awesome. Would you be ready for the April meetup? Or May?

We've got a longer presentation planned for April, and if yours might run a bit overtime too, it may be better off in May.

**Comment by sjahandideh** [comment]
i dont mine either

**Comment by joshuapaling** [comment]
Hi Shamim, sorry for the delay. We've got you down for April. Looking forward to it!

**Comment by sjahandideh** [comment]
Cheers!

**Comment by mootpointer** [comment]
Thanks Shamim! Shipped.
