### ISSUE TITLE
Work Study Groups - Why it's worth learning new languages

### ISSUE THREAD

**Issue by tracymu** [rails-oceania/roro#83]
I spoke to Garrett Heinlen last night, he was speaking very enthusiastically about a study group they had formed at Blake Education for them all to learn Elixr, and how successful it is.

I think it would be a great topic for a talk (and he said it was ok for me to suggest him).
How Blake did it, why they did it, benefits of learning new languages, etc. 

oh I just noticed I can't add labels....

**Comment by joshuapaling** [comment]
:+1: agree, sounds like a good talk.

**Comment by martinstannard** [comment]
As a participant in the group, I can second Garrett's enthusiam, and reckon it would be a good topic for a talk.

**Comment by gogogarrett** [comment]
I'm in, perhaps May?

**Comment by joshuapaling** [comment]
That works for us. I'll put you down for May. Let us know if you can't do it by then.

**Comment by tracymu** [comment]
@gogogarrett  just a reminder to check if you can do this one in May? :)

**Comment by gogogarrett** [comment]
Yep, I'm in. :]

**Comment by holodigm** [comment]
Rockstar @gogogarrett

**Comment by mootpointer** [comment]
Thanks Garrett. I appreciate you spruiking my other meetup :P
