### ISSUE TITLE
Beginner talk suggestion - Ruby Building Blocks, and how Rails uses them

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#85]
Talk request. I think there's a few beginners/intermediates who'd like to talk but aren't really sure what to talk about. I have lots of ideas, and lots of semi-planned begginer/intermediate oriented talks in my head. I'll do a brain dump here and see if anyone picks up on them. I'd be happy to help mentor in the talk prep if anyone wanted it.

Audience: beginner / intermediate

Cover the building blocks of object oriented programming in general (classes, objects, instances, methods, variables, scope, inheritance) and also Ruby-specific concepts (eg Modules, class macros, etc), and how they apply to Rails (eg, helpers are modules - that's why they're available everywhere. has_many etc are class macros. Your models inherit from Active Record.)

This is a super broad topic, and could be broken up into several talks:

eg. "What are modules in Ruby? (answer: they're used for namespacing, and mixin functionality). What is mixin functionality? What is namespacing? (simple namespacing example: folders on your desktop - you can keep two files with the same name, so long as they're 'namespaced' in different folders.

**Comment by holodigm** [comment]
:+1:

**Comment by joshuapaling** [comment]
Probably a bit too optimistic / excited to thing someone would want to talk about something that wasn't their idea. Closing this. I'll keep it in mind if I ever get round to doing a beginner-ish talk.
