### ISSUE TITLE
Intermediate talk suggestion - Ruby class macros

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#86]
Talk request. I think there's a few beginners/intermediates who'd like to talk but aren't really sure what to talk about. I have lots of ideas, and lots of semi-planned beginner/intermediate oriented talks in my head. I'll do a brain dump here and see if anyone picks up on them. I'd be happy to help mentor in the talk prep if anyone wanted it.

Audience: beginner / intermediate

Intro to what a "class macro" is in ruby. Short answer: it modifies the behaviour of the class - usually by adding methods. You could then walk through an example of building a really simple class macro - such as building your own version of `attr_accessor`. Rough example code below. You could then go on to describe common class macros in Rails (eg belongs_to, has_many) and what methods they add to your models.

    class Person

      def self.my_attr_accessor(variable)
        # one way to do it...
        define_method "my_#{variable}" do
          return instance_variable_get("@#{variable}")
        end

        define_method "my_#{variable}=" do
          instance_variable_set("@#{variable}")
        end
        
        # another way to do it...
        # getter
        self.class_eval("
          def #{variable}
            @#{variable}
          end
        ")

        # setter
        self.class_eval("
          def #{variable}=(val)
            @#{variable}=val
          end
        ")

      end

      my_attr_accessor :name

      def initialize(name)
        @name = name
      end

      # def say_hello
      #   puts "Hi, I'm #{@name}"
      # end

      # def name
      #   @name
      # end

      # def name=(name)
      #   @name = name
      # end
    end

    p = Person.new('Joss')
    puts p.name
    p.name = 'Fred'
    puts p.name
    # puts p.my_name
    # p.my_name = 'Fred'

    puts p.methods - p.class.superclass.methods

**Comment by holodigm** [comment]
:+1:

**Comment by joshuapaling** [comment]
Probably a bit too optimistic / excited to thing someone would want to talk about something that wasn't their idea. Closing this. I'll keep it in mind if I ever get round to doing a beginner-ish talk.
