### ISSUE TITLE
Lightning talk triple shot

### ISSUE THREAD

**Issue by simonhildebrandt** [rails-oceania/roro#88]
I'd like to do a 5 minute lightning talk covering three gems I've just open sourced:

Pact::Retreaty - S3 contract storage for Pact.
https://github.com/fairfaxmedia/pact-retreaty

Restroom - lightweight toolkit for building RESTful API wrapper gems.
https://github.com/fairfaxmedia/restroom

New Bitbucket gem leveraging V2 of the API, and Faraday.
https://github.com/fairfaxmedia/bitbucket2

I'd like to present on the 12th of April, but I can wait until later if necessary.

**Comment by joshuapaling** [comment]
@simonhildebrandt it looks like we don't have any lightning talks down for 12th April, so that should be fine. Let's lock in the 12th! :+1:

**Comment by simonhildebrandt** [comment]
Awesome. :)

**Comment by joshuapaling** [comment]
@simonhildebrandt I'm sorry Simon, I've made a mistake - this month we have Sebastian von Conrad coming up from Melbourne to do a longer talk on Event Sourcing, so we weren't going to have any lightning talks. Would it be OK if we move you to May?

**Comment by holodigm** [comment]
Hi @simonhildebrandt We'll just check before confirming as Sebastian's talk is going over the normal length.

**Comment by simonhildebrandt** [comment]
That sucks - already told all my cow-orkers. :( 

I'll send 'round an update - May for sure?

**Comment by joshuapaling** [comment]
Hi Simon, sorry for the delayed response. Re: "May for sure" - May's a tricky meetup. The plan is to switch venues (from King St Brewhouse to Pivotal Labs) - but that partly depends on the construction being finished at Pivotal. If things run on schedule, it should be finished. But as these things sometimes go, there's a change things won't be finished. If that happens, we may end up moving the May meeting back a week or so, or getting a different venue.

We should know for sure what's happening in a couple of weeks, and will let you know then.

**Comment by joshuapaling** [comment]
@simonhildebrandt barring catastrophe we're now locked in for the new venue for May. Are you still good to present in May?

**Comment by simonhildebrandt** [comment]
@joshuapaling - sounds good. :)

**Comment by mootpointer** [comment]
Cool stuff, thanks Simon!
