### ISSUE TITLE
How the Digital Transformation Office used Ruby to prototype GOV.AU

### ISSUE THREAD

**Issue by catherine-jones** [rails-oceania/roro#89]
We'd love to have you speak, or suggest a talk for Sydney Ruby. In addition to your talk topic, please mention the following:
- Proposal
- Suitable for everyone

For proposals:
- My talk would be ready to give this month April
- This is a lightening talk

**Comment by holodigm** [comment]
Hey @catherine-jones This sounds great! We're full for April (next week) but how does May sound?

**Comment by catherine-jones** [comment]
@holodigm @joshuapaling @tracymu I am so sorry but I just got an email from our corporate team this evening and I am no longer allowed to do any speaking engagements until after the July 2nd election. Again apologies about the late notice but they only just informed me of this change

**Comment by holodigm** [comment]
ROFL politics... No worries and thanks Catherine 👍
On Mon, 9 May 2016 at 19:31, Catherine <notifications@github.com> wrote:

> @holodigm <https://github.com/holodigm> @joshuapaling
> <https://github.com/joshuapaling> @tracymu <https://github.com/tracymu> I
> am so sorry but I just got an email from our corporate team this evening
> and I am no longer allowed to do any speaking engagements until after the
> July 2nd election. Again apologies about the late notice but they only just
> informed me of this change
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/rails-oceania/roro/issues/89#issuecomment-217818327>
>
-- 



*Kym McInerney*
*CTO - AirService Digital*


*twitter: @holodigm <http://twitter.com/holodigm>skype: kym_mcinerney*
* <http://au.linkedin.com/in/kymmcinerneysydney>*

**Comment by mootpointer** [comment]
So can we pencil this in for July?

**Comment by joshuapaling** [comment]
@catherine-jones Would you be interested in giving this talk in July?

**Comment by tracymu** [comment]
@catherine-jones  - I don't know if we even have a government!?!? How do you feel about August @catherine-jones ?

**Comment by tracymu** [comment]
@catherine-jones  where have you gone!?!??!

**Comment by joshuapaling** [comment]
I think we'll close this one for now... but @catherine-jones if you're still keen to give it, feel free to re-open!
