### ISSUE TITLE
Resume as Code

### ISSUE THREAD

**Issue by paulfioravanti** [rails-oceania/roro#90]
This is a 5 minute lightning talk proposal for a show and tell of [my resume](https://github.com/paulfioravanti/resume), which evolved from a simple document into a Ruby program.

It consists of a short slide deck and short demo, and should be good for beginners upwards since I don't plan on delving deep into code specifics unless asked.  The main message is really just to try something a bit different with the tools you use to sell yourself.

Slide deck and app/demo are ready to go for whenever a slot is available.

**Comment by joshuapaling** [comment]
Sounds good. We're full up for April, but will let you know soon if we can fit you in for May :+1:

**Comment by tracymu** [comment]
Hehe, I was going to put your name down, I'm so glad you committed @paulfioravanti  👍

**Comment by mootpointer** [comment]
`thanks.exe.bat.pif`
