### ISSUE TITLE
EDD part 2- Code Structure

### ISSUE THREAD

**Issue by sjahandideh** [rails-oceania/roro#91]
We'd love to have you speak, or suggest a talk for Sydney Ruby. In addition to your talk topic, please mention the following:

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?
**Myself**

- Intended audience (beginners, intermediates, advanced)
**all levels**
  
For proposals:
- Which month would you be ready for?
**July 2016**

- Is this a 5m (lightning) talk, or a 15m talk?
**15 to 20 min**

**Comment by joshuapaling** [comment]
👍  looking forward to it.

**Comment by sjahandideh** [comment]
@joshuapaling it can be ready for June as well btw. fit it in the schedule as you see fit

**Comment by joshuapaling** [comment]
Ok sweet, we'll let you know as proposals start coming in for June.

**Comment by holodigm** [comment]
Thanks Shamim, Loving the series, keep them coming :) 👍
