### ISSUE TITLE
"Catching the Bugs You're Missing"

### ISSUE THREAD

**Issue by tracymu** [rails-oceania/roro#92]
Writing code well is hard enough; testing code well is much harder. We cherry-pick our test examples piecemeal, hoping to cover all the bases, and our apps still blow up.

A testing approach called Property-Based Testing lets you lean on the computer to help you write better, more thorough tests. What are property tests, what are they good for, and how do you write them?   Come along and learn how to make the your tests really work for you.

**Comment by mootpointer** [comment]
Loved it. Thanks Rob!
