### ISSUE TITLE
Git tips and tricks

### ISSUE THREAD

**Issue by agrimm** [rails-oceania/roro#93]
This is a talk request, not a proposal, but one I may fulfill myself at some stage.

This is aimed at a beginner audience: people who use git on a day to day basis, but only the bare minimum of its functionality.

Most people use git (or similar version control software), but many people only use a small subset of its functionality.

What unused functionality is there in git, and how can it be useful?

Examples:

* Doing too many things at once? `git stash save` to the rescue!
* Using `git add -p` to create a commit that does one thing and only one thing.
* Want to see what changes have happened to a file? `git log -p path/to/filename`
* Want to re-order or squash together commits? `git reset --soft` or `git rebase -i`
* Want to find out when the build broke? `git bisect run bundle exec rspec`

**Comment by mootpointer** [comment]
Sounds like a great talk. Does anyone want to dob in a speaker?

**Comment by joshuapaling** [comment]
Was @agrimm dobbing in himself for this one? I agree it's something a lot of the new GA grads could benefit from.

**Comment by agrimm** [comment]
I'm ready to dob myself in. Should be ready by the next RoRoSyd if you want it scheduled then.

**Comment by joshuapaling** [comment]
Great, thanks Andrew! We're full up for June, but I've put you down for July. Let me know if that's not OK.

Also, I'm assuming this will be a full 15m talk, not a lightning talk?

**Comment by agrimm** [comment]
July is fine. August is also fine, but I can't do September.

This will be a full 15m talk.

**Comment by agrimm** [comment]
Can I confirm it's still scheduled for July, not August?

**Comment by joshuapaling** [comment]
Hi Andrew, if it's OK we'll move you to August. Jon was unable to do August, so we've confirmed him for July.

**Comment by tracymu** [comment]
@agrimm  just a reminder that you are scheduled to talk at the next Roro if that is still cool?

**Comment by agrimmtt** [comment]
@tracymu Yes, that's fine.

**Comment by joshuapaling** [comment]
Thanks Andrew, very interesting talk.
