### ISSUE TITLE
Lightning talk: you should give a talk at RORO

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#95]
- Talk proposal for all levels, for June.
- Lightning talk

Each month we briefly mention "if you'd like to submit a talk, check out the issues list on github". This would basically be an extended version of that, were I spend a few minutes mentioning the benefits of giving a talk, and encourage especially newcomers and first-time speakers to give a talk. I'd also try to encourage people who are interested in speaking, or who have a topic they'd like to hear about, to come and speak to Tracy or myself on the night, then we can create the issue in Github and follow up with them.

**Comment by holodigm** [comment]
Great talk Joss, thanks. 👍
