### ISSUE TITLE
RSpec Q&A

### ISSUE THREAD

**Issue by JonRowe** [rails-oceania/roro#97]
So, it's been put to me that people really enjoyed the QA section of my RubyConfAU talk so I propose to embigenate that and do more! Basically I'm proposing that I get questions in advance via the mailing list, twitter here, slack, etc. and then answer them. Tada! Ruby! Will bring suitable gifs.

I'd say this would be a 15minute talk (well kinda), aimed at all levels. I'm proposing this is for June, if bumped would have to check dates!

**Comment by tracymu** [comment]
@JonRowe I'm loving it. We may have got June sorted out already (and maybe even July), BUT this just gives everyone more time to come up with the most eloquent questions they can :)

Let me know what dates you're available

**Comment by JonRowe** [comment]
Nevermind then, I can't plan that far ahead.

**Comment by JonRowe** [comment]
Nevermind then, I can't plan that far ahead.

**Comment by JonRowe** [comment]
Actually I can do july, but any later than that is a no no.

**Comment by joshuapaling** [comment]
Hey @JonRowe are you saying:

a) "not interested in doing this after July"? In which case, we'll try and move one of the other speakers back a month, as I think lots of people would like this talk.
or
b) "interested at sometime in the next few months, but can't commit to an exact month"? In which case, we'll leave this issue open, and do it whenever you're available over the next few months (after July).

The only thing I'd say is it would be good if we could lock you in a month in advance, so we can announce at the prior RORO that you'll be doing a Q and A, and people have that month to send you questions.

**Comment by JonRowe** [comment]
I can't commit to August or September or possibly even October.

**Comment by JonRowe** [comment]
And by then I'll probably have lost interest :P

**Comment by joshuapaling** [comment]
OK cool, we'll see if anyone's happy to move.

**Comment by joshuapaling** [comment]
Hey Jon, can we lock you in for July? And then we'll announce it this month, so people can send questions your way.

**Comment by JonRowe** [comment]
👍

**Comment by joshuapaling** [comment]
How would you prefer to recieve questions? Should people tweet you, or ask them here in this issues list, or other...?

**Comment by JonRowe** [comment]
I don't mind, probably a nice idea to have them on here but I'll take tweet/slack/mailing list too

**Comment by joshuapaling** [comment]
Yep, I agree.

**Comment by JonRowe** [comment]
Any I receive by other means I'll paste here

**Comment by JonRowe** [comment]
Reactions will be counted as votes :P

**Comment by joshuapaling** [comment]
Cool, I've added an rspec-questions label for this purpose.
