### ISSUE TITLE
RSpec - Questions for Jon next month

### ISSUE THREAD

**Issue by joshuapaling** [rails-oceania/roro#98]
As you may know, RSpec core maintainer Jon Rowe will be giving a Q and A talk next month. Have an RSpec question you'd like Jon to answer? Ask below!

**Comment by holodigm** [comment]
Why Jon? Why?

**Comment by JuanLUJoanne** [comment]
Good Morning, I want to ask how to write the spec for the model chain object?
something like this: `transfer.from_line_item.account.user.parent.try(:name)`

**Comment by simonhildebrandt** [comment]
What's the neatest way to do an order-independent test of the contents of an array? I've seen people do weird hacks like sorting both before testing, but that seems ugly. Matcher composition is pretty awesome - how does array-order-independence fit with that?

**Comment by NotJonRowe** [comment]
1. How do you allocate time to OSS work?

2. If testing frameworks were made of icecream, which flavour would rspec be?

**Comment by mootpointer** [comment]
Looking at testing frameworks in other languages, in particular the
decision of ExUnit (Elixir) to avoid deeply nested contexts, do you think
that feature (deeply nested contexts) has been a problem for RSpec?

**Comment by joshuapaling** [comment]
Not really an rspec specific question, but I'd like to know:

- how much time per week do you spend on rspec?
- how much time did you have to invest to get up to 'core member' level? Huge amounts? Or less than you might expect?
- do you do it just for fun? And is it always fun? Are there times when you want to just quit it? Are there times when you're under pressure to complete a feature or meet a deadline and it's basically "just like work but without the pay"?

**Comment by rudyyazdi** [comment]
Thanks @joshuapaling  and @NotJonRowe :)

I've got one for you. I am working on an integration app which creates and removes a ton of files in the temp folder. Since I am a paranoid person, I would like to be able to compare all my files before and after the whole suite to make sure nothing was added or removed:

So I was going to ask what is the cleanest way to do a `@before_files = Dir["**/*.*"]` before the whole suite and another `@after_files = Dir["**/*.*"]` and finally something like:

```ruby
expect(@before_files).to match(@after_files)
```

Thanks :)
Cheers,

**Comment by JonRowe** [comment]
From slack:
> RSpec in a Rails 5 project using some non-standard directory structure stuff, I am currently (in `spec/rails_helper.rb`) doing this: `RSpec::Rails::DIRECTORY_MAPPINGS[:foo] = %w(spec foo)` to automatically tag specs with type foo to be lazy and avoid doing it per file (in order to use spec support stuff like shared contexts).

> First, it seems a bit non standard so I’m wondering if this is a good/bad idea as far as you are concerned? is there a better way?

> Second, I have hit an edge case where I would quite like to be able to tag specs in both `spec/baz` and `spec/bar` with type `:qux`
seems like the approach i’m using won’t permit that. is there a direction you can point me in that makes sense for this case?

**Comment by tracymu** [comment]
Thanks so much for this last week @JonRowe it was a really great session!

Don't forget to dob in any other gem maintainers you think might do a session like this, because it seems a good format
