### ISSUE TITLE
From 1 to 6 - guide for self learner to become intermediate rails developer

### ISSUE THREAD

**Issue by wayne5540** [rails-oceania/roro#99]
I've been asked many times about how to become a intermediate developer or how to find a RoR job from people who learned RoR themselves as their first language/framework. Most of them have basic knowledge of  ruby on rails, html, css, javascript by finished their first RoR project (A CRUD website) but got stuck on this level for 2 reasons:  
1. Don't know what/how to learn next, because most of the tutorials end here.
2. Can't find a developer job to sharp their skill because lack of some practical experiences/skills.

See? It's a infinite loop! There is a gap between **people learned themselves and want to find a job (or go to next level)** and **people who companies would hire as junior developer**, so why not we list the to-learn checklist and give a practical project example which require all skills on the checklist so that people can follow and learn themselves?  
Time to break the loop 👊 

The checklist would be:

* Write user story for yourself
* Play with a front-end framework
* Open APIs for your front-end framework
* Test your API
* Play with a 3-party API
* Use worker to do something

And the example would be a **advanced TODO MVC**, I'll explain this at meetup. 😄 

====

- Is this a proposal (you want to give this talk yourself) or a request (you'd like someone else to give this talk)?
**Myself**

- Intended audience (beginners, intermediates, advanced)
**Beginners ~ Intermediates**

For proposals:

- Which month would you be ready for?
**July, 2016**

- Is this a 5m (lightning) talk, or a 15m talk?
**Probably 10 mins, could be shorter or longer**

**Comment by wayne5540** [comment]
Cool, I'm #99 😆 🚀

**Comment by tracymu** [comment]
What a great topic @wayne5540 . Thanks for volunteering to do a talk on it.

This sounds like more than a lightning talk to me - so 10-15 minutes would be good.

We have our two 'longer' talks already booked in for July, would you be available in August or September?

**Comment by wayne5540** [comment]
Thanks @tracymu, presentation at August sounds good to me 😄

**Comment by tracymu** [comment]
Awesome @wayne5540  I look forward to it :)

**Comment by tracymu** [comment]
Hey @wayne5540 , nice to meet you last night.   Let us know within the next week if you will be able to do August, so we can find an alternative if we need to. :)

**Comment by wayne5540** [comment]
Hi @tracymu, I might be in Melbourne at August, so I'm not able to do at August, I'll give you my available time as possible as I can, thanks a lot 😄 👍

**Comment by tracymu** [comment]
Ok sure no problem, let me know in the future if you are available :)

**Comment by joshuapaling** [comment]
Hi @wayne5540, are you interested in giving this talk at the September meetup?

**Comment by wayne5540** [comment]
Hi @joshuapaling yes I can do at September, thanks :)

**Comment by joshuapaling** [comment]
Sweet, see you there!

**Comment by tracymu** [comment]
Hey @wayne5540  Actually I can see that your talk might be too similar (though I understand not the same) as this one we already booked for September https://github.com/rails-oceania/roro/issues/100

Is it ok if you do October, or some other time?

**Comment by wayne5540** [comment]
Hi @tracymu, ya, #100 is very similar to this one~ nice!

Actually could you close this one for me?  I'll propose some other topics in the future.
Thanks :)

**Comment by tracymu** [comment]
Hey @wayne5540 

This is such a shame, because you have put so much detail in for the proposal, writing an actual plan/steps to help a newbie, that I think it would be quite different to Rob's.

It's up to you, but perhaps you would still be willing to do this talk in the new year? I personally think it sounds great.

AND if you want to talk sooner than that, you could also propose another talk  ;)

Up to you of course.

**Comment by joshuapaling** [comment]
@wayne5540 I agree with Tracy - I think this is a great topic, and while it might not go well back-to-back with Rob's talk, it'd still be great to hear your talk another month. If you'd still like to close it, let us know. Otherwise, let's schedule it in for another month.

**Comment by wayne5540** [comment]
Hi @joshuapaling, thanks but I'm not interesting in this topic now, maybe in the future. I'm working on something else and considering giving another talk after it's done, so please help me close this one, thanks 👍

**Comment by joshuapaling** [comment]
No worries.
